//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CoolServ.rc
//
#define IDS_NETERR_GENERIC              1
#define IDS_NETERR_SELECTSERVICE        2
#define IDS_NETERR_FILLSERVICE          3
#define IDC_COMMANDS_OPTIONS            3
#define IDS_NETERR_JOINSESSION          4
#define IDS_NETERR_HOSTSESSION          5
#define IDS_NETERR_INIT                 6
#define IDS_REZBASE                     7
#define IDS_INSERTCD                    8
#define IDS_APPNAME                     9
#define IDS_CONFIGFILE                  10
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_COOLSERV_DIALOG             102
#define IDS_ERROR_REZFILE               102
#define IDS_ERROR_LOADREZ               103
#define IDS_ERROR_LOADSERVER            104
#define IDS_ERROR_ACCESSSERVER          105
#define IDS_ERROR_MEMORY                106
#define IDS_HELP_RUNSPEED               107
#define IDS_TITLE_RUNSPEED              108
#define IDS_HELP_MISSILESPEED           109
#define IDS_TITLE_MISSILESPEED          110
#define IDS_HELP_TIMESPEED              111
#define IDS_TITLE_TIMESPEED             112
#define IDS_HELP_NIGHTCOLOR             113
#define IDS_TITLE_NIGHTCOLOR            114
#define IDS_HELP_RESPAWNSCALE           115
#define IDS_TITLE_RESPAWNSCALE          116
#define IDS_HELP_HEALSCALE              117
#define IDS_TITLE_HEALSCALE             118
#define IDS_TITLE_DASHGO                119
#define IDS_HELP_DASHGO                 120
#define IDS_CHECKEXIT                   121
#define IDS_CONSOLE_INITSERVER          122
#define IDS_CONSOLE_SERVERINITED        123
#define IDS_CONSOLE_UNABLETOHOST        124
#define IDS_CONSOLE_SERVERRUNNING       125
#define IDS_CONSOLE_LASTPLAYERLEFT      126
#define IDS_CONSOLE_UNABLETOSTARTWORLD  127
#define IDR_MAINFRAME                   128
#define IDS_DEFAULTSERVERNAME           128
#define IDD_SHOGOSERVER                 129
#define IDS_SPYGAMENAME                 129
#define IDD_GAMESERVER                  129
#define IDS_REAL_APPNAME                130
#define IDS_SPYGAMEVER                  131
#define IDS_SPYGAMEKEY                  132
#define IDS_WEBGAMENAME                 133
#define IDS_WEBGAMEVER                  134
#define IDS_WEBREGURL                   135
#define IDC_SERVER_MESSAGES             1000
#define IDC_STARTSERVER                 1001
#define IDC_SHUTDOWNSERVER              1002
#define IDC_SERVICELIST                 1002
#define IDC_SERVER_NAME                 1003
#define IDC_BACK                        1003
#define IDC_PLAYER_LIST                 1004
#define IDC_NEXT                        1004
#define IDC_WORLD_NAME                  1006
#define IDC_RESOURCES                   1008
#define IDC_DEATHMATCH                  1008
#define IDC_COMMAND_BOX                 1009
#define IDC_COOPERATIVE                 1009
#define ID_MY_QUIT                      1010
#define IDC_CAPTURETHEFLAG              1010
#define IDC_SETTINGS                    1011
#define IDC_NAME                        1011
#define IDC_APPLY                       1012
#define IDC_DEFAULTS                    1013
#define IDC_LEVELS_LIST                 1014
#define IDC_PLAYERS_LIST                1015
#define IDC_PLAYERS_BOOT                1016
#define IDC_CONSOLE_COMMAND             1018
#define IDC_SERVER                      1019
#define IDC_QUIT                        1020
#define IDC_CONSOLE_WINDOW              1021
#define IDC_AFTERFRAGS                  1022
#define IDC_FRAGS                       1023
#define IDC_AFTERMINUTES                1024
#define IDC_MINUTES                     1025
#define IDC_GAMELIST                    1029
#define IDC_RETAILLIST                  1030
#define IDC_CUSTOMLIST                  1031
#define IDC_ADDRETAIL                   1032
#define IDC_ADDCUSTOM                   1033
#define IDC_REMOVE                      1034
#define ID_INIT                         1035
#define IDC_SERVER_VERSION              1036
#define IDC_SERVER_TIME                 1037
#define IDC_SERVER_SERVICE              1038
#define IDC_GAME_PLAYERS                1039
#define IDC_GAME_CURLEVEL               1040
#define IDC_GAME_NEXTLEVEL              1041
#define IDC_GAME_TIME                   1042
#define IDC_GAME_GOAL                   1043
#define IDC_CONSOLE_CLEAR               1044
#define IDC_MAXPLAYERS                  1044
#define IDC_CONSOLE_SEND                1045
#define IDC_PORT                        1045
#define IDC_COMMANDS_NEXTLEVEL          1046
#define ID_UPDATE                       1047
#define IDC_SERVERREG                   1048
#define IDC_UPDATEINFO                  1049
#define IDC_SOURCELIST                  1050
#define IDC_USEGAMESPY                  1050
#define IDC_DESTLIST                    1051
#define IDC_ADD                         1052
#define IDC_SAVE                        1053
#define IDC_TRACTORBEAM                 1054
#define IDC_DOUBLEJUMP                  1055
#define IDC_RAMMINGDAMAGE               1056
#define IDC_RUNSPEED                    1057
#define IDC_MISSILESPEED                1058
#define IDC_RESPAWNSCALE                1059
#define IDC_HEALSCALE                   1060
#define IDC_HELP_RUNSPEED               1061
#define IDC_HELP_MISSILESPEED           1062
#define IDC_PORT_TEXT                   1062
#define IDC_TIMESPEED                   1063
#define IDC_NIGHTCOLOR                  1064
#define IDC_HELP_TIMESPEED              1065
#define IDC_HELP_NIGHTCOLOR             1066
#define IDC_HELP_RESPAWNSCALE           1067
#define IDC_HELP_HEALSCALE              1068
#define IDC_COLORPICKER                 1069

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
