// ----------------------------------------------------------------------- //
//
// MODULE  : RiotSoundTypes.h
//
// PURPOSE : Riot sound types
//
// CREATED : 11/12/97
//
// ----------------------------------------------------------------------- //

#ifndef __RIOTSOUNDTYPES_H__
#define __RIOTSOUNDTYPES_H__

#define SOUNDPRIORITYBASE_MISC		0
#define SOUNDPRIORITYBASE_AI		2
#define SOUNDPRIORITYBASE_PLAYER	4

#define SOUNDPRIORITYMOD_LOW		0
#define SOUNDPRIORITYMOD_MEDIUM		1
#define SOUNDPRIORITYMOD_HIGH		2

#define SOUNDPRIORITY_MISC_LOW		SOUNDPRIORITYBASE_MISC + SOUNDPRIORITYMOD_LOW
#define SOUNDPRIORITY_MISC_MEDIUM	SOUNDPRIORITYBASE_MISC + SOUNDPRIORITYMOD_MEDIUM
#define SOUNDPRIORITY_MISC_HIGH		SOUNDPRIORITYBASE_MISC + SOUNDPRIORITYMOD_HIGH
#define SOUNDPRIORITY_AI_LOW		SOUNDPRIORITYBASE_AI + SOUNDPRIORITYMOD_LOW
#define SOUNDPRIORITY_AI_MEDIUM		SOUNDPRIORITYBASE_AI + SOUNDPRIORITYMOD_MEDIUM
#define SOUNDPRIORITY_AI_HIGH		SOUNDPRIORITYBASE_AI + SOUNDPRIORITYMOD_HIGH
#define SOUNDPRIORITY_PLAYER_LOW	SOUNDPRIORITYBASE_PLAYER + SOUNDPRIORITYMOD_LOW
#define SOUNDPRIORITY_PLAYER_MEDIUM SOUNDPRIORITYBASE_PLAYER + SOUNDPRIORITYMOD_MEDIUM
#define SOUNDPRIORITY_PLAYER_HIGH	SOUNDPRIORITYBASE_PLAYER + SOUNDPRIORITYMOD_HIGH

#endif // __RIOTSOUNDTYPES_H__