// EventNames.h
//
// Contains #defines for all user interface events. This allows them
// to be easily synced and prevents type-o errors.
//
// Author: John O'Rorke
// Createdd 7/10/00
//
// Note: UIE = User Input Event
//

//The proper way to name an event is <family name>.<event>, or just <event> if
//it is global. For example, an input event that only occurs when doing move 
//should be called NavMove.Forward, or something along those lines. Events in
//a family will only conflict with other events in that family.

#ifndef __EVENTNAMES_H__
#define __EVENTNAMES_H__

#define UIE_TRACKER_FOCUS				"Focus"
#define UIE_SELECT_DEPTH				"Select Depth"
#define UIE_APPLY_TEXTURE_CLICK			"Apply Texture Click"
#define UIE_APPLY_TEXTURE_TO_SEL		"Apply Texture to Sel"
#define UIE_REMOVE_TEXTURE				"Remove Texture"
#define UIE_TEST_RENDER_SPEED			"Test Render Speed"
#define UIE_SPLIT_BRUSH					"Split Brush"
#define UIE_SELECT_NONE					"Select None"
#define UIE_SET_GRID_FORWARD			"Set Grid Dir Forward"
#define UIE_SET_GRID_RIGHT				"Set Grid Dir Right"
#define UIE_SET_GRID_UP					"Set Grid Dir Up"
#define UIE_INIT_TEXTURE_SPACE			"Init Texture Space"
#define UIE_DELETE						"Delete"
#define UIE_NUDGE_UP					"Nudge Up"
#define UIE_NUDGE_DOWN					"Nudge Down"
#define UIE_NUDGE_LEFT					"Nudge Left"
#define UIE_NUDGE_RIGHT					"Nudge Right"
#define UIE_REMOVE_EDGES				"Remove Edges"
#define UIE_DELETE_EDGES				"Delete Edges"
#define UIE_SPLIT_EDGE					"Split Edge"
#define UIE_DELETE_TAGGED_POLIES		"Delete Tagged Polies"
#define UIE_GRID_TO_POLY				"Grid To Poly"
#define UIE_TAG_POLY_VERTS				"Tag Poly Verts"
#define UIE_FLIP_NORMAL					"Flip Normal"
#define UIE_ORBIT_VERTEX				"Orbit Vertex"
#define UIE_NODE_ROTATE					"Rotate Node"
#define UIE_NODE_ROTATE_STEP			"Rotate Node.Step"
#define UIE_TEXTURE_MOVE				"Texture Move"
#define UIE_TEXTURE_MOVE_ROTATE			"Texture Move.Rotate"
#define UIE_TEXTURE_MOVE_SCALE			"Texture Move.Scale"
#define UIE_TEXTURE_MOVE_STEP			"Texture Move.Step"
#define UIE_BRUSH_SIZE					"Brush Size"
#define UIE_OBJECT_SIZE					"Object Size"
#define UIE_CURVE_EDIT					"Edit Curve"
#define UIE_FAR_DIST					"Far Distance"
#define UIE_GRID_SIZE					"GridSize"
#define UIE_MARKER_MOVE					"Move Marker"
#define UIE_MOVE_VERT					"Move Poly Vert"
#define UIE_MOVE_VERT_SNAP				"Move Poly Vert.Snap"
#define UIE_MOVE_VERT_PERP				"Move Poly Vert.Perp"
#define UIE_MOVE_SEL_VERT				"Move Selected Vert"
#define UIE_MOVE_IMM_VERT				"Move Immediate Vert"
#define UIE_NODE_MOVE_LOCK_AXIS			"Node Move.Lock Axis"
#define UIE_NODE_MOVE_CLONE				"Node Move.Clone"
#define UIE_SCALE_POLY					"Scale Poly"
#define UIE_SCALE_POLY_DIVIDE			"Scale Poly.Divide"
#define UIE_SCALE_POLY_EXTRUDE			"Scale Poly.Extrude"
#define UIE_SCALE_VERT_SEL				"Scale Selected Verts"
#define UIE_SCALE_VERT_IMM				"Scale Immediate Vert"
#define UIE_EXTRUDE_POLY				"Extrude Poly"
#define UIE_EXTRUDE_POLY_SNAP			"Extrude Poly.Snap"
#define UIE_EXTRUDE_POLY_BRUSH			"Extrude Poly.Brush"
#define UIE_MOVE_NODE_HANDLE			"Move Node Handle"
#define UIE_SNAP_NODE					"Move Node Snap"
#define UIE_MOVE_NODE_PERP				"Move Node Perp"
#define UIE_NAV_MOVE					"Nav Move"
#define UIE_NAV_MOVE_PERP				"Nav Move.Perp"
#define UIE_NAV_MOVE_FAST				"Nav Move.Fast"
#define UIE_NAV_ARC_ROTATE				"Nav Arc Rotate"
#define UIE_NAV_ARC_ROTATE_ROLL			"Nav Arc Rotate.Roll"
#define UIE_NAV_DRAG					"Nav Drag"
#define UIE_NAV_DRAG_FAST				"Nav Drag.Fast"
#define UIE_NAV_ROTATE					"Nav Rotate"
#define UIE_NAV_ROTATE_FORWARD			"Nav Rotate.Forward"
#define UIE_NAV_ROTATE_BACKWARD			"Nav Rotate.Backward"
#define UIE_NAV_ORBIT					"Nav Orbit"
#define UIE_NAV_ORBIT_MOVE				"Nav Orbit.Move"
#define UIE_DRAW_POLY					"Draw Poly"
#define UIE_DRAW_POLY_UNDO				"Draw Poly.Undo"
#define UIE_DRAW_POLY_NEW_VERTEX		"Draw Poly.New Vertex"
#define UIE_DRAW_POLY_SPLIT				"Draw Poly.Split"
#define UIE_DRAW_POLY_ROTATE			"Draw Poly.Rotate"
#define UIE_DRAW_POLY_INSERT_EDGE		"Draw Poly.Insert Edge"
#define UIE_DRAW_POLY_VERT_SNAP			"Draw Poly.Vert Snap"
#define UIE_DRAW_POLY_CLOSE				"Draw Poly.Close"
#define UIE_TAG_ALL						"Tag All"
#define UIE_TAG_ADD						"Tag.Add"
#define UIE_TAG_INVERT					"Tag.Invert"
#define UIE_TAG_BRUSH					"Tag Brush"
#define UIE_VERT_SNAP_EDGE_SEL			"Vert Snap Edge Sel Vert"
#define UIE_VERT_SNAP_EDGE				"Vert Snap Edge"
#define UIE_VERT_SNAP_VERT_SEL			"Vert Snap Vert Sel Vert"
#define UIE_VERT_SNAP_VERT				"Vert Snap Vert"
#define UIE_JOIN_BRUSHES				"Join Brushes"
#define UIE_UNJOIN_BRUSHES				"Unjoin Brushes"
#define UIE_TRI_BRUSHES					"Triangulate Brushes"
#define UIE_MAXIMIZE_VIEW1				"Maximize View 1"
#define UIE_MAXIMIZE_VIEW2				"Maximize View 2"
#define UIE_MAXIMIZE_VIEW3				"Maximize View 3"
#define UIE_MAXIMIZE_VIEW4				"Maximize View 4"
#define UIE_RESET_VIEWPORTS				"Reset Viewports"
#define UIE_MAXIMIZE_ACTIVE_VIEW		"Maximize Active View"
#define UIE_FREEZE_SELECTED				"Freeze Selection"
#define UIE_UNFREEZE_ALL				"Unfreeze All"
#define UIE_LOCK_FOCUS					"Lock Focus"
#define UIE_ZOOM						"Zoom"
#define UIE_ZOOM_FAST					"Zoom.Fast"
#define UIE_TOGGLE_CLASS_ICONS			"Toggle Class Icons"
#define UIE_HIDE_FROZEN_NODES			"Hide Frozen Nodes"
#define UIE_CAMERA_TO_OBJECT			"Camera To Object"
#define UIE_DISCONNECT_SELECTED_PREFABS	"Disconnect Sel Prefabs"
#define UIE_EDIT_UNDO					"Undo"
#define UIE_EDIT_REDO					"Redo"
#define UIE_ADD_OBJECT					"Add Object"
#define UIE_FIT_TEXTURE_TO_POLY			"Fit Texture To Poly"
#define UIE_SHRINK_GRID_SPACING			"Shrink Grid Spacing"
#define UIE_EXPAND_GRID_SPACING			"Expand Grid Spacing"
#define UIE_APPLY_COLOR					"Apply Color"
#define UIE_TEXTURE_WRAP				"Texture Wrap"
#define UIE_TEXTURE_WRAP_SKIP			"Texture Wrap.Skip"
#define UIE_MAP_TEXTURE_COORDS			"Map Texture Coords"
#define UIE_MAP_TEXTURE_TO_VIEW			"Map Texture to View"
#define UIE_RESET_TEXTURE_COORDS		"Reset Texture Coords"
#define UIE_REPLACE_TEXTURES			"Replace Textures"
#define UIE_REPLACE_TEXTURES_IN_SEL		"Replace Textures In Sel"
#define UIE_SHADE_WIREFRAME				"Shade Wireframe"
#define UIE_SHADE_TEXTURES				"Shade Textures"
#define UIE_SHADE_LIGHTMAPS				"Shade Lightmaps"
#define UIE_SHADE_FLAT					"Shade Flat"
#define UIE_SELECT_TEXTURE				"Select Texture"
#define UIE_SELECT_PREFAB				"Select Prefab"
#define UIE_SELECT_BRUSH_COLOR			"Select Brush Color"
#define UIE_HIDE_INVERSE				"Hide Inverse"
#define UIE_UNHIDE_INVERSE				"Unhide Inverse"
#define UIE_HIDE_SELECTED				"Hide Selected"
#define UIE_UNHIDE_SELECTED				"Unhide Selected"
#define UIE_ROTATE_SELECTION			"Rotate Selection"
#define UIE_BIND_TO_OBJECT				"Bind To Object"
#define UIE_SELECT_TEXTURE				"Select Texture"
#define UIE_SHOW_ALL_MODELS				"Show All Models"
#define UIE_HIDE_ALL_MODELS				"Hide All Models"
#define UIE_SHOW_MODELS_OF_CLASS		"Show Models Of Class"
#define UIE_HIDE_MODELS_OF_CLASS		"Hide Models Of Class"
#define UIE_SHOW_SELECTED_MODELS		"Show Selected Models"
#define UIE_HIDE_SELECTED_MODELS		"Hide Selected Models"
#define UIE_SHOW_MODEL_POLYCOUNT		"Show Model Polycount"
#define UIE_NEXT_TEXTURE_LAYER			"Next Texture Layer"
#define UIE_BRUSH_EDIT_MODE				"Brush Edit Mode "
#define UIE_GEOMETRY_EDIT_MODE			"Geometry Edit Mode"
#define UIE_OBJECT_EDIT_MODE			"Object Edit Mode"
#define UIE_MIRROR_X					"Mirror Selected X"
#define UIE_MIRROR_Y					"Mirror Selected Y"
#define UIE_MIRROR_Z					"Mirror Selected Z"
#define UIE_SELECT_ALL					"Select All"
#define UIE_SELECT_INVERSE				"Select Inverse"
#define UIE_SELECT_CONTAINER			"Select Container"
#define UIE_ADVANCED_SELECT				"Advanced Select"
#define UIE_SCALE_SELECTION				"Scale Selection"
#define UIE_SAVE_AS_PREFAB				"Save As Prefab"
#define UIE_GENERATE_UNIQUE_NAMES		"Generate Unique Names"
#define UIE_GROUP_SELECTION				"Group Selection"
#define UIE_FLIP_BRUSH					"Flip Brush"
#define UIE_CREATE_DOME					"Create Dome"
#define UIE_CREATE_SPHERE				"Create Sphere"
#define UIE_CREATE_PLANE				"Create Plane"
#define UIE_CREATE_PYRAMID				"Create Pyramid"
#define UIE_CREATE_CYLINDER				"Create Cylinder"
#define UIE_CREATE_BOX					"Create Box"
#define UIE_TOP_VIEW					"View Top"
#define UIE_BOTTOM_VIEW					"View Bottom"
#define UIE_FRONT_VIEW					"View Front"
#define UIE_BACK_VIEW					"View Back"
#define UIE_LEFT_VIEW					"View Left"
#define UIE_RIGHT_VIEW					"View Right"
#define UIE_PERSPECTIVE_VIEW			"View Perspective"
#define UIE_NAVIGATOR_STORE				"Navigator Store"
#define UIE_NAVIGATOR_ORGANIZE			"Navigator Organize"
#define UIE_NAVIGATOR_NEXT				"Navigator Next"
#define UIE_NAVIGATOR_PREVIOUS			"Navigator Previous"
#define UIE_MARKER_CENTER				"Center Marker"
#define UIE_CENTER_SEL_ON_MARKER		"Center Selection On Marker"
#define UIE_ROTATE_SELECTION_LEFT		"Rotate Selection Left"
#define UIE_ROTATE_SELECTION_RIGHT		"Rotate Selection Right"
#define UIE_MIRROR_TEXTURE_X			"Mirror Texture X"
#define UIE_MIRROR_TEXTURE_Y			"Mirror Texture Y"
#define UIE_MATCH_TEXTURE_COORDS		"Match Texture Coords"

#endif

