//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dedit.rc
//
#define IDC_BUTTON_ERROR_AUTO_RESOLVE   2
#define ID_BUTTON_GENERATE              2
#define IDC_BUTTON_SELECT_BRUSHES       2
#define IDC_BUTTON_SEARCH               2
#define ID_PALETTE_ADD                  3
#define ID_SAVE_BUTTON                  3
#define ID_CLEAR                        3
#define IDC_BUTTON_RESET_ALL_DETECTORS  3
#define IDC_BUTTON_LIST                 3
#define ID_BUTTON_NEWEFFECTGROUP        3
#define ID_BUTTON_SAVE                  3
#define ID_BIND                         4
#define ID_BUTTON_EDITEFFECTGROUP       4
#define IDC_BUTTON_UPDATE               4
#define ID_SAVE                         5
#define ID_LOAD                         6
#define ID_RESETALL                     7
#define ID_RESET                        8
#define IDD_ABOUTBOX                    100
#define CG_ID_VIEW_CREZBAR              103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_ADVANCEDSELECT              105
#define IDS_TEXTURE_ALREADY_EXISTS      105
#define IDD_PROPPAGE_UNDO               106
#define CG_ID_VIEW_PROJECTBAR           106
#define IDD_NEWPROJECT                  107
#define IDS_INVALIDMIPPCX               107
#define CG_ID_VIEW_MYDIALOGBAR          108
#define IDD_NAVIGATORDLG                109
#define CG_IDR_POPUP_WORLDLIST          109
#define IDS_WORLD_ALREADY_EXISTS        109
#define IDD_NAVIGATORSTOREDLG           110
#define IDS_SPRITE_ALREADY_EXISTS       110
#define IDS_KEYS                        111
#define IDD_IMPORT_OBJECT               112
#define IDS_EDIT_MODE                   112
#define CG_IDR_POPUP_TEXTURELIST        113
#define IDS_SOUND_ALREADY_EXISTS        113
#define IDD_IMPORT_OBJ_FILE_DIALOG      113
#define IDR_MAINFRAME_MODE_MENUS        114
#define CG_IDS_PHYSICAL_MEM             114
#define IDD_PRIMSPHERE                  115
#define CG_IDS_DISK_SPACE               115
#define IDD_POPUP_NOTE_DLG              116
#define CG_IDS_DISK_SPACE_UNAVAIL       116
#define IDD_GENERATE_UNIQUE_NAMES       117
#define IDS_EXTENSION_DELIMITER         117
#define IDD_OBJECT_BROWSER              118
#define IDS_LAYOUT_EXTENSION            118
#define IDS_WORLDEXTENSION              119
#define IDD_NAME_CHANGE_REPORT          120
#define CG_IDR_POPUP_REGION_VIEW        120
#define IDS_BARE_DAT_EXTENSION          120
#define IDB_SPLASH                      121
#define IDS_BARE_TEX_EXTENSION          121
#define IDD_EXPORT_OBJ_FILE_DLG         121
#define CG_IDR_POPUP_FRAMELIST          122
#define IDS_TEXTURE_EXTENSION           122
#define IDD_KEYCONFIG                   122
#define IDS_BARE_MODEL_EXTENSION        123
#define CG_IDR_POPUP_SOUNDS_DLG         124
#define IDS_MODEL_EXTENSION             124
#define CG_IDR_POPUP_MODELS_DLG         125
#define IDS_MODEL_ALREADY_EXISTS        125
#define IDD_BINDKEYDLG                  125
#define IDS_ERROR_OPENING_MODEL         126
#define CG_IDR_POPUP_TEXTUREPALETTE     127
#define IDS_LOD_COUNT                   127
#define IDD_LTALOADING                  127
#define IDR_MAINFRAME                   128
#define IDR_LOADANIM                    128
#define IDR_DEDITTYPE                   129
#define IDD_SOLIDALPHA                  129
#define IDS_ENTERWORLDNAME              130
#define IDD_SCALESELECT                 130
#define IDD_WORLDS_TABDLG               131
#define IDS_NEWWORLD                    131
#define IDI_WORLDS_TAB_ICON             132
#define IDS_ERRORRUNNINGPREPROCESSOR    132
#define IDD_TEXTURE_BATCHRELOAD         132
#define IDI_SPRITES_TAB_ICON            133
#define IDS_CANTFINDCLASSMODULE         133
#define IDS_WORLDNAME                   134
#define IDD_LIGHTATTENUATIONEDIT        134
#define IDS_NUMBRUSHES                  135
#define CG_IDR_POPUP_WORLDLIST_NOITEM   135
#define IDS_NUMPOLIES                   136
#define IDD_TEXTURE_CUBEMAP             136
#define IDS_NUMPOINTS                   137
#define IDD_PROPPAGE_MODELS             137
#define IDS_ERROR_OPENING_WORLD         138
#define IDD_STRINGDLG                   139
#define IDS_CORRUPTED_FILE              139
#define IDS_DELETEWORLDS_MAKESURE       140
#define IDD_PROPPAGE_CONTROLS           140
#define IDS_DAT_EXTENSION               141
#define IDC_CURSOR_ROTATE_Y             141
#define IDI_SOUNDS_TAB_ICON             142
#define IDS_BARE_SPRITE_EXTENSION       142
#define IDC_CURSOR_HAND                 142
#define IDS_OUTOFMEMORY_SAVING          143
#define IDC_CURSOR_ROTATE_X             143
#define IDI_MODELS_TAB_ICON             144
#define IDS_BARE_ED_EXTENSION           144
#define IDC_CURSOR_ROTATE               144
#define IDS_ERROROPENINGFILES           145
#define IDC_CURSOR_ROTATE_Z             145
#define IDD_SPRITEEDIT_DLG              146
#define IDS_REZFILE_EXTENSION           146
#define IDD_PROPPAGE_MISC               147
#define IDS_ERRORBUILDINGREZFILE        147
#define IDS_WAV_EXTENSION               148
#define IDS_WAV_FILEMASK                149
#define IDD_COLORSELECT_DLG             150
#define IDS_BARE_SOUND_EXTENSION        150
#define IDS_MODEL_FILEMASK              151
#define IDD_ADDPATCH                    151
#define CG_IDR_POPUP_SPRITE_DLG         152
#define IDS_SPRITE_EXTENSION            152
#define IDD_SETPATCHRESOLUTION          152
#define IDS_NEWSPRITE                   153
#define IDD_AUTOTEXTURE_OPTIONS         153
#define IDD_ADDOBJECTDLG                154
#define IDS_ENTERSPRITENAME             154
#define IDD_CLASSDLG                    155
#define IDS_SPRITE_EDITOR_TITLE         155
#define IDB_PROJECT_ICONS               156
#define IDS_ERROR_SAVING_SPRITE         156
#define IDD_PROPERTIES                  157
#define IDS_SPRITE_FRAMERATE            157
#define IDS_ERROROPENINGQUAKEMAP        158
#define IDS_COULDNT_LOAD_CODE_FILE      159
#define IDD_WORLDINFO                   160
#define IDS_ERRORLOADINGPALETTES        160
#define IDS_BINARY_ALREADY_EXISTS       161
#define IDS_CODE_ALREADY_EXISTS         162
#define IDS_IMPORT_TEXTURE              163
#define IDR_CICON_TERRAIN               163
#define IDS_SCRIPT_FILEMASK             164
#define IDR_WORLDEDIT_TOOLBAR           164
#define IDR_CICON_DIRLIGHT              164
#define IDS_NOTEPAD_APPNAME             165
#define IDR_CICON_INSIDEDEF             165
#define IDS_ONLY_BINARY_FILE_EXISTS     166
#define IDR_CICON_LIGHT                 166
#define IDS_DELETE_CODEFILES_MAKESURE   167
#define IDR_CICON_OBJECTLIGHT           167
#define IDR_ENTERCLASSNAME              168
#define IDR_CICON_OUTSIDEDEF            168
#define IDS_ERRORCREATING_CODEFILE      169
#define IDR_CICON_SKYPOINTER            169
#define IDS_CHOOSE_OBJECT_TYPE          170
#define IDR_NODEVIEW_TOOLBAR            170
#define IDR_CICON_DEMOSKYWORLDMODEL     170
#define IDS_CHOOSE_WORLD_TYPE           171
#define IDD_LEVEL_ERROR                 171
#define IDB_NODE_ICONS                  172
#define IDS_BRUSHNODEVIEW               172
#define IDD_LEVEL_ERROR_OPTIONS         172
#define IDS_SELECT_CHILD_NODE           173
#define IDD_ERROR_INFORMATION           173
#define IDS_SELECT_PARENT_NODE          174
#define IDD_UNDOWARNINGDLG              174
#define CG_IDR_POPUP_WORLD_NODE_VIEW    175
#define IDS_PROJECTBAR_TITLE            175
#define IDS_FILEOPEN_FILTER             176
#define IDR_CLASSHLP_BUT                176
#define IDD_PROJECTBAR_DLG              177
#define IDS_WORLDEDITTOOLBAR_TEXT       177
#define CG_IDR_POPUP_NODE_VIEW          178
#define IDS_NEWBRUSHCAPTION             178
#define IDD_CAMERAFOV                   178
#define IDD_NEWDIR                      179
#define IDS_ENTERBRUSHTHICKNESS         179
#define IDD_MAPTEXTURECOORDS            180
#define IDS_HOLLOWBRUSHCAPTION          180
#define IDI_OPTIONSRUN                  180
#define IDD_NODEVIEW_TABDLG             181
#define IDS_INVALIDHOLLOW               181
#define IDI_OPTIONSMODELS               181
#define IDD_VECTOR_EDIT                 182
#define IDS_NOPROJECTOPEN               182
#define IDI_OPTIONSLIGHTING             182
#define IDS_CANTCARVEWITHOUTSELECTEDBRUSH 183
#define IDI_OPTIONSMISC                 183
#define IDS_PCX_EXTENSION               184
#define IDI_OPTIONSVIEWPORT             184
#define IDD_ROTATE_SELECTION            185
#define IDS_CANTLOADPCX                 185
#define IDI_OPTIONSD3D                  185
#define IDS_INVALIDTEXTURESIZE          186
#define IDI_OPTIONSCLIPBOARD            186
#define IDB_NODE_STATE_ICONS            187
#define IDS_OUTOFDATEOBJECTS            187
#define IDI_OPTIONSCONTROLS             187
#define IDS_SCRIPT_BINARY_EXTENSION     188
#define IDD_ROTATIONEDIT                189
#define IDI_UNDO_ICON                   189
#define CG_IDR_POPUP_WORLDTREE          189
#define IDS_ENTER_PALETTE_NUMBER        189
#define IDD_TEXTURE_TABDLG              190
#define IDI_TEXTURE_TAB_ICON            190
#define IDS_OBJECT_HEIGHT               190
#define IDD_MODEL_TABDLG                191
#define IDS_BARE_SCR_EXTENSION          191
#define IDI_OPTIONSAUTOSAVE             191
#define IDD_SOUND_TABDLG                192
#define IDS_DELETEFILE_CONFIRM          192
#define IDD_SPRITE_TABDLG               193
#define IDS_ENTER_OBJECT_HEIGHT         193
#define IDD_DEBUGDLG                    194
#define IDS_RESTYPE_WORLD               194
#define IDD_TEXTUREPROP                 195
#define IDS_RESTYPE_SPRITE              195
#define IDD_PALETTE                     196
#define IDS_RESTYPE_MODEL               196
#define IDS_RESTYPE_TEXTURE             197
#define IDD_PROPPAGE_PREFAB             197
#define IDD_QUICKHELP                   198
#define IDS_RESTYPE_SOUND               198
#define IDS_OK                          199
#define IDD_RENAMERESOURCE              199
#define IDS_COMPILE                     200
#define IDD_EVENTEDITOR                 200
#define IDD_PRIMCYLINDER                201
#define IDS_LOAD                        201
#define CG_IDR_POPUP_EVENTEDITOR        201
#define IDD_ALLTEXTUREDLG               202
#define IDS_LOWONMEMORY                 202
#define IDD_MULTILINEEDIT               203
#define IDS_VIEW_PERSP                  203
#define IDD_PROPCONTROLS                204
#define IDS_VIEW_TOP                    204
#define IDD_PROPCONTROLSMODAL           205
#define IDS_VIEW_BOTTOM                 205
#define IDS_VIEW_LEFT                   206
#define IDD_EVENTLIST                   206
#define IDS_VIEW_RIGHT                  207
#define IDD_SELECTEFFECTGROUP           207
#define IDS_VIEW_FRONT                  208
#define IDD_EDITEFFECTGROUP             208
#define IDS_VIEW_BACK                   209
#define IDS_FRAME_RATE                  210
#define IDD_IMPORTBUMPMAP               210
#define IDD_ALPHAFROMCOLOR              211
#define IDS_ERR_SINGLE_BRUSH            211
#define IDB_CLASSLIST_ICONS             212
#define IDD_CLASSES_TABDLG              212
#define IDS_ERR_OPENFILE                212
#define IDI_COPY                        212
#define IDD_PROPPAGE_DISPLAY            213
#define IDS_ERR_TERRAINMAP_INVALIDDIMS  213
#define IDI_PASTE                       213
#define IDD_PROPPAGE_DIRECT3D           214
#define IDS_ERR_TERRAINMAP_INVALID      214
#define IDD_PROPPAGE_RUN                215
#define IDS_GRID                        215
#define IDD_PROPPAGE_CLIPBOARD          216
#define IDS_ERROR_BRUSH_THICKNESS       216
#define IDD_PREFAB_TABDLG               217
#define IDS_SCRIPT_EXTENSION            217
#define IDS_INVALIDBITDEPTH             218
#define IDD_PREFAB_TRACKER              218
#define IDS_ERROR_SAVING_FILE           219
#define IDD_LEVEL_TEXTURES              219
#define IDS_ERR_MULTI_BRUSH             220
#define IDD_LEVEL_TEXTURES_OPTIONS      220
#define IDR_WORLD_TYPE                  221
#define IDD_TEXTURE_SEARCH_REPLACE      221
#define IDS_INVALIDCLASSMODULE          222
#define IDI_PHYSICS_TAB_ICON            222
#define IDD_OBJECTSEARCH                222
#define CG_IDR_POPUP_PREFAB             223
#define IDS_INVALIDCLASSMODULEVERSION   223
#define IDI_SAVE_ICON                   223
#define IDD_LEVEL_ITEMS                 223
#define IDS_CHECKMAKEREZ                224
#define CG_IDR_POPUP_TEXTURETREE        224
#define IDD_PRIMPLANE                   224
#define IDS_CREATENEWORLD               225
#define CG_IDR_POPUP_PHYSICSLIST        225
#define IDD_OBJECTSELFILTER             225
#define IDS_BADWORLDDIR                 226
#define CG_IDR_POPUP_PHYSICSLIST_NOITEM 226
#define ID_DELETE_EMPTY_CONTAINERS      226
#define IDS_YAW_TEXT                    227
#define CG_IDR_POPUP_PHYSICSTREE        227
#define ID_DELETE_EMPTY_CONTAINER_CASCADE 227
#define IDS_PITCH_TEXT                  228
#define IDS_ROLL_TEXT                   229
#define IDI_LOAD_ICON                   230
#define IDS_WORLDS                      230
#define IDS_TEXTURES                    231
#define IDS_NODES                       232
#define IDS_PROPERTIES                  233
#define IDS_MODELS                      234
#define IDS_SOUNDS                      235
#define IDS_SPRITES                     236
#define IDS_OPENMIPFILE                 237
#define IDS_NUMBRUSHES2                 238
#define IDS_SAVEDTXFILE                 239
#define IDS_ERRORSAVEDTX                240
#define IDS_ERRORSAVEPCX                241
#define IDS_ERRORCREATING_PROJECT       242
#define IDS_ERRORCREATING_WORLD         243
#define IDS_ERRORCREATING_SPRITE        244
#define IDS_PHYSICS                     245
#define IDS_NEWPHYSICS                  246
#define IDS_ENTERPHYSICSNAME            247
#define IDS_VIEW                        248
#define IDS_DESCRIPTION                 249
#define IDS_ALL                         250
#define IDS_GEOMETRY                    251
#define IDS_BRUSH                       252
#define IDS_SPACEBAR                    253
#define IDS_CTRLPLUS                    254
#define IDS_SHIFTPLUS                   255
#define IDS_PLUSMOUSE                   256
#define IDS_PLUSLMB                     257
#define IDS_PLUSRMB                     258
#define IDS_PERSPECTIVE                 259
#define IDS_PARALLEL                    260
#define IDS_BRUSHOBJECT                 261
#define IDS_BRUSHGEOMETRY               262
#define IDS_ADDPOINTDESC                263
#define IDS_SNAPADDPOINTDESC            264
#define IDS_XZMOVEDESC                  265
#define IDS_YMOVEDESC                   266
#define IDS_ORIENTATIONDESC             267
#define IDS_PLANEGRIDDESC               268
#define IDS_ZOOMDESC                    269
#define IDS_FOCUSGREENDESC              270
#define IDS_TAGBRUSHDESC                271
#define IDS_UNTAGDESC                   272
#define IDS_PLACEGRIDONPOLYDESC         273
#define IDS_890                         274
#define IDS_PLACEGRIDONAXISDESC         275
#define IDS_TAGRECTDESC                 276
#define IDS_EXTRUDEPOLYDESC             277
#define IDS_SCALEPOLYDESC               278
#define IDS_EXTRUDEREMOVEPOLYDESC       279
#define IDS_SCALEREMOVEPOLYDESC         280
#define IDS_INSERTVERTDESC              281
#define IDS_DELETEGREENVERTDESC         282
#define IDS_DELETEREDPOLYDESC           283
#define IDS_PLUSMINUS                   284
#define IDS_DELETE                      285
#define IDS_INSERT                      286
#define IDS_END                         287
#define IDS_GRIDSPACINGDESC             288
#define IDS_RESIZEGRIDDESC              289
#define IDS_FLIPNORMALDESC              290
#define IDS_MOVEFARCLIPDESC             291
#define IDS_CARVEDESC                   292
#define IDS_BRUSHMODEDESC               293
#define IDS_GEOMETRYMODEDESC            294
#define IDS_OBJECTMODEDESC              295
#define IDS_APPLYTEXTUREBRUSHDESC       296
#define IDS_APPLYCOLORDESC              297
#define IDS_UNDODESC                    298
#define IDS_REDODESC                    299
#define IDS_NEXTPREVPANEDESC            300
#define IDS_F6SHIFTF6                   301
#define IDS_MOVEMARKERDESC              302
#define IDS_MOVEBRUSHOBJECTDESC         303
#define IDS_MOVEGREENVERTDESC           304
#define IDS_MOVETAGVERTSDESC            305
#define IDS_INITTEXTURESDESC            306
#define IDS_TAGVERTREDPOLYDESC          307
#define IDS_CANTFINDCLIENTEXE           308
#define IDS_WORLDFILEDOESNOTEXIST       309
#define IDS_RUNWORLDDLG_TEXT            310
#define IDS_ABOUTWARN                   311
#define IDS_VERSION                     312
#define IDS_FILESAVEAS_FILTER           313
#define IDS_NOSELTEXTURE                314
#define IDS_REZFILEFILTER               315
#define IDS_CANTOPENOUTPUTREZFILE       316
#define IDS_NUMBER_STRING               317
#define IDS_SURFACEFLAGS                318
#define IDS_ENTERSURFACEFLAGS           319
#define IDS_ERR_WRITING_TO_TEXTURE      320
#define IDS_ERRORLOADINGDTX             321
#define IDS_SIZEDOESNTMATCH             322
#define IDS_ENTERTEXTUREFLAGS           323
#define IDS_INVALID_MIPMAP_COUNT        324
#define IDS_DIRDOESNTEXIST              325
#define IDS_CANTCREATEDIRECTORY         326
#define IDS_MULTIPLETEXTURESSELECTED    327
#define IDS_ALPHA_SET_SUCCESSFUL        328
#define IDS_CLASSLIST                   329
#define IDS_APPLYTEXTURETOBRUSH         330
#define IDS_MODECYCLEDESC               331
#define IDS_CTRLPLUSALTPLUS             332
#define IDS_BUILDSTRING                 333
#define IDS_ERRORCONVERTINGTEXTURE      334
#define IDS_INVALIDMIPTGA               335
#define IDS_TGA_EXTENSION               336
#define IDS_TGA_FILEMASK                337
#define IDS_CANTLOADTGA                 338
#define IDS_PREFABS                     339
#define IDS_ERROR_OPENING_DAT           340
#define IDS_ERROR_LOADING_DAT           341
#define IDS_ERROR_SAVING_DAT            342
#define IDS_SCALE_WORLD                 343
#define IDS_SCALE_ENTER_VALUE           344
#define IDS_PHYSICSMATERIAL_ALREADY_EXISTS 345
#define IDS_ENTERLIGHTPRESETNAME        346
#define IDS_NEWLIGHTPRESET              347
#define IDS_OVERWRITE_LIGHT_PRESET      348
#define IDS_TEXRELOAD_NODIRECTORIES     400
#define IDS_TEXRELOAD_ERRORPROCESSING   401
#define IDS_TEXRELOAD_NOTFOUND          402
#define IDS_TEXRELOAD_OPENERROR         403
#define IDS_TEXRELOAD_BADFORMAT         404
#define IDS_TEXRELOAD_SAVEERROR         405
#define IDS_TEXRELOAD_CANTCONVERT       406
#define IDS_TEXRELOAD_CANTWRITE         407
#define IDS_TEXRELOAD_BADDIMS           408
#define IDC_YAWVIEW                     1008
#define IDC_IMPORT_OBJ_REVERSE_CB       1008
#define IDC_ENTEREDTEXT                 1009
#define IDC_PITCHVIEW                   1009
#define IDC_MSGTEXT                     1010
#define IDC_YAWTITLE                    1011
#define IDC_IMPORT_OBJ_FROM_3DSMAX_CHECK 1011
#define IDC_NODESOFCLASS                1012
#define IDC_PITCHTITLE                  1012
#define IDC_IMPORT_OBJ_FROM_MAYA_CHECK  1012
#define IDC_OBJECTSWITHNAME             1013
#define IDC_YAWSCROLLBAR                1013
#define IDC_IMPORT_OBJ_FROM_SOFTIMAGE_CHECK 1013
#define IDC_OBJECTNAME                  1014
#define IDC_EXPORT_HIDDEN_BRUSHES_CHECK 1014
#define IDC_MESSAGES                    1015
#define IDC_EXPORT_OBJ_FILE_AS          1015
#define IDC_COMMANDSTRING               1016
#define IDC_ROLLTITLE                   1016
#define IDC_EXPORT_OBJ_FOR_3DSMAX_CHECK 1016
#define IDC_RUNCOMMAND                  1017
#define IDC_PITCHSCROLLBAR              1017
#define IDC_EXPORT_OBJ_FOR_MAYA_CHECK   1017
#define IDHIDE                          1018
#define IDC_ROLLSCROLLBAR               1018
#define IDC_EXPORT_OBJ_FOR_SOFT_CHECK   1018
#define IDC_PROJECTDIR_LOCATION         1019
#define IDC_EXPORT_OBJ_REVERSE_NORMALS  1019
#define IDC_BUTTON_UPDATE_PROPERTIES    1019
#define IDC_SPRITEFRAMELISTPOS          1020
#define IDC_KEYLIST                     1021
#define IDC_KEYSELECT1                  1022
#define IDC_MOD_CTRL                    1023
#define IDC_FRAMERATE_TEXT              1024
#define IDC_BUILDSTRING                 1025
#define IDC_FRAMERATE_VALUE             1025
#define IDC_MOD_SHIFT                   1025
#define IDC_BUTTON_MOVEUP               1026
#define IDC_KEYSELECT2                  1026
#define IDC_BUTTON_MOVEDOWN             1027
#define IDC_FRAMERATE_SPIN              1027
#define IDC_KEYSELECT3                  1027
#define ID_BUTTON_GOTO                  1028
#define IDC_EVENT_NAME                  1028
#define IDC_BUTTON_DELETE               1029
#define IDC_EVENT_DESCRIPTION           1029
#define IDC_CLASSTREE                   1030
#define IDC_BUTTON_RENAME               1030
#define IDC_ENABLEAUTOSAVE              1030
#define IDC_LIST_NAVIGATOR_ITEMS        1031
#define IDC_EDIT_NAVIGATOR_NAME         1032
#define IDC_PALETTE_COLOR               1032
#define IDC_SPINSAVETIME                1032
#define IDC_RADIO_SELECT                1033
#define IDC_SPINNUMBACKUPS              1033
#define IDC_RADIO_DESELECT              1034
#define IDC_BACKUPPATH                  1034
#define IDC_CHECK_MATCH_WHOLE_WORD      1035
#define IDC_BUTTON_CHANGE_CLASS         1036
#define IDC_DELETEONEXIT                1036
#define IDC_LIST_CLASSES                1037
#define IDC_BASEREZ_TREE                1037
#define IDC_LTALOADFILENAME             1037
#define IDC_RADIO_NODEVIEW_CLASS        1038
#define IDC_RADIO_NODEVIEW_NAME         1039
#define IDC_LOADANIMCTRL                1039
#define IDC_RADIO_NODEVIEW_BOTH         1040
#define IDC_SCALEX                      1040
#define IDC_SCALEXAMOUNT                1041
#define IDC_CHECK_SHOW_HIERARCHY        1042
#define IDC_RADIO_PERCENTAGE            1042
#define IDC_OBJECTTREE                  1043
#define IDC_LIST_RECENT_CLASSES         1043
#define IDC_RADIO_WORLDUNITS            1043
#define IDC_UNIFORMVALUES               1044
#define IDC_BUTTON_REMOVE               1045
#define IDC_SCALEY                      1045
#define IDC_LIST_COLOR_CHOICES          1046
#define IDC_SCALEYAMOUNT                1046
#define IDC_ET_UOFFSET                  1047
#define IDC_BUTTON_CHANGE_COLOR         1047
#define IDC_SCALEZ                      1047
#define IDC_ET_VOFFSET                  1048
#define IDC_STATIC_COLOR_BOX            1048
#define IDC_SCALEZAMOUNT                1048
#define IDC_CHECK_ZBUFFER_LINES         1049
#define IDC_KEEPTEXTURES                1049
#define IDC_CHECK_SHADE_POLYGONS        1050
#define IDC_CHECK_SATURATE_LIGHTMAPS    1050
#define IDC_NODEVIEW_TREE               1051
#define IDC_CHECK_SHOW_SURFACE_COLOR    1051
#define IDC_ET_ROTATION                 1052
#define IDC_CLASSNAME_TEXT              1052
#define IDC_CHECK_INVERT_MOUSE_Y        1052
#define IDC_ADJUSTMAPPINGS              1052
#define IDC_CHECK_AUTO_LOAD_LIGHTMAPS   1053
#define IDC_BASEPATH                    1054
#define IDC_CHECK_ORIENT_OBJECT_BOXES   1054
#define IDC_EC_ROTATION                 1055
#define IDC_WORLDNAME                   1055
#define IDC_CHECK_SHOW_SELECTED_DECALS  1055
#define IDC_VECTOR_EDIT                 1056
#define IDC_NUMBRUSHES                  1056
#define IDC_NOCOMPRESSION               1056
#define IDC_CHECK_DISPLAY_CLASS_ICONS   1056
#define IDC_VECTOR_EDITX                1056
#define IDC_NUMPOLIES                   1057
#define IDC_OK                          1057
#define IDC_VECTOR_EDITY                1057
#define IDC_RADIO_VERTEX_RULE           1058
#define IDC_NUMPOINTS                   1058
#define IDC_CANCEL                      1058
#define IDC_VECTOR_EDITZ                1058
#define IDC_RADIO_SELECTED_BRUSHES      1059
#define IDC_VECTOR_EDIT_INC             1059
#define IDC_SHOWRESULTS                 1060
#define IDC_NODESWITHPROPERTY           1061
#define IDC_SPIN_HANDLE_SIZE            1062
#define IDC_EDIT_HANDLE_SIZE            1063
#define IDC_PROPNAME                    1063
#define IDC_ET_USCALE                   1064
#define IDC_EDIT_VERTEX_SIZE            1064
#define IDC_PROPTYPECOMBO               1064
#define IDC_ET_VSCALE                   1065
#define IDC_SPIN_VERTEX_SIZE            1065
#define IDC_PROPVALUE                   1065
#define IDC_CH_STICK                    1066
#define IDC_BUTTON_RESET                1066
#define IDC_SHOW_COLORS                 1066
#define IDC_RADIO_UPDATE_PROPERTIES     1067
#define IDC_CH_XZONLY                   1067
#define IDC_A_COEF                      1067
#define IDC_EDIT_CLASS_ICON_SIZE        1067
#define IDC_RADIO2                      1068
#define IDC_B_COEF                      1068
#define IDC_SPIN_CLASS_ICON_SIZE        1068
#define IDC_CHECK_USE_D3D_AS_DEFAULT    1069
#define IDC_C_COEF                      1069
#define IDC_COMBO_D3DDEVICES            1070
#define IDC_A_EXP                       1070
#define IDC_COMBO_D3D_MODE              1071
#define IDC_B_EXP                       1071
#define IDC_STATIC_DEVICE_TEXT          1072
#define IDC_FULLBRITE                   1072
#define IDC_C_EXP                       1072
#define IDC_STATIC_MODE_TEXT            1073
#define IDC_32BITSYSCOPY                1073
#define IDC_A_COEF_SPIN                 1073
#define IDC_PREFER16BIT                 1074
#define IDC_B_COEF_SPIN                 1074
#define IDC_EDIT_SIDES                  1075
#define IDC_PREFER4444                  1075
#define IDC_C_COEF_SPIN                 1075
#define IDC_CHECK_DISABLE_D3D_DEFAULT_ORTHO 1075
#define IDC_CHECK_BIND_INDIVIDUALLY     1076
#define IDC_EDIT_VERTICAL_SUBDIVISIONS  1076
#define IDC_PREFER5551                  1076
#define IDC_A_EXP_SPIN                  1076
#define IDC_CHECK_DISPLAY_REPORT        1077
#define IDC_CHECK_GROUP_BY_TYPE         1077
#define IDC_EDIT_RADIUS                 1077
#define IDC_CHECK_GENERATE_UNIQUE_NAMES 1077
#define IDC_FORMAT_32BIT                1077
#define IDC_B_EXP_SPIN                  1077
#define IDC_STATIC_OPERATION            1078
#define IDC_CHECK_DISPLAY_NAME_CHANGE_REPORT 1078
#define IDC_FORMAT_DXT1                 1078
#define IDC_C_EXP_SPIN                  1078
#define IDC_EDIT_EXECUTABLE             1079
#define IDC_FORMAT_DXT3                 1079
#define IDC_PRESETS                     1079
#define IDC_EDIT_WORKING_DIRECTORY      1080
#define IDC_FORMAT_DXT5                 1080
#define IDC_SAVE_PRESET                 1080
#define IDC_EDIT_PROGRAM_ARGUMENTS      1081
#define IDC_GRADIENT                    1081
#define IDC_FORMAT_32P                  1081
#define IDC_BUTTON_BROWSE               1082
#define IDC_GRAPH                       1082
#define IDC_NOSYSCACHE                  1082
#define IDC_CHECK_UPDATE_REFERENCING_PROPERTIES 1083
#define IDC_INTENSITY_MAX               1083
#define IDC_BUTTON_BROWSE_PACKER_DIR    1083
#define IDC_LIST_PROPERTIES             1084
#define IDC_CHECK_UPDATE_SELECTED_ONLY  1085
#define IDC_BLURRY_TEXTURES             1085
#define IDC_TEXTUREPROP_FLAGS           1085
#define IDC_LIGHTDEFS_STRING            1086
#define IDC_NUM_UNDOS                   1086
#define IDC_QHELPTEXT                   1087
#define IDC_TEXTURE_GROUP               1087
#define IDC_POSX                        1087
#define IDC_LIST_OBJECTS                1088
#define IDC_NUMBER_OF_MIPMAPS           1088
#define IDC_POSX_BUTTON                 1088
#define IDC_BUTTON_LOCATE               1089
#define IDC_UIMIPMAPOFFSET              1089
#define IDC_NAME                        1089
#define IDC_BUTTON_SELECT               1090
#define IDC_CYLINDER_NUSIDES            1090
#define IDC_DTX_NONS3TCMIPMAPOFFSET     1090
#define IDC_TREE_OBJECTS                1091
#define IDC_CYLINDER_HEIGHT             1091
#define IDC_DTX_COMMAND_STRING2         1091
#define IDC_CYLINDER_RADIUS             1092
#define IDC_TEXTUREPRIORITY             1092
#define IDC_NEGX                        1092
#define IDC_ABOUTWARN                   1093
#define IDC_DETAILTEXTURESCALE          1093
#define IDC_NEGX_BUTTON                 1093
#define IDC_TEXTURELB                   1094
#define IDC_DETAILTEXTUREANGLE          1094
#define IDC_POSY                        1094
#define IDC_CLASSCOMBO                  1095
#define IDC_LIST_NAMES                  1095
#define IDC_POSY_BUTTON                 1095
#define IDC_STATIC_FRICTION             1095
#define IDC_MULTILINEEDIT               1096
#define IDC_BUTTON_ROTATE_90            1096
#define IDC_DATAFORMAT                  1096
#define IDC_NEGY                        1096
#define IDC_KINETIC_FRICTION            1096
#define IDC_SAVETIME                    1097
#define IDC_BUTTON_ROTATE_45            1097
#define IDC_STATIC_SPRITE_TEXTURES      1097
#define IDC_DATAFORMAT2                 1097
#define IDC_NEGY_BUTTON                 1097
#define IDC_RESTITUTION                 1097
#define IDC_APPLY                       1098
#define IDC_BUTTON_ROTATE_180           1098
#define IDC_DATAFORMAT3                 1098
#define IDC_NUMBACKUPS                  1098
#define IDC_POSZ                        1098
#define IDC_TYPE                        1098
#define IDC_BUTTON_ROTATE_NEG_90        1099
#define IDC_DATAFORMAT4                 1099
#define IDC_POSZ_BUTTON                 1099
#define IDC_BUTTON_ROTATE_NEG_45        1100
#define IDC_NEGZ                        1100
#define IDC_DISPLAY_COLOR               1100
#define IDC_FLIPX                       1101
#define IDC_NEGZ_BUTTON                 1101
#define IDC_MATCH_VALUE                 1101
#define IDC_CHECK_DETAIL_TEX_ENABLE     1101
#define IDC_FLIPY                       1102
#define IDC_DETAIL_TEX_SCALE            1102
#define IDC_DETAIL_TEX_ANGLE            1103
#define IDC_CHECK_DETAIL_TEX_ADDITIVE   1104
#define IDC_INFOSTRING                  1105
#define IDC_STATIC_DETAIL_TEX_SCALE     1105
#define IDC_SPRITETEXTURENAMES          1106
#define IDC_STATIC_DETAIL_TEX_ANGLE     1106
#define IDC_SCALE                       1108
#define IDC_EDIT_PERSPECTIVE_FAR_Z      1108
#define IDC_SCALESPIN                   1109
#define IDC_RADIO_PERSPECTIVE_BOX       1109
#define IDC_OFFSET                      1110
#define IDC_RADIO_PERSPECTIVE_WIREFRAME 1110
#define IDC_OFFSETSPIN                  1111
#define IDC_TEXTUREPROP_FLAGS_TEXT      1111
#define IDC_RADIO_PERSPECTIVE_SOLID     1111
#define IDC_LIGHTDEFS_STRING_TEXT       1112
#define IDC_RADIO_PERSPECTIVE_TEXTURED  1112
#define IDC_TEXTURE_GROUP_TEXT          1113
#define IDC_RADIO_ORTHOGRAPHIC_BOX      1113
#define IDC_RADIO_ORTHOGRAPHIC_WIREFRAME 1114
#define IDC_CHECK_LOW_PRIORITY_MODEL_THREAD 1115
#define IDC_NUMBER_OF_MIPMAPS_TEXT      1116
#define IDC_CHECK_DISPLAY_MODELS_AS_BOXES 1116
#define IDC_CLASS_LIST                  1117
#define IDC_UIMIPMAPOFFSET_LABEL        1117
#define IDC_EDIT_MODEL_DISPLAY_BOX_DISTANCE 1117
#define IDC_DTX_NONS3TCMIPMAPOFFSET_LABEL 1118
#define IDC_CHECK_MAXIMUM_MODEL_MEMORY_USE 1118
#define IDC_DTX_COMMAND_STRING_LABEL2   1119
#define IDC_EDIT_MODEL_MAX_MEMORY       1119
#define IDC_CHECK_ZOOM_TO_CURSOR        1119
#define IDC_PRIORITY_LABEL              1120
#define IDC_CHECK_ORBIT_AROUND_SEL      1120
#define IDC_CHECK_ALWAYS_SHOW_MODELS    1120
#define IDC_DETAILTEXTURESCALE_LABEL    1121
#define IDC_BUTTON_HOT_KEYS             1121
#define IDC_DETAILTEXTUREANGLE_LABEL    1122
#define IDC_CHECK_AUTO_CAPTURE_FOCUS    1122
#define IDC_CHECK_PARENT_FOLDER         1123
#define IDC_CHECK_TINT_SELECTED         1125
#define IDC_CHECK_TINT_FROZEN           1126
#define IDC_BUTTON_APPLY_STYLE          1126
#define IDC_CHECK_TINT_DETAIL           1127
#define IDC_COMBO_PRESET_STYLES         1127
#define IDC_EDIT_STYLE_DESCRIPTION      1128
#define IDC_CHECK_TINT_INVALID          1128
#define IDC_CHECK_PREFABS_AS_BOXES      1129
#define IDC_EDIT_PATCH_NAME             1130
#define IDC_EDIT_PATCH_X_POINTS         1131
#define IDC_EDIT_PATCH_Y_POINTS         1132
#define IDC_RADIO_PATCH_XY_POS_PLANE    1133
#define IDC_RADIO_PATCH_XZ_POS_PLANE    1134
#define IDC_RADIO_PATCH_YZ_POS_PLANE    1135
#define IDC_RADIO_PATCH_XY_NEG_PLANE    1136
#define IDC_RADIO_PATCH_XZ_NEG_PLANE    1137
#define IDC_EDIT_PATCH_WIDTH            1138
#define IDC_CHECK_SHOW_THUMBNAILS       1138
#define IDC_EDIT_PATCH_HEIGHT           1139
#define IDC_CHECK_AUTO_EXTRACT_ICONS    1139
#define IDC_RADIO_PATCH_YZ_NEG_PLANE    1140
#define IDC_CHECK_AUTO_EXTRACT_HELP     1140
#define IDC_EDIT_PATCH_X_SUBDIV         1141
#define IDC_EDIT_PATCH_Y_SUBDIV         1142
#define IDC_EDIT_SET_PATCH_RESOLUTION_X 1142
#define IDC_EDIT_SET_PATCH_RESOLUTION_Y 1143
#define IDC_EDIT_CLASS_ICON_DIR         1143
#define IDC_BROWSE_CLASS_ICON_DIR       1144
#define IDC_SPIN_MAX_MODEL_MEMORY       1146
#define IDC_SPIN_ADD_PATCH_X_RES        1147
#define IDC_SPIN_ADD_PATCH_Y_RES        1148
#define IDC_SPIN_SET_PATCH_RES_X        1148
#define IDC_SPIN_ADD_PATCH_X_CP         1149
#define IDC_SPIN_SET_PATCH_RES_Y        1149
#define IDC_STYLE_LINEAR                1149
#define IDC_SPIN_ADD_PATCH_Y_CP         1150
#define IDC_STYLE_PATH                  1150
#define IDC_RESTRICT_DIR                1153
#define IDC_PALETTE_COLORS              1154
#define IDC_ALLTEXTURE_EDIT4            1154
#define IDC_PALETTE_INDEX               1155
#define IDC_ALLTEXTURE_EDIT3            1155
#define IDC_LEVEL_ERROR_LIST            1155
#define IDC_CHECK_SHOW_ICONS            1156
#define IDC_ALLTEXTURE_EDIT2            1156
#define IDC_BUTTON_LEVEL_ERROR_OPTIONS  1156
#define IDC_PALETTE_PALNUM              1157
#define IDC_ALLTEXTURE_EDIT1            1157
#define IDC_BUTTON_SCAN_LEVEL           1157
#define IDC_BUTTON_RESOLVE_SELECTED     1158
#define IDC_STATIC_NUM_LEVEL_ERRORS     1159
#define IDC_BUTTON_SELECT_LEVEL_ERROR   1160
#define IDC_BUTTON_SELECT_ITEM_OBJECT   1160
#define IDC_LIST_ERROR_DETECTORS        1163
#define IDC_STATIC_RESOLVED_STATS       1164
#define IDC_CHECK_ENABLE_DETECTOR       1165
#define IDC_EDIT_DETECTOR_HELP_TEXT     1166
#define IDC_EDIT_ERROR_HELP_TEXT        1168
#define IDC_STATIC_ERROR_DETECTED_BY    1169
#define IDC_STATIC_ERROR_NAME           1170
#define IDC_STATIC_ERROR_RESOLVED       1171
#define IDC_STATIC_ERROR_SEVERITY       1172
#define IDC_UW_ALWAYS                   1172
#define IDC_STATIC_ERROR_NODE_NAME      1173
#define IDC_UW_NEVER                    1173
#define IDC_UW_YES                      1174
#define IDC_UW_NO                       1175
#define IDC_UW_TEXT                     1176
#define IDC_UW_SHOW_WARNINGS            1177
#define IDC_CHECK_SHOW_UNDO_WARNING     1178
#define IDC_EDIT_PACKER_DIRECTORY       1179
#define IDC_CLEAR_DEBUG_TEXT            1181
#define IDC_CHECK_AUTO_APPLY            1183
#define IDC_MAINTAINASPECT              1184
#define IDC_EDIT_HORIZONTALFOV          1187
#define IDC_EDIT_VERTICALFOV            1188
#define IDC_SPIN_HORIZONTALFOV          1189
#define IDC_SPIN_VERTICALFOV            1190
#define IDC_CHECK_SHOW_FULL_TITLE       1190
#define IDC_RADIO_UNSHADED              1191
#define IDC_CHECK_AUTO_LOAD_PROJ        1191
#define IDC_RADIO_SHADED                1192
#define IDC_CHECK_DEFAULT_COMPRESSED    1192
#define IDC_RADIO_VERTEX_LIT            1193
#define IDC_CHECK_LOAD_LYT_FILE         1193
#define IDC_RADIO_LIGHTMAPPED           1194
#define IDC_CHECK_UNDO_FREEZE_HIDE      1194
#define IDC_CHECK_LAMBERTIAN            1195
#define IDC_CHECK_SHADOWS               1196
#define IDC_EDIT_LIGHT_TIME_SLICE       1197
#define IDC_EDIT_LM_MAX_SIZE            1198
#define IDC_EDIT_MIN_LM_TEXEL           1199
#define IDC_EDIT_LM_MIN_SIZE            1200
#define IDC_EDIT_LIGHT_LEAK_DIST        1201
#define IDC_SPIN_LIGHT_TIME_SLICE       1202
#define IDC_SPIN_LM_MAX_SIZE            1203
#define IDC_SPIN_LM_MIN_SIZE            1204
#define IDC_SPIN_MIN_LM_TEXEL           1205
#define IDC_RADIO_PREFAB_BOX            1205
#define IDC_SPIN_LIGHT_LEAK_DIST        1206
#define IDC_RADIO_PREFAB_GEOMETRY       1206
#define IDC_RADIO_PREFAB_NONE           1207
#define IDC_CHECK_PREFAB_OUTLINE        1208
#define IDC_CHECK_PREFAB_ORIENTATION    1209
#define IDC_SPIN_TEX_COORD_U            1209
#define IDC_SPIN_TEX_COORD_V            1210
#define IDC_LIST_RES_RENAME             1210
#define IDC_SPIN_TEX_COORD_U_SCALE      1211
#define IDC_SPIN_TEX_COORD_V_SCALE      1212
#define IDC_SPIN_TEX_COORD_ROTATION     1213
#define IDC_EDIT_RES_RENAME_OUTDIR      1214
#define IDC_BUTTON_RES_RENAME_OUTDIR_BROWSE 1215
#define IDC_EDIT_RES_RENAME_OUTNAME     1216
#define IDC_BUTTON_RES_RENAME_ADD       1217
#define IDC_BUTTON_RES_RENAME_REMOVE    1218
#define IDC_RADIO_RES_RENAME_UPDATE_ALL 1219
#define IDC_RADIO_RES_RENAME_UPDATE_ONLY_OPEN 1220
#define IDC_EDIT_ROTATION_YAW           1220
#define IDC_EDIT_ROTATION_PITCH         1221
#define IDC_BUTTON_RES_RENAME_OUTNAME_BROWSE 1221
#define IDC_STATIC_CURR_TIME            1221
#define IDC_EDIT_ROTATION_ROLL          1222
#define IDC_STATIC_NUM_MESSAGES         1222
#define IDC_BUTTON_RES_RENAME_CLEAR     1222
#define IDC_STATIC_TRACK_MESSAGES       1223
#define IDC_EDIT_EVENT_SCALE            1224
#define IDC_EDIT_EVENT_LENGTH           1225
#define IDC_SPIN_EVENT_SCALE            1226
#define IDC_SPIN_EVENT_LENGTH           1227
#define IDC_SCROLLBAR_EVENT_TIME        1228
#define IDC_STATIC_TRACK_NAME_AREA      1232
#define IDC_EDIT_EVENT_MESSAGE          1233
#define IDC_LIST_EVENTS                 1234
#define IDC_EDIT_EVENT_IMM_MESSAGE      1234
#define IDC_EDIT_EVENT_TIME             1235
#define IDC_CHECK_MAKE_TARGETS_WRITABLE 1236
#define IDC_COMBO_GROUPLIST             1237
#define IDC_CHECK_SCALE_TEXTURE_UVS     1237
#define IDC_EDIT_NAME                   1239
#define IDC_COMBO_CHANNEL1              1240
#define IDC_EDIT_SCRIPT1                1241
#define IDC_BUTTON_BROWSESCRIPT1        1242
#define IDC_STATIC_EVENT_VIEW_AREA      1243
#define IDC_STATIC_S1P0                 1243
#define IDC_STATIC_RULER_AREA           1244
#define IDC_EDIT_S1P0                   1244
#define IDC_BUTTON_LOAD_GEN_CUBE_MAP    1244
#define IDC_STATIC_S1P1                 1245
#define IDC_EDIT_TGA_NAME               1245
#define IDC_EDIT_S1P1                   1246
#define IDC_STATIC_S1P2                 1247
#define IDC_COMBO_HEIGHT_CHANNEL        1247
#define IDC_EDIT_S1P2                   1248
#define IDC_COMBO_LUMINANCE_CHANNEL     1248
#define IDC_STATIC_S1P3                 1249
#define IDC_EDIT_HEIGHT_SCALE           1249
#define IDC_EDIT_S1P3                   1250
#define IDC_EDIT_COPYPASTE              1250
#define IDC_STATIC_S1P4                 1251
#define IDC_BUTTON_COPY                 1251
#define IDC_EDIT_S1P4                   1252
#define IDC_BUTTON_PASTE                1252
#define IDC_BUTTON_EDIT_MESSAGE         1252
#define IDC_STATIC_S1P5                 1253
#define IDC_STATIC_LUMINANCE_CHANNEL    1253
#define IDC_EDIT_S1P5                   1254
#define IDC_RADIO_ACTIONMOVE            1254
#define IDC_COMBO_CHANNEL2              1255
#define IDC_RADIO_ACTIONREPLACE         1255
#define IDC_EDIT_SCRIPT2                1256
#define IDC_BUTTON_BROWSESCRIPT2        1257
#define IDC_STATIC_S2P0                 1258
#define IDC_RICHEDIT_PREFABTEXT         1258
#define IDC_EDIT_S2P0                   1259
#define IDC_STATIC_S2P1                 1260
#define IDC_LIST_TEXTURE_INFO           1260
#define IDC_EDIT_S2P1                   1261
#define IDC_LIST_TEXTURE_STATS          1261
#define IDC_STATIC_S2P2                 1262
#define IDC_EDIT_S2P2                   1263
#define IDC_BUTTON_SAVE                 1263
#define IDC_STATIC_S2P3                 1264
#define IDC_LIST_TEXTURE_COLUMNS        1264
#define IDC_BUTTON_OPTIONS              1264
#define IDC_EDIT_S2P3                   1265
#define IDC_EDIT_REPLACEWITH            1265
#define IDC_STATIC_S2P4                 1266
#define IDC_EDIT_FIND                   1266
#define IDC_EDIT_S2P4                   1267
#define IDC_CHECK_SEARCH_FLAGS          1267
#define IDC_STATIC_S2P5                 1268
#define IDC_CHECK_SEARCH_GROUP          1268
#define IDC_EDIT_S2P5                   1269
#define IDC_CHECK_SEARCH_COMMAND        1269
#define IDC_COMBO_OVERRIDE1             1270
#define IDC_EDIT_START_DIR              1270
#define IDC_COMBO_OVERRIDE2             1271
#define IDC_BUTTON_BROWSE_DIR           1271
#define IDC_LIST_SEARCH_RESULTS         1274
#define IDC_EDIT_SEARCH_TEXT            1275
#define IDC_CHECK_CASE_SENSITIVE        1277
#define IDC_EDIT_LEVEL_DIR              1278
#define IDC_CHECK_SEARCH_PREFABS        1279
#define IDC_BUTTON_BROWSE_LEVEL_DIR     1279
#define IDC_CHECK_SEARCH_SELECTION_ONLY 1280
#define IDC_SPIN_VECTORX                1280
#define IDC_CHECK_IGNORE_HIDDEN         1281
#define IDC_SPIN_VECTORY                1281
#define IDC_CHECK_IGNORE_FROZEN         1282
#define IDC_SPIN_VECTORZ                1282
#define IDC_CHECK_AUTOAPPLY             1283
#define IDC_CHECK_SHOWFILEREFERENCES    1285
#define IDC_LIST_ITEMS                  1286
#define IDC_LIST_ITEM_OBJECTS           1287
#define IDC_RADIO_TRIANGLE              1289
#define IDC_RADIO_RECTANGLE             1290
#define IDC_EDIT_WIDTH                  1291
#define IDC_EDIT_HEIGHT                 1292
#define IDC_RADIO_POSX                  1293
#define IDC_RADIO_NEGX                  1294
#define IDC_RADIO_POSY                  1295
#define IDC_CHECK_MATCH_NAME            1295
#define IDC_RADIO_NEGY                  1296
#define IDC_EDIT_OBJECTNAME             1296
#define IDC_RADIO_POSZ                  1297
#define IDC_CHECK_MATCH_CLASS           1297
#define IDC_RADIO_NEGZ                  1298
#define IDC_BUTTON_SELALL               1300
#define IDC_BUTTON_SELNONE              1301
#define IDC_COMBO_PRESETS               1302
#define IDC_BUTTON_ADDPRESET            1303
#define IDC_BUTTON_REMOVEPRESET         1304
#define IDC_BUTTON_SELINVERT            1305
#define IDC_BUTTON_SELALL3              1306
#define IDC_BASEREZ_LIST                4005
#define IDC_PROJECTVIEW_TABS            12772
#define IDD_TEXTURE_SCALETEXTURECOORDS  30722
#define IDD_PHYSICS_TABDLG              30723
#define IDD_PHYSICS_MATERIAL            30724
#define IDD_PROPPAGE_LIGHTING           30725
#define ID_VIEW_PROJECT_WINDOW          32771
#define ID_POPUP_IMPORTTEXTURES         32772
#define IDS_PCX_FILEMASK                32773
#define IDS_DEP_EXTENSION               32774
#define IDS_PROJECTDIR_TITLE            32775
#define IDS_DIRALREADYEXISTS            32776
#define IDS_UNABLETOCREATEDIR           32777
#define IDS_DIRECTORY_DELIMITER         32778
#define IDS_SCRIPT_BINARY_FILEMASK      32779
#define IDS_TEXTURE_FILEMASK            32780
#define ID_POPUP_ADDOBJECT              32781
#define ID_POPUP_OBJECTPROPERTIES       32782
#define ID_POPUP_WORLDINFO              32783
#define ID_POPUP_SHADEMODE_WIREFRAMEPOLIES 32784
#define ID_POPUP_SHADEMODE_FLATPOLIES   32785
#define ID_POPUP_SHADEMODE_TEXTUREDPOLIES 32786
#define ID_POPUP_VIEWMODE_PERSPECTIVEVIEW 32787
#define ID_POPUP_VIEWMODE_TOPVIEW       32788
#define ID_POPUP_VIEWMODE_BOTTOMVIEW    32789
#define ID_POPUP_VIEWMODE_FRONTVIEW     32790
#define ID_POPUP_VIEWMODE_BACKVIEW      32791
#define ID_POPUP_VIEWMODE_LEFTVIEW      32792
#define ID_POPUP_VIEWMODE_RIGHTVIEW     32793
#define ID_POPUP_MOVEMODE_WALKTHRUMOVEMENT 32794
#define ID_POPUP_MOVEMODE_ORBITMOVEMENT 32795
#define ID_POPUP_OPTIONS_BACKFACINGPOLIES 32798
#define ID_POPUP_OPTIONS_SHOWWIREFRAME  32799
#define ID_POPUP_OPTIONS_SHOWNORMALS    32800
#define ID_POPUP_OPTIONS_SHOWOBJECTS    32801
#define ID_POPUP_FUNCTIONS_REMOVEEXTRAEDGES 32802
#define ID_POPUP_FUNCTIONS_RESETALLTEXTURECOORDINATES 32803
#define ID_POPUP_FUNCTIONS_RESETALLTEXTURES 32804
#define ID_POPUP_FUNCTIONS_JOINTAGGEDVERTICES 32805
#define ID_POPUP_PROCESSWORLD           32806
#define ID_POPUP_COMPRESSPROJECTFILE    32807
#define ID_POPUP_IMPORTSOUNDS           32808
#define ID_POPUP_IMPORTMODELS           32809
#define ID_POPUP_CREATENEWSPRITE        32810
#define ID_POPUP_FUNCTIONS_CLEANUPGEOMETRY 32812
#define ID_VIEW_COLORSELECTION          32813
#define ID_POPUP_OPTIONS_SHOWEDITGRID   32814
#define ID_POPUP_EXPORTQUAKEMAP         32815
#define ID_POPUP_VIEWMODE_4VIEWCONFIGURATION 32816
#define ID_POPUP_IMPORTCODEFILES        32817
#define ID_POPUP_IMPORTBINARYFILES      32818
#define ID_POPUP_COMPILEALL             32819
#define ID_POPUP_UPDATE                 32820
#define ID_POPUP_COMPILE                32821
#define ID_POPUP_NEWCLASS               32822
#define ID_POPUP_SELECTWORLDCLASS       32823
#define ID_POPUP_FLOATNODEVIEW          32825
#define ID_NODEVIEW_SELECTMODE          32827
#define ID_NODEVIEW_MOVEMODE            32829
#define ID_ATTACH_MODE                  32830
#define NODEVIEW_ATTACHMODE             32831
#define ID_BRUSH_EDITMODE               32832
#define ID_GEOMETRY_EDITMODE            32836
#define ID_OBJECT_EDITMODE              32837
#define ID_ADD_NULL_NODE                32838
#define ID_HOLLOW_BRUSH                 32840
#define ID_SHRINK_GRID_SPACING          32841
#define ID_EXPAND_GRID_SPACING          32842
#define ID_APPLY_COLOR                  32845
#define ID_APPLY_TEXTURE                32846
#define ID_SINGLE_NODE_SELECTION        32848
#define ID_MULTI_NODE_SELECTION         32849
#define ID_POPUP_IMPORTPCX              32850
#define ID_EDIT_STAMP                   32854
#define ID_POPUP_FUNCTIONS_RANDOMIZETEXTURES 32857
#define ID_POPUP_FUNCTIONS_UPDATEPLANES 32858
#define ID_FILE_CREATEREZFILE           32859
#define ID_CENTERONSELECTION            32861
#define ID_POPUP_FUNCTIONS_FINDCONCAVEBRUSHES 32862
#define IDW_NODEVIEW_TOOLBAR            32865
#define IDW_WORLDEDIT_TOOLBAR           32866
#define ID_VIEW_TOOLTIPS                32867
#define ID_RESTREECTRL_ADDDIR           32869
#define ID_RESTREECTRL_DELDIR           32870
#define ID_POPUP_FUNCTIONS_MAPTEXTURECOORDS 32871
#define ID_FILE_RELOADPALETTEDAT        32872
#define ID_OBJECT_HEIGHT                32873
#define ID_POPUP_FUNCTIONS_ROTATESELECTION 32876
#define ID_IMPORT_TERRAIN_MAP           32877
#define ID_HIDE_NODE                    32878
#define ID_HIDE_CHILD_NODE              32879
#define ID_UNDO_PREFERENCES             32882
#define ID_SELECTION_GROUPING           32883
#define ID_FILE_NEWPROJECT              32884
#define ID_FILE_CLOSEPROJECT            32885
#define ID_FILE_NEWWORLD                32886
#define ID_FILE_CLOSEWORLD              32887
#define ID_HELP_WWWDE                   32888
#define ID_ADVANCESELECT                32889
#define ID_MENUITEM32897                32897
#define ID_EDIT_OPTIONS                 32898
#define ID_DELETE_WORLD                 32899
#define ID_WORLD_OPEN                   32900
#define ID_WORLD_DELETE                 32901
#define ID_WORLD_ADDDIR                 32903
#define ID_VIEW_DEBUGWINDOW             32904
#define ID_USEDIRECT3D                  32905
#define ID_USEDEVICE1                   32906
#define ID_USEDEVICE2                   32907
#define ID_USEDEVICE3                   32908
#define ID_USEDEVICE4                   32909
#define ID_RENDERMODE1                  32910
#define ID_RENDERMODE2                  32911
#define ID_RENDERMODE3                  32912
#define ID_RENDERMODE4                  32913
#define ID_POPUP_EXPORTPCX              32915
#define ID_POPUP_IMPORTMIPS             32917
#define ID_POPUP_IMPORTMIPPCX           32918
#define ID_MENUITEM32919                32919
#define ID_POPUP_TEXTUREPROP            32920
#define ID_EDIT_PALETTE                 32921
#define ID_POPUP_OPTIONS_SHOWMARKER     32922
#define ID_SHOW_WORLD_TEXTURES          32923
#define ID_QUICKHELP                    32924
#define ID_KEYMAP                       32925
#define ID_RUN_WORLD                    32926
#define ID_ADDPRIM_BOX                  32927
#define ID_ADDPRIM_CYLINDER             32928
#define ID_HELP_ONLINEDOCUMENTATION     32929
#define ID_FILE_SAVEWORLDAS             32930
#define ID_UNHIDEALL_NODES              32931
#define ID_POPUP_VIEWALLTEXTURES        32932
#define ID_POPUP_BINDTOOBJECT           32933
#define ID_WINDOW_NEXT                  32934
#define ID_WINDOW_PREVIOUS              32935
#define ID_WINDOW_TILEHORIZONTALLY      32937
#define ID_WINDOW_TILEVERTICALLY        32938
#define ID_POPUP_REPLACEALLTEXTURES     32941
#define ID_EDIT_SURFACE_FLAGS           32942
#define ID_ADDPRIM_PYRAMID              32943
#define ID_POPUP_SELECTTEXTURE          32944
#define ID_STICKTEXTURE                 -32591
#define ID_EDIT_SURFACE_COLOR           32946
#define ID_POPUP_SETPATH                32949
#define ID_POPUP_UNSETPATH              32950
#define ID_POPUP_IMPORTALPHAMASK        32951
#define ID_POPUP_CREATEALPHAFROMCOLOR   32952
#define ID_POPUP_CREATESOLIDALPHA       32953
#define ID_RESET_DETAIL_LEVELS          32956
#define ID_SELECT_TAB_WORLDSVIEW        33001
#define ID_SELECT_TAB_TEXTUREVIEW       33002
#define ID_SELECT_TAB_NODESVIEW         33003
#define ID_SELECT_TAB_PROPERTIESVIEW    33004
#define ID_SELECT_TAB_MODELVIEW         33005
#define ID_SELECT_TAB_SOUNDVIEW         33006
#define ID_SELECT_TAB_SPRITEVIEW        33007
#define ID_SELECT_TAB_CLASSVIEW         33008
#define ID_SELECT_TAB_PHYSICSVIEW       33009
#define ID_SELECT_TAB_PREFABVIEW        33010
#define ID_POPUP_EXPORTDTX8_24          40002
#define ID_POPUP_EXPORTDTX_ALL_AS_BPP32P 40003
#define ID_BRUSH_FLIP                   40004
#define ID_SHOW_WORLD_CLASSES           40005
#define ID_EDIT_KEY_CONFIGURATION       40006
#define ID_SCALE_SELECTED               40009
#define ID_TOGGLE_EDIT_MODE             40010
#define ID_SELECTION_SCALE              40010
#define ID_POPUP_HIDEALLNODES           40011
#define ID_POPUP_BATCHRELOAD            40011
#define ID_EDIT_PASTE_ALTERNATE         40013
#define ID_POPUP_SETACTIVEPARENT        40014
#define ID_POPUP_SCALETEXTURECOORDS     40014
#define ID_NAVIGATOR_STORE              40015
#define ID_POPUP_FINDTEXINWORLD         40015
#define ID_NAVIGATOR_GOTONEXT           40016
#define ID_NAVIGATOR_GOTOPREVIOUS       40017
#define ID_NAVIGATOR_ORGANIZE           40018
#define ID_POPUP_RENAME                 40019
#define ID_HELP_CREATION_GUIDE          40019
#define ID_SELECTION_SELECTALL          40020
#define ID_WORLD_COMPRESS               40020
#define ID_SELECTION_SELECTNONE         40021
#define ID_WORLD_DECOMPRESS             40021
#define ID_SELECTION_SELECTINVERSE      40022
#define ID_SELECTION_ADVANCED           40023
#define ID_SELECTION_HIDESELECTED       40024
#define ID_SELECTION_UNHIDESELECTED     40025
#define ID_POPUP_SHADEMODE_PHYSICSPOLIES 40026
#define ID_SELECTION_GROUP              40027
#define ID_UNHIDE_NODE_AND_CHILDREN     40029
#define ID_IMPORT_CUBEMAP               40029
#define ID_HIDE_NODE_AND_CHILDREN       40030
#define ID_VIEW_MAXIMIZEVIEW1           40030
#define ID_WORLD_IMPORT_OBJECTS         40031
#define ID_POPUP_MOVE_TAGGED_NODES      40032
#define ID_VIEW_MAXIMIZEVIEW2           40032
#define ID_VIEW_MAXIMIZEVIEW3           40033
#define ID_VIEW_MAXIMIZEVIEW4           40034
#define ID_VIEW_MAXIMIZEACTIVEVIEW      40035
#define ID_PHYSICS_NEWMATERIAL          40036
#define ID_MAP_TEXTURE_TO_VIEW          40038
#define ID_BRUSH_SPLITBRUSH             40039
#define ID_PHYSICS_DELETEMATERIAL       40039
#define ID_PHYSICS_MATERIALPROPERTIES   40040
#define ID_BRUSH_CARVE                  40041
#define ID_PHYSICS_DELETE               40041
#define ID_PHYSICS_ADDDIRECTORY         40042
#define ID_APPLY_PHYSICSMATERIAL        40045
#define ID_SELECTION_FREEZE_SELECTED    40047
#define ID_POPUP_REFRESH                40048
#define ID_SELECTION_UNFREEZE_ALL       40048
#define ID_VIEW_DISPLAY_ALL_MODELS      40049
#define ID_ADDPRIM_SPHERE               40050
#define ID_ADDPRIM_DOME                 40051
#define ID_SELECTION_CONTAINER          40052
#define IDC_VIEW_HIDE_ALL_MODELS        40053
#define ID_VIEW_DISPLAY_SELECTED_MODELS 40054
#define ID_VIEW_HIDE_SELECTED_MODELS    40055
#define ID_VIEW_DISPLAY_MODELS_OF_CLASS 40056
#define ID_VIEW_HIDE_MODELS_OF_CLASS    40057
#define ID_VIEW_HIDE_ALL_MODELS         40058
#define ID_CENTER_MARKER_ON_SELECTION   40059
#define ID_POPUP_DISCONNECT_PREFAB      40060
#define ID_POPUP_SHOWTHUMBNAILS         40061
#define ID_PLACE_MARKER_AT_CAMERA       40062
#define ID_SELECTION_GENERATE_UNIQUE_NAMES 40063
#define ID_WORLD_OBJECT_BROWSER         40064
#define ID_WORLD_DEBUG_LOADLEAKFILE     40065
#define ID_WORLD_DEBUG_CLEARLEAKFINDER  40066
#define ID_ADD_PATCH                    40067
#define ID_PATCH_EDITMODE               40068
#define ID_WORLD_DEBUG_FIND_NAMING_CONFLICTS 40069
#define ID_IMPORT_TGA_FILES             40070
#define ID_SET_PATCH_RESOLUTION         40070
#define ID_IMPORT_8BIT_ALPHA            40071
#define ID_HELP_INTRODUCTION            40071
#define ID_SELECTION_MIRROR_X           40072
#define ID_SELECTION_MIRROR_Y           40073
#define ID_SELECTION_MIRROR_Z           40074
#define ID_SELECTION_HIDEINVERSE        40075
#define ID_SELECTION_UNHIDEINVERSE      40076
#define ID_POPUP_COLLAPSE_CHILDREN      40077
#define ID_VIEW_TOGGLE_FLOATING_TOOLBARS 40078
#define ID_FILE_IMPORT_WORLD            40079
#define ID_SELECTION_SAVEPREFAB         40080
#define ID_PREFAB_OPEN                  40081
#define ID_WORLD_DEBUG_GOTO_NEXT_LEAK_VERTICE 40082
#define ID_WORLD_DEBUG_GOTO_PREVIOUS_LEAK_VERTICE 40083
#define ID_WORLD_SPECIAL_ALIGNPOLYTEXTURES 40084
#define ID_LOAD_LIGHT_DATA              40085
#define ID_UNLOAD_LIGHT_DATA            40086
#define ID_POPUP_TEXTUREPALETTE_REMOVE  40087
#define ID_CENTER_ON_MARKER             40088
#define ID_POPUP_SHADEMODE_LIGHTMAPSONLY 40089
#define ID_WORLD_SCALE_GEOMETRY         40090
#define ID_POPUP_FRAMELIST_ZOOM_50      40091
#define ID_POPUP_FRAMELIST_ZOOM_100     40092
#define ID_POPUP_FRAMELIST_ZOOM_200     40093
#define ID_POPUP_FRAMELIST_ZOOM_400     40094
#define ID_POPUP_TEXTUREPALETTE_LOAD    40095
#define ID_POPUP_TEXTUREPALETTE_VIEWALL 40096
#define ID_POPUP_TEXTUREPALETTE_SAVE    40097
#define ID_POPUP_ADDTOPALETTE           40098
#define ID_POPUP_TEXTUREPALETTE_NEW     40099
#define ID_POPUP_TEXTUREPALETTE_DELETE  40100
#define ID_POPUP_TEXTUREPALETTE_IMPORT  40101
#define ID_POPUP_TEXTUREPALETTE_SORT    40102
#define ID_PLACE_MARKER_AT_VECTOR       40103
#define ID_FIT_TEXTURE_TO_POLY          40104
#define ID_TOGGLE_CLASS_ICONS           40105
#define ID_VIEW_TEXTUREPALETTE          40106
#define ID_VIEW_LEVEL_ERROR             40107
#define ID_VIEW_DISPLAY_POLYCOUNTS      40108
#define ID_VIEW_DISPLAY_POLYCOUNT       40109
#define ID_VIEW_DISPLAY_MODEL_POLYCOUNT 40110
#define ID_EDIT_SURFACE_KEY             40111
#define ID_EDIT_SURFACE_UNIQUE          40112
#define ID_CONVERT_TO_32P               40113
#define ID_SELECTBRUSHCOLOR             40114
#define ID_HIDE_FROZEN_NODES            40115
#define ID_SET_CAMERA_FOV               40116
#define ID_CAMERA_TO_OBJECT             40117
#define ID_SHOW_DYNAMIC_LIGHTING        40118
#define ID_RENAME_RESOURCES             40119
#define ID_POPUP_TEXTUREPALETTE_RENAMETEX 40120
#define ID_UPDATE_WORLD_OBJECTS         40121
#define ID_REPLACE_TEXTURES_IN_SEL      40122
#define ID_REPLACE_SELECTED_PREFABS     40123
#define ID_RENAME_TEXTURE               40124
#define ID_RENAME_PREFAB                40125
#define ID_DETACH_SELECTED_PREFABS      40126
#define ID_DISCONNECT_SELECTED_PREFABS  40127
#define ID_WORLD_SPECIAL_UPDATE_PROPS   40129
#define ID_EVENTEDITOR_ADD              40130
#define ID_EVENTEDITOR_DELETE           40131
#define ID_EVENTEDITOR_DELETEALL        40132
#define ID_EVENTEDITOR_DELETETRACK      40133
#define ID_EVENTEDITOR_COPY             40134
#define ID_EVENTEDITOR_PASTE            40135
#define ID_EVENTEDITOR_CUT              40136
#define ID_WORLDLIST_RUN                40137
#define ID_IMPORT_BUMPMAP               40138
#define ID_TEXTURE_PASS1                40139
#define ID_TEXTURE_PASS2                40140
#define ID_REMOVE_TEXTURE               40141
#define ID_IMPORT_NORMALMAP             40142
#define ID_PREFAB_TRACKER               40143
#define ID_VIEW_LEVEL_TEXTURES          40144
#define ID_SEARCH_REPLACE_IN_TEXTURES   40145
#define ID_VIEW_OBJECT_SEARCH           40146
#define ID_FILE_RELOADWORLD             40147
#define ID_WORLD_SPECIAL_IGNORE_PREFABPROPS 40149
#define ID_SNAP_VERTICES                40150
#define ID_WORLD_SPECIAL_IGNORE_MSGS_IN_PREFABS 40151
#define ID_TEXTURE_TRACKER              40153
#define ID_VIEW_LEVEL_ITEMS             40154
#define ID_POPUP_MAKETEXTUREWRITABLE    40155
#define ID_OBJECT_TRACKER               40156
#define ID_ADDPRIM_PLANE                40157
#define ID_CENTER_SELECTION_ON_MARKER   40158
#define ID_SELECT_PREFAB                40159
#define ID_OBJECT_SEL_FILTER            40160
#define ID_BRUSH_UNSUPPORTED            40161
#define ID_RESET_TEXTURE_COORDS         41000
#define IDS_MUSTHAVEONEWORLDSDIRECTORY  57666
#define ID_PALETTE_REMOVE               57670
#define IDS_NOWORLDDIRSELECTED          59142
#define ID_INDICATOR_CAMERA             59143
#define ID_INDICATOR_CURSOR             59144
#define ID_INDICATOR_GRID               59145
#define ID_INDICATOR_TEXTURE            59146
#define ID_INDICATOR_BOUNDING_BOX       59147
#define ID_INDICATOR_SELECTION          59148
#define ID_INDICATOR_BRUSHNAME          59149
#define ID_INDICATOR_VIEWTYPE           59150
#define IDS_NODEVIEWTOOLBAR_TEXT        61447
#define IDS_STANDARD_TOOLBAR            61448
#define IDS_NONOBJECT_NODES_SELECTED    61449
#define ID_GOTO_NEXT_SELECTED_NODE      61450
#define IDS_TEXTUREPALETTE_FILE_HEADER  61450
#define IDS_TEXTUREPALETTE_NEW_TITLE    61451
#define IDS_TEXTUREPALETTE_NEW_CAPTION  61452
#define AFX_IDS_DOCK                    61458
#define IDS_KEYCONFIG_EXTENSION         61889
#define IDS_KEYCONFIG_FILTER            61890
#define IDS_KEYCONFIG_DESCRIPTION       61891
#define IDS_KEYCONFIG_KEY               61892
#define IDS_KEYCONFIG_COMMAND           61893
#define IDS_UIE_TRACKER_FOCUS           61894
#define IDS_UIE_SELECT_DEPTH            61895
#define IDS_UIE_APPLY_TEXTURE_CLICK     61896
#define IDS_UIE_TEST_RENDER_SPEED       61897
#define IDS_UIE_SPLIT_BRUSH             61898
#define IDS_UIE_CARVE_BRUSH             61899
#define IDS_UIE_SELECT_NONE             61900
#define IDS_UIE_SET_GRID_FORWARD        61901
#define IDS_UIE_SET_GRID_RIGHT          61902
#define IDS_UIE_SET_GRID_UP             61903
#define IDS_UIE_INIT_TEXTURE_SPACE      61904
#define IDS_UIE_DELETE                  61905
#define IDS_UIE_NUDGE_UP                61906
#define IDS_UIE_NUDGE_DOWN              61907
#define IDS_UIE_NUDGE_LEFT              61908
#define IDS_UIE_NUDGE_RIGHT             61909
#define IDS_UIE_REMOVE_EDGES            61910
#define IDS_UIE_DELETE_EDGES            61911
#define IDS_UIE_SPLIT_EDGE              61912
#define IDS_UIE_DELETE_TAGGED_POLIES    61913
#define IDS_UIE_GRID_TO_POLY            61914
#define IDS_UIE_TAG_POLY_VERTS          61915
#define IDS_UIE_FLIP_NORMAL             61916
#define IDS_UIE_ORBIT_VERTEX            61917
#define IDS_UIE_NODE_ROTATE             61921
#define IDS_UIE_TEXTURE_MOVE            61922
#define IDS_UIE_BRUSH_SIZE              61923
#define IDS_UIE_CURVE_EDIT              61924
#define IDS_UIE_FAR_DIST                61925
#define IDS_UIE_GRID_SIZE               61926
#define IDS_UIE_MARKER_MOVE             61927
#define IDS_UIE_MOVE_VERT               61928
#define IDS_UIE_MOVE_SEL_VERT           61929
#define IDS_UIE_MOVE_IMM_VERT           61930
#define IDS_UIE_SCALE_POLY              61931
#define IDS_UIE_MOVE_NODE_HANDLE        61932
#define IDS_UIE_SNAP_NODE               61933
#define IDS_UIE_MOVE_NODE_PERP          61934
#define IDS_UIE_NAV_MOVE                61935
#define IDS_UIE_NAV_ROTATE              61936
#define IDS_UIE_DRAW_POLY               61937
#define IDS_UIE_TAG_ALL                 61938
#define IDS_UIE_TAG_BRUSH               61939
#define IDS_ERROR_SAVING_BACKUP         61940
#define IDS_UIE_VERT_SNAP_EDGE_SEL      61941
#define IDS_UIE_VERT_SNAP_EDGE          61942
#define IDS_UIE_VERT_SNAP_VERT_SEL      61943
#define IDS_UIE_VERT_SNAP_VERT          61944
#define IDS_UIE_UNJOIN_BRUSHES          61945
#define IDS_UIE_JOIN_BRUSHES            61946
#define IDS_UIE_TRI_BRUSHES             61947
#define IDS_UIE_OBJECT_SIZE             61970
#define AFX_IDP_NO_CREATION_GUIDE       61971
#define AFX_IDP_NO_PDF_READER           61972
#define AFX_IDP_GENERIC_CREATION_GUIDE_FALURE 61973
#define IDS_PROJ_BAR_FLOAT              61974
#define IDS_PROJ_BAR_ALLOW_DOCKING      61975
#define IDS_PROJ_BAR_HIDE               61976
#define IDS_UIE_MAXIMIZE_VIEW1          61977
#define IDS_UIE_MAXIMIZE_VIEW2          61978
#define IDS_UIE_MAXIMIZE_VIEW3          61979
#define IDS_UIE_MAXIMIZE_VIEW4          61980
#define IDS_UIE_MAXIMIZE_ACTIVE_VIEW    61981
#define IDS_UIE_RESET_VIEWPORTS         61982
#define IDS_UIE_FREEZE_SELECTED         61983
#define IDS_UIE_UNFREEZE_ALL            61984
#define IDS_UIE_EDIT_UNDO               61985
#define IDS_UIE_EDIT_REDO               61986
#define IDS_UIE_SHRINK_GRID_SPACING     61987
#define IDS_UIE_EXPAND_GRID_SPACING     61988
#define IDS_UIE_APPLY_COLOR             61989
#define IDS_UIE_APPLY_PHYSICS_MAT       61990
#define IDS_UIE_MAP_TEXTURE_COORDS      61991
#define IDS_UIE_SHADE_PHYSICS           61992
#define IDS_UIE_SHADE_WIREFRAME         61993
#define IDS_UIE_SHADE_TEXTURES          61994
#define IDS_UIE_SHADE_FLAT              61995
#define IDS_UIE_SHADE_LIGHTMAPS         61996
#define IDS_UIE_MOVE_WALKTHROUGH        61997
#define IDS_UIE_MOVE_ORBIT              61998
#define IDS_UIE_SELECT_TEXTURE          61999
#define IDS_UIE_SURFACE_COLOR           62000
#define IDS_UIE_HIDE_INVERSE            62001
#define IDS_UIE_HIDE_SELECTED           62002
#define IDS_UIE_UNHIDE_SELECTED         62003
#define IDS_UIE_UNHIDE_INVERSE          62004
#define IDS_UIE_ROTATE_SELECTION        62005
#define IDS_UIE_BIND_TO_OBJECT          62006
#define IDS_UIE_SHOW_SELECTED_MODELS    62007
#define IDS_UIE_HIDE_SELECTED_MODELS    62008
#define IDS_UIE_SHOW_MODELS_OF_CLASS    62009
#define IDS_UIE_HIDE_MODELS_OF_CLASS    62010
#define IDS_UIE_SHOW_ALL_MODELS         62011
#define IDS_UIE_HIDE_ALL_MODELS         62012
#define IDS_UIE_ZOOM                    62013
#define IDS_UIE_NAV_ROTATE_FORWARD      62014
#define IDS_UIE_NAV_ROTATE_BACKWARD     62015
#define IDS_UIE_NAV_MOVE_PERP           62016
#define IDS_UIE_NAV_MOVE_FAST           62017
#define IDS_UIE_ZOOM_FAST               62018
#define IDS_UIE_NAV_DRAG                62019
#define IDS_UIE_NAV_DRAG_FAST           62020
#define IDS_UIE_NAV_ARC_ROTATE          62021
#define IDS_UIE_NAV_ARC_ROTATE_ROLL     62022
#define IDS_PROJ_BAR_HIDE_CURRENT       62023
#define IDS_PROJ_BAR_UNHIDE_ALL         62024
#define IDS_DEFAULT_STYLE_DESCRIPTION   62025
#define IDS_MAX_STYLE_DESCRIPTION       62026
#define IDS_APPLY_STYLE_FAILED          62027
#define IDS_APPLY_STYLE_WARNING_TITLE   62028
#define IDS_APPLY_STYLE_WARNING         62029
#define IDS_MAYA_STYLE_DESCRIPTION      62030
#define IDS_DEDIT_STYLE_DESCRIPTION     62031
#define IDS_UIE_TEXTURE_MOVE_ROTATE     62032
#define IDS_UIE_TEXTURE_MOVE_SCALE      62033
#define IDS_UIE_TEXTURE_MOVE_STEP       62034
#define IDS_UIE_DRAW_POLY_UNDO          62035
#define IDS_UIE_DRAW_POLY_NEW_VERTEX    62036
#define IDS_UIE_DRAW_POLY_ROTATE        62037
#define IDS_UIE_DRAW_POLY_SPLIT         62038
#define IDS_UIE_LOCK_FOCUS              62039
#define IDS_UIE_SCALE_POLY_EXTRUDE      62040
#define IDS_UIE_NAV_ORBIT               62041
#define IDS_UIE_NAV_ORBIT_MOVE          62042
#define IDS_UIE_NODE_MOVE_LOCK_AXIS     62043
#define IDS_UIE_NODE_MOVE_CLONE         62044
#define IDS_UIE_BRUSH_EDIT_MODE         62045
#define IDS_UIE_OBJECT_EDIT_MODE        62046
#define IDS_UIE_GEOMETRY_EDIT_MODE      62047
#define IDS_UIE_PATCH_EDIT_MODE         62048
#define IDS_UIE_ADD_OBJECT              62049
#define IDS_UIE_ADD_PATCH               62050
#define IDS_UIE_NODE_ROTATE_STEP        62051
#define IDS_UIE_TAG_ADD                 62052
#define IDS_UIE_TAG_INVERT              62053
#define IDS_UIE_MOVE_VERT_SNAP          62054
#define IDS_UIE_MOVE_VERT_PERP          62055
#define IDS_PROJ_BAR_SHOW_ICONS         62056
#define IDS_UIE_MIRROR_X                62057
#define IDS_UIE_MIRROR_Y                62058
#define IDS_UIE_MIRROR_Z                62059
#define IDS_UIE_SELECT_ALL              62060
#define IDS_UIE_SELECT_INVERSE          62061
#define IDS_UIE_SELECT_CONTAINER        62062
#define IDS_UIE_ADVANCED_SELECT         62063
#define IDS_UIE_SCALE_SELECTION         62064
#define IDS_UIE_SAVE_AS_PREFAB          62065
#define IDS_UIE_GENERATE_UNIQUE_NAMES   62066
#define IDS_UIE_GROUP_SELECTION         62067
#define IDS_UIE_FLIP_BRUSH              62068
#define IDS_UIE_EXTRUDE_POLY            62069
#define IDS_UIE_EXTRUDE_POLY_BRUSH      62070
#define IDS_UIE_SCALE_POLY_DIVIDE       62071
#define IDS_UIE_SET_PATCH_RESOLUTION    62072
#define IDS_UIE_MAP_TEXTURE_TO_VIEW     62073
#define IDS_UIE_RESET_TEXTURE_COORDS    62074
#define IDS_UIE_REPLACE_TEXTURES        62075
#define IDS_UIE_TEXTURE_WRAP            62076
#define AFX_IDP_NO_HTML_READER          62077
#define AFX_IDP_NO_INTRODUCTION         62078
#define AFX_IDP_GENERIC_INTRODUCTION_FALURE 62079
#define AFX_IDP_REGISTRY_ERROR          62080
#define IDS_UIE_CREATE_DOME             62081
#define IDS_UIE_CREATE_SPHERE           62082
#define IDS_UIE_CREATE_PYRAMID          62083
#define IDS_UIE_CREATE_CYLINDER         62084
#define IDS_UIE_CREATE_BOX              62085
#define IDS_UIE_TOP_VIEW                62086
#define IDS_UIE_BOTTOM_VIEW             62087
#define IDS_UIE_LEFT_VIEW               62088
#define IDS_UIE_RIGHT_VIEW              62089
#define IDS_UIE_FRONT_VIEW              62090
#define IDS_UIE_BACK_VIEW               62091
#define IDS_UIE_PERSPECTIVE_VIEW        62092
#define IDS_UIE_EDIT_SURFACE_FLAGS      62093
#define IDS_UIE_EDIT_SURFACE_COLOR      62094
#define IDS_UIE_TEXTURE_WRAP_SKIP       62095
#define IDS_UIE_NAVIGATOR_STORE         62096
#define IDS_UIE_NAVIGATOR_ORGANIZE      62097
#define IDS_UIE_NAVIGATOR_NEXT          62098
#define IDS_UIE_NAVIGATOR_PREVIOUS      62099
#define IDS_UIE_FIT_TEXTURE_TO_POLY     62100
#define IDS_UIE_TOGGLE_CLASS_ICONS      62101
#define IDS_UIE_SHOW_MODEL_POLYCOUNT    62102
#define IDS_UIE_SCALE_VERT_SEL          62103
#define IDS_UIE_SCALE_VERT_IMM          62104
#define IDS_UIE_EDIT_SURFACE_KEY        62105
#define IDS_SURFACEKEY                  62106
#define IDS_ENTERSURFACEKEY             62107
#define IDS_UIE_SELECT_BRUSH_COLOR      62108
#define IDS_UIE_HIDE_FROZEN_NODES       62109
#define IDS_UIE_CAMERA_TO_OBJECT        62110
#define IDS_LOAD_PRE_WORLD_CORRECT_LIGHTING 62111
#define IDS_LOAD_PRE_WORLD_CORRECT_LIGHTING_TITLE 62112
#define IDS_UIE_DISPLAY_DYN_LIGHTING    62113
#define IDS_UIE_ROTATE_SELECTION_LEFT   62114
#define IDS_UIE_ROTATE_SELECTION_RIGHT  62115
#define IDS_UIE_MARKER_CENTER           62116
#define IDS_UIE_DRAW_POLY_INSERT_EDGE   62117
#define IDS_UIE_MIRROR_TEXTURE_X        62118
#define IDS_UIE_MIRROR_TEXTURE_Y        62119
#define IDS_UIE_MATCH_TEXTURE_COORDS    62120
#define IDS_UIE_DRAW_POLY_VERT_SNAP     62121
#define IDS_UIE_DRAW_POLY_CLOSE         62122
#define IDS_UIE_REPLACE_TEXTURES_IN_SEL 62123
#define IDS_RENAME_RESOURCE_FILTER      62124
#define IDS_UIE_DISCONNECT_SELECTED_PREFABS 62125
#define IDS_TT_EVENT_LIST               62126
#define IDS_TT_EVENT_TIME               62127
#define IDS_TT_EVENT_RULER              62128
#define IDS_TT_EVENT_MESSAGE            62129
#define IDS_TT_EVENT_IMM_MESSAGE        62130
#define IDS_TT_EVENT_SCALE              62131
#define IDS_TT_EVENT_LENGTH             62132
#define IDS_UIE_EXTRUDE_POLY_SNAP       62133
#define IDS_UIE_APPLY_TEXTURE_TO_SEL    62134
#define IDS_COMPRESSEDWORLDEXTENSION    62135
#define IDS_SAVETOREADONLYFILE          62136
#define IDS_UIE_NEXT_TEXTURE_LAYER      62137
#define IDS_UIE_REMOVE_TEXTURE          62138
#define IDS_UIE_CREATE_PLANE            62139
#define IDS_UIE_CENTER_SEL_ON_MARKER    62140
#define IDS_UIE_SELECT_PREFAB           62141
#define IDS_OBJSEL_ADDPRESETTITLE       62142
#define IDS_OBJSEL_ADDPRESETTEXT        62143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         40164
#define _APS_NEXT_CONTROL_VALUE         1304
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
