// ----------------------------------------------------------------------- //
//
// MODULE  :	LightSpot.h
//
// PURPOSE :	Provides the definition for the spot projector light class 
//				which represents a light generated by emitting a texture
//				forward in a truncated frustum
//
// CREATED :	2/21/03
//
// (c) 2003 Monolith Productions, Inc.  All Rights Reserved
// ----------------------------------------------------------------------- //

#ifndef __LIGHTSPOT_H__
#define __LIGHTSPOT_H__

#include "LightBase.h"
#include "SharedFXStructs.h"

LINKTO_MODULE( LightSpot );

class LightSpot :
	public LightBase
{
public:

	LightSpot();
	~LightSpot();
	
private:

	//virtual function that derived classes must override to handle loading in of
	//property data
	virtual void	ReadLightProperties(const GenericPropList *pProps);
	
	virtual uint32	OnObjectCreated(const GenericPropList* pProps, float fCreationReason);
};

class LightSpot_Plugin: 
	public LightBase_Plugin
{
public:

	virtual LTRESULT PreHook_EditStringList(
		const char* szRezPath,				
		const char* szPropName,				
		char** aszStrings,					
		uint32* pcStrings,	
		const uint32 cMaxStrings,		
		const uint32 cMaxStringLength)		
	{
		//handle setting up any LOD properties on the light
		if(	LTStrEquals(szPropName, "VolumetricLOD") )
		{
			return CEngineLODPropUtil::AddLODStrings(aszStrings, pcStrings, cMaxStrings, cMaxStringLength);
		}
		return LightBase_Plugin::PreHook_EditStringList(szRezPath, szPropName, aszStrings, pcStrings, cMaxStrings, cMaxStringLength);
	}
};


#endif
