#ifndef __CHEATDEFS_H
#define __CHEATDEFS_H

enum CheatCode
{
	CHEAT_NONE = -1,
	CHEAT_GOD,
	CHEAT_AMMO,
	CHEAT_ARMOR,
	CHEAT_HEALTH,
	CHEAT_CLIP,
	CHEAT_TELEPORT,
	CHEAT_POS,
	CHEAT_KFA,
	CHEAT_FULL_WEAPONS,
	CHEAT_POSWEAPON,
	CHEAT_POSWEAPON_MUZZLE,
	CHEAT_CAMERAOFFSET,
	CHEAT_LIGHTSCALE,
	CHEAT_LIGHTADD,
	CHEAT_FOV,
	CHEAT_INTERFACEADJUST,
	CHEAT_TEARS,
	CHEAT_REMOVEAI,
	CHEAT_TRIGGERBOX,
	CHEAT_POSBREACH,
	CHEAT_POS1STCAM,
	CHEAT_MOTORCYCLE,
	CHEAT_SNOWMOBILE,
	CHEAT_MODSQUAD,
	CHEAT_FULL_GEAR,
	CHEAT_CHASETOGGLE,
	CHEAT_ALL_MISSIONS,
	CHEAT_RESET_HISTORY,
	CHEAT_CAM_POSROT,
	CHEAT_MISSION_INVENTORY,
	CHEAT_EXITLEVEL,
	CHEAT_VERSION,
	CHEAT_MIKED,
	CHEAT_BIGBLOOD,
	CHEAT_MAX
};

#endif
