//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ServerRes.rc
//
#define IDS_DUMMYSTRING                 0

#define IDS_MODEL_FIRSTAID_10           1
#define IDS_SKIN_FIRSTAID_10			2
#define IDS_SOUND_FIRSTAID_10			3
#define IDS_MODEL_FIRSTAID_15           4
#define IDS_SKIN_FIRSTAID_15			5	
#define IDS_SOUND_FIRSTAID_15			6
#define IDS_MODEL_FIRSTAID_25           7
#define IDS_SKIN_FIRSTAID_25			8
#define IDS_SOUND_FIRSTAID_25			9
#define IDS_MODEL_FIRSTAID_50           10
#define IDS_SKIN_FIRSTAID_50			11
#define IDS_SOUND_FIRSTAID_50			12

#define IDS_MODEL_POWERSURGE_50			20
#define IDS_SKIN_POWERSURGE_50			21
#define IDS_SOUND_POWERSURGE_50			22
#define IDS_MODEL_POWERSURGE_100		23	
#define IDS_SKIN_POWERSURGE_100			24
#define IDS_SOUND_POWERSURGE_100		25
#define IDS_MODEL_POWERSURGE_150		26
#define IDS_SKIN_POWERSURGE_150			27
#define IDS_SOUND_POWERSURGE_150		28
#define IDS_MODEL_POWERSURGE_250		29
#define IDS_SKIN_POWERSURGE_250			30
#define IDS_SOUND_POWERSURGE_250		31

#define IDS_MODEL_BODYARMOR_50			40
#define IDS_SKIN_BODYARMOR_50			41
#define IDS_SOUND_BODYARMOR_50			42
#define IDS_MODEL_BODYARMOR_100			43
#define IDS_SKIN_BODYARMOR_100			44
#define IDS_SOUND_BODYARMOR_100			45
#define IDS_MODEL_BODYARMOR_200			46
#define IDS_SKIN_BODYARMOR_200			47
#define IDS_SOUND_BODYARMOR_200			48

#define IDS_MODEL_ARMORREPAIR_100		60
#define IDS_SKIN_ARMORREPAIR_100		61
#define IDS_SOUND_ARMORREPAIR_100		62
#define IDS_MODEL_ARMORREPAIR_250		63
#define IDS_SKIN_ARMORREPAIR_250		64
#define IDS_SOUND_ARMORREPAIR_250		65
#define IDS_MODEL_ARMORREPAIR_500		66
#define IDS_SKIN_ARMORREPAIR_500		67
#define IDS_SOUND_ARMORREPAIR_500		68

// Upgrades...

#define IDS_MODEL_DAMAGEUPGRADE			80
#define IDS_SKIN_DAMAGEUPGRADE			81
#define IDS_SOUND_DAMAGEUPGRADE			82

#define IDS_MODEL_PROTECTIONUPGRADE		90
#define IDS_SKIN_PROTECTIONUPGRADE		91
#define IDS_SOUND_PROTECTIONUPGRADE		92

#define IDS_MODEL_REGENUPGRADE			100
#define IDS_SKIN_REGENUPGRADE			101
#define IDS_SOUND_REGENUPGRADE			102

#define IDS_MODEL_HEALTHUPGRADE			110
#define IDS_SKIN_HEALTHUPGRADE			111
#define IDS_SOUND_HEALTHUPGRADE			112

#define IDS_MODEL_ARMORUPGRADE			120
#define IDS_SKIN_ARMORUPGRADE			121
#define IDS_SOUND_ARMORUPGRADE			122

#define IDS_MODEL_TARGETINGUPGRADE		125
#define IDS_SKIN_TARGETINGUPGRADE		126
#define IDS_SOUND_TARGETINGUPGRADE		127

// Enhancements...

#define IDS_MODEL_DAMAGEENHANCEMENT						130
#define IDS_SKIN_DAMAGEENHANCEMENT						131
#define IDS_SOUND_DAMAGEENHANCEMENT						132

#define IDS_MODEL_MELEEDAMAGEENHANCEMENT				140
#define IDS_SKIN_MELEEDAMAGEENHANCEMENT					141
#define IDS_SOUND_MELEEDAMAGEENHANCEMENT				142

#define IDS_MODEL_PROTECTIONENHANCEMENT					150
#define IDS_SKIN_PROTECTIONENHANCEMENT					151
#define IDS_SOUND_PROTECTIONENHANCEMENT					152

#define IDS_MODEL_ENERGYPROTECTIONENHANCEMENT			160
#define IDS_SKIN_ENERGYPROTECTIONENHANCEMENT			161
#define IDS_SOUND_ENERGYPROTECTIONENHANCEMENT			162

#define IDS_MODEL_PROJECTILEPROTECTIONENHANCEMENT		170
#define IDS_SKIN_PROJECTILEPROTECTIONENHANCEMENT		171
#define IDS_SOUND_PROJECTILEPROTECTIONENHANCEMENT		172

#define IDS_MODEL_EXPLOSIVEPROTECTIONENHANCEMENT		180
#define IDS_SKIN_EXPLOSIVEPROTECTIONENHANCEMENT			181
#define IDS_SOUND_EXPLOSIVEPROTECTIONENHANCEMENT		182

#define IDS_MODEL_REGENENHANCEMENT						190
#define IDS_SKIN_REGENENHANCEMENT						191
#define IDS_SOUND_REGENENHANCEMENT						192

#define IDS_MODEL_HEALTHENHANCEMENT						200
#define IDS_SKIN_HEALTHENHANCEMENT						201
#define IDS_SOUND_HEALTHENHANCEMENT						202

#define IDS_MODEL_ARMORENHANCEMENT						210
#define IDS_SKIN_ARMORENHANCEMENT						211
#define IDS_SOUND_ARMORENHANCEMENT						212

// UltraPowerups...

#define IDS_MODEL_ULTRADAMAGE							220
#define IDS_SKIN_ULTRADAMAGE							221
#define IDS_SOUND_ULTRADAMAGE							222

#define IDS_MODEL_ULTRAPOWERSURGE						230
#define IDS_SKIN_ULTRAPOWERSURGE						231
#define IDS_SOUND_ULTRAPOWERSURGE						232

#define IDS_MODEL_ULTRAHEALTH							240
#define IDS_SKIN_ULTRAHEALTH							241
#define IDS_SOUND_ULTRAHEALTH							242
	
#define IDS_MODEL_ULTRASHIELD							250
#define IDS_SKIN_ULTRASHIELD							251
#define IDS_SOUND_ULTRASHIELD							252

#define IDS_MODEL_ULTRASTEALTH							260
#define IDS_SKIN_ULTRASTEALTH							261
#define IDS_SOUND_ULTRASTEALTH							262

#define IDS_MODEL_ULTRAREFLECT							270
#define IDS_SKIN_ULTRAREFLECT							271
#define IDS_SOUND_ULTRAREFLECT							272

#define IDS_MODEL_ULTRANIGHTVISION						280
#define IDS_SKIN_ULTRANIGHTVISION						281
#define IDS_SOUND_ULTRANIGHTVISION						282

#define IDS_MODEL_ULTRAINFRARED							290
#define IDS_SKIN_ULTRAINFRARED							291
#define IDS_SOUND_ULTRAINFRARED							292

#define IDS_MODEL_ULTRASILENCER							300
#define IDS_SKIN_ULTRASILENCER							301
#define IDS_SOUND_ULTRASILENCER							302

#define IDS_MODEL_ULTRARESTORE							310
#define IDS_SKIN_ULTRARESTORE							311
#define IDS_SOUND_ULTRARESTORE							312

// Special Moves...

#define IDS_MODEL_BEAM									320
#define IDS_SKIN_BEAM									321

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
