//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by C:\Proj\TO2\Source\Game\ClientRes\Shared\Lang\EN\ClientResShared.rc
//
#define IDS_VERSION                     500
#define IDS_TITLE_GAME                  502
#define IDS_TITLE_DIFFICULTY            503
#define IDS_TITLE_OPTIONS               504
#define IDS_TITLE_NEWGAME               505
#define IDS_TITLE_LOADGAME              506
#define IDS_TITLE_SAVEGAME              507
#define IDS_TITLE_CUSTOMLEVELS          508
#define IDS_TITLE_DISPLAYOPTIONS        509
#define IDS_TITLE_TEXTURE               510
#define IDS_TITLE_PERFORMANCE           511
#define IDS_TITLE_SOUND                 512
#define IDS_TITLE_KEYBOARD              513
#define IDS_TITLE_MOUSE                 514
#define IDS_TITLE_JOYSTICK              515
#define IDS_TITLE_BRIEFING              516
#define IDS_TITLE_STATUS                517
#define IDS_NO_DM_MAPS                  517
#define IDS_TITLE_ENDMISSION            518
#define IDS_TITLE_PROFILE               519
#define IDS_TITLE_PLAYER                520
#define IDS_TITLE_CROSSHAIR             521
#define IDS_TITLE_CONTROLS              522
#define IDS_TITLE_CONFIGURE             523
#define IDS_TITLE_MULTI                 524
#define IDS_TITLE_HOST_OPTIONS          525
#define IDS_TITLE_SKILLS                526
#define IDS_TITLE_OBJECTIVES            527
#define IDS_TITLE_GAME_OPTIONS          528
#define IDS_TITLE_INVENTORY             529
#define IDS_TITLE_ADVDISPLAY            530
#define IDS_TITLE_EFFECTS               531
#define IDS_TITLE_JOIN                  532
#define IDS_TITLE_HOST                  533
#define IDS_TITLE_HOST_MISSIONS         534
#define IDS_TITLE_PLAYER_SETUP          535
#define IDS_TITLE_SUMMARY               536
#define IDS_CHAPTERS                    537
#define IDS_TITLE_INTEL                 538
#define IDS_TITLE_HOST_CAMPAIGN         539
#define IDS_TITLE_SYSTEM                540
#define IDS_TITLE_KEYS                  541
#define IDS_SUBROUTINES                 542
#define IDS_HOST_NAME_TDM_DEFAULT       542
#define IDS_MULTIPLAYER_LAN             543
#define IDS_HELP_SUBROUTINES            544
#define IDS_HOST_NAME_DD_DEFAULT        544
#define IDS_HELP_MULTIPLAYER_LAN        545
#define IDS_RATINGS                     546
#define IDS_TITLE_TEAM                  546
#define IDS_HELP_CHAPTERS               547
#define IDS_HELP_RATINGS                548
#define IDS_HELP_TEAM_NAME              548
#define IDS_HELP_CHAPTER_LIST           549
#define IDS_HELP_FAILURE                550
#define IDS_PRESS_ANY_KEY               551
#define IDS_NORMAL                      552
#define IDS_PERFORMANCE_TEST            553
#define IDS_CUSTOM                      554
#define IDS_ON                          555
#define IDS_OFF                         556
#define IDS_YES                         557
#define IDS_NO                          558
#define IDS_NONE                        559
#define IDS_FEW                         560
#define IDS_SOME                        561
#define IDS_LOTS                        562
#define IDS_ALL                         563
#define IDS_CLOSE                       564
#define IDS_SPACER                      565
#define IDS_BACK                        566
#define IDS_CREATE                      567
#define IDS_LOAD                        568
#define IDS_DELETE                      569
#define IDS_OK                          570
#define IDS_CANCEL                      571
#define IDS_ENTER_NAME                  572
#define IDS_CONTINUE                    573
#define IDS_EMPTY_SLOT                  574
#define IDS_WHEEL_UP                    575
#define IDS_WHEEL_DOWN                  576
#define IDS_RANK                        577
#define IDS_SKILL_PTS                   578
#define IDS_SINGLEPLAYER                579
#define IDS_MULTIPLAYER                 580
#define IDS_OPTIONS                     581
#define IDS_CREDITS                     582
#define IDS_EXIT                        583
#define IDS_NEWGAME                     584
#define IDS_LOADGAME                    585
#define IDS_SAVEGAME                    586
#define IDS_CUSTOM_LEVEL                587
#define IDS_DISPLAY                     588
#define IDS_SOUND                       589
#define IDS_KEYBOARD                    590
#define IDS_MOUSE                       591
#define IDS_JOYSTICK                    592
#define IDS_RESTOREDEFAULTS             593
#define IDS_CONFIGURE                   594
#define IDS_BRIEFING                    595
#define IDS_OBJECTIVES                  596
#define IDS_NORMALTURN                  597
#define IDS_FASTTURN                    598
#define IDS_LOOKUP                      599
#define IDS_START_MISSION               600
#define IDS_CH_ALPHA                    601
#define IDS_CH_R                        602
#define IDS_CH_G                        603
#define IDS_CH_B                        604
#define IDS_CH_STYLE                    605
#define IDS_CH_BASIC                    606
#define IDS_CH_CROSSBAR                 607
#define IDS_CH_DOTCROSS                 608
#define IDS_CH_POST                     609
#define IDS_CH_DOT                      610
#define IDS_CH_CORNER                   611
#define IDS_CH_DYNAMIC                  612
#define IDS_CONTROLS_CROSSHAIR          613
#define IDS_PROFILE                     614
#define IDS_HELP_PROFILE                615
#define IDS_56K                         616
#define IDS_CABLE                       617
#define IDS_DSL                         618
#define IDS_TEAM_NAME                   618
#define IDS_DSL_HIGH                    619
#define IDS_T1                          620
#define IDS_T3                          621
#define IDS_BANDWIDTH_CYCLE             622
#define IDS_HELP_BANDWIDTH_CYCLE        623
#define IDS_SCORE                       624
#define IDS_HELP_BANDWIDTH_EDIT         625
#define IDS_BANDWIDTH_EDIT              626
#define IDS_PROFILE_LIST                627
#define IDS_RESUME                      628
#define IDS_CONTINUE_GAME               629
#define IDC_POINTER                     630
#define IDS_TEAM_MODEL                  630
#define IDS_GAMMA                       631
#define IDS_HEADBOB                     632
#define IDS_WEAPONSWAY                  633
#define IDS_HELP_HEADBOB                634
#define IDS_HELP_WEAPONSWAY             635
#define IDS_HELP_PICKUP_MSG_DUR         636
#define IDS_PICKUP_MSG_DUR              637
#define IDS_IGNORE_TAUNTS               638
#define IDS_HELP_IGNORE_TAUNTS          639
#define IDS_ALLOW_TAUNTS                640
#define IDS_HELP_ALLOW_TAUNTS           641
#define IDS_RENAME                      642
#define IDS_VERSION_FILTER              643
#define IDS_MAIN                        644
#define IDS_HELP_GAMMA                  645
#define IDS_HELP_SINGLEPLAYER           646
#define IDS_HELP_MULTIPLAYER            647
#define IDS_HELP_OPTIONS                648
#define IDS_HELP_EXIT                   649
#define IDS_HELP_NEW                    650
#define IDS_HELP_LOAD                   651
#define IDS_HELP_SAVE                   652
#define IDS_HELP_CUSTOM                 653
#define IDS_HELP_PROFILE_CREATE         654
#define IDS_HELP_BACK                   655
#define IDS_HELP_DIFFICULTY             656
#define IDS_HELP_DISPLAY                657
#define IDS_HELP_SOUND                  658
#define IDS_HELP_CONTROLS               659
#define IDS_HELP_RENDERER               660
#define IDS_HELP_RESOLUTION             661
#define IDS_HELP_ANTIALIAS              662
#define IDS_HELP_DETAILLEVEL            663
#define IDS_HELP_ADVDISPLAY             664
#define IDS_HELP_LOOKSPRING             665
#define IDS_HELP_RUNLOCK                666
#define IDS_HELP_CROSSHAIR              667
#define IDS_HELP_GORE                   668
#define IDS_HELP_SHADOWS                669
#define IDS_TITLE_SUBROUTINES           670
#define IDS_HELP_TEAM_MODEL             670
#define IDS_HOST_CAMPAIGN               671
#define IDS_TITLE_RATINGS               672
#define IDS_TEAM_1                      672
#define IDS_HELP_CAMPAIGN_NAME          673
#define IDS_DETAILTEXTURES              674
#define IDS_HELP_DETAILTEXTURES         675
#define IDS_ENVIRONMENT_MAP             676
#define IDS_HELP_ENVIRONMENT_MAP        677
#define IDS_DYNAMICLIGHTS               678
#define IDS_HELP_DYNAMICLIGHTS          679
#define IDS_TRIPLE_BUFF                 680
#define IDS_HELP_TRIPLE_BUFF            681
#define IDS_HELP_SETCONTROL             682
#define IDS_HELP_CUSTOMCONTROLS         683
#define IDS_HELP_MOUSE                  684
#define IDS_HELP_JOYSTICK               685
#define IDS_HELP_ADVCONTROLS            686
#define IDS_HELP_RESTORE                687
#define IDS_HELP_SOUNDFX                688
#define IDS_HELP_SOUNDVOL               689
#define IDS_HELP_SOUNDQUAL              690
#define IDS_HELP_MUSIC                  691
#define IDS_HELP_MUSICVOL               692
#define IDS_HELP_CUSTOMLEVEL            693
#define IDS_HELP_USEJOYSTICK            694
#define IDS_HELP_INVERTAXIS             695
#define IDS_HELP_DEADZONE               696
#define IDS_HELP_ANALOG                 697
#define IDS_HELP_JOY_SENSE              698
#define IDS_HELP_JOY_CENTER             699
#define IDS_HELP_INVERTY                700
#define IDS_HELP_MOUSELOOK              701
#define IDS_HELP_MOUSE_SENSE            702
#define IDS_HELP_MOUSE_INPUT            703
#define IDS_HELP_MOUSE_BUTTON           704
#define IDS_HELP_NORMALTURN             705
#define IDS_HELP_FASTTURN               706
#define IDS_HELP_LOOKUP                 707
#define IDS_HOST_CAMPAIGN_DEFAULT       708
#define IDS_HELP_CROSSHAIRMENU          709
#define IDS_HELP_LEFT                   710
#define IDS_HELP_RIGHT                  711
#define IDS_HELP_QUICKSAVE              712
#define IDS_HELP_SAVEGAME               713
#define IDS_HELP_QUICKLOAD              714
#define IDS_HELP_LOADGAME               715
#define IDS_HELP_RELOAD                 716
#define IDS_HELP_CAMPAIGN               717
#define IDS_HELP_RESUME                 718
#define IDS_HELP_CONTINUE_GAME          719
#define IDS_HELP_CH_ALPHA               720
#define IDS_HELP_CH_R                   721
#define IDS_HELP_CH_G                   722
#define IDS_HELP_CH_B                   723
#define IDS_HELP_CH_STYLE               724
#define IDS_HELP_CH_DYNAMIC             725
#define IDS_HELP_MAIN                   726
#define IDS_HELP_NEXTMISSION            727
#define IDS_HELP_CONTINUE               728
#define IDS_CAMPAIGN_EXISTS             729
#define IDS_GUN_NOPICKUP                730
#define IDS_GUN_NOPICKUP_INF            731
#define IDS_PLAYER_SETUP                732
#define IDS_JOIN                        733
#define IDS_HOST                        734
#define IDS_HELP_PLAYER                 735
#define IDS_HELP_JOIN                   736
#define IDS_HELP_HOST                   737
#define IDS_HOST_ADD_MISSION            738
#define IDS_HOST_REMOVE_MISSION         739
#define IDS_HOST_ADD_ALL                740
#define IDS_HOST_REMOVE_ALL             741
#define IDS_NOLEVELS                    742
#define IDS_HELP_OK                     743
#define IDS_SCENENUMBER                 744
#define IDS_PLAYER_SKILLS               745
#define IDS_LOOP_MISSIONS               746
#define IDS_MOVE_CONTROLS               747
#define IDS_INV_CONTROLS                748
#define IDS_VIEW_CONTROLS               749
#define IDS_MISC_CONTROLS               750
#define IDS_HELP_KEYBOARD               751
#define IDS_COMPILE                     752
#define IDS_GAME_OPTIONS                753
#define IDS_HELP_GAME_OPTIONS           754
#define IDS_DISPLAY_SUBTITLES           755
#define IDS_HELP_COMPILE                756
#define IDS_TEAM_2                      756
#define IDS_HELP_LOOP_MISSIONS          757
#define IDS_CAMPAIGN_LIST               758
#define IDS_STAT_COMBAT                 759
#define IDS_STAT_DEFENSE                760
#define IDS_STAT_ACCURACY               761
#define IDS_HELP_CAMPAIGN_CREATE        762
#define IDS_HELP_CAMPAIGN_LOAD          763
#define IDS_HELP_SUBTITLES              764
#define IDS_GAME_TYPE                   765
#define IDS_HELP_TEAM_1                 766
#define IDS_HELP_TEAM_2                 767
#define IDS_DEDICATED                   768
#define IDS_HELP_DEDICATED              769
#define IDS_GAME_LANGUAGE               770
#define IDS_MENU_VKEY_YES               771
#define IDS_MENU_VKEY_NO                772
#define IDS_DEMOVERSION                 773
#define IDS_HELP_CAMPAIGN_DELETE        774
#define IDS_HELP_CAMPAIGN_RENAME        775
#define IDS_HELP_VERSION_FILTER         776
#define IDS_ALL_VERSIONS                777
#define IDS_CURRENT_VERSION             778
#define IDS_PERFORMANCE                 779
#define IDS_HELP_PERFORMANCE            780
#define IDS_SFX                         781
#define IDS_HELP_SFX                    782
#define IDS_POLYGRIDBUMP                783
#define IDS_HELP_POLYGRIDBUMP           784
#define IDS_POLYGRIDFRES                785
#define IDS_HELP_POLYGRIDFRES           786
#define IDS_TEXTURE_RES                 787
#define IDS_HELP_TEXTURE_RES            788
#define IDS_BUMPMAP                     789
#define IDS_HELP_BUMPMAP                790
#define IDS_BILINEAR                    791
#define IDS_HELP_BILINEAR               792
#define IDS_SHADOWS                     793
#define IDS_SOUND_HIGH                  794
#define IDS_SOUND_LOW                   795
#define IDS_QUICKLOAD                   796
#define IDS_QUICKSAVE                   797
#define IDS_LOADCURRENT                 798
#define IDS_OBJECTIVES_OPTIONAL         799
#define IDS_HELP_PLAYER_SKILLS          800
#define IDS_OBJECTIVES_CHANGED          801
#define IDS_RESET_SKILLS                802
#define IDS_HELP_RESET_SKILLS           803
#define IDS_X_OF_Y                      804
#define IDS_SERVER_LAN                  805
#define IDS_USE_SKILLS                  806
#define IDS_USE_CROSSHAIR               807
#define IDS_HELP_USE_SKILLS             808
#define IDS_HUD_LAYOUT0                 809
#define IDS_HUD_LAYOUT1                 810
#define IDS_HUD_LAYOUT2                 811
#define IDS_HUDLAYOUT                   812
#define IDS_HELP_HUDLAYOUT              813
#define IDS_NO_INVENTORY                814
#define IDS_VEHICLETURN                 815
#define IDS_HELP_VEHICLETURN            816
#define IDS_HELP_RETURN                 817
#define IDS_TRILINEAR                   818
#define IDS_HELP_TRILINEAR              819
#define IDS_ANISOTROPIC                 820
#define IDS_HELP_ANISOTROPIC            821
#define IDS_DETAILLEVEL                 822
#define IDS_TRACERS                     823
#define IDS_HELP_TRACERS                824
#define IDS_DISPLAY_CURRENTMODE         825
#define IDS_SERVER_NORESPONSE           826
#define IDS_SERVER_DETAIL_VERSION       827
#define IDS_DISPLAY_CHANGE              828
#define IDS_DISPLAY_GORE                829
#define IDS_ENV_DETAIL                  830
#define IDS_HELP_ENV_DETAIL             831
#define IDS_RESPAWN                     832
#define IDS_SOUND_MUSICENABLED          833
#define IDS_SOUND_MUSICVOL              834
#define IDS_SOUND_FX                    835
#define IDS_SOUND_FXVOL                 836
#define IDS_SOUND_QUALITY               837
#define IDS_SOUND_NONE                  838
#define IDS_SOUND_IMA                   839
#define IDS_LOW                         840
#define IDS_MEDIUM                      841
#define IDS_HIGH                        842
#define IDS_CUSTOMIZED                  843
#define IDS_MOUSE_MOUSELOOK             844
#define IDS_MOUSE_LOOKSPRING            845
#define IDS_MOUSE_INVERTYAXIS           846
#define IDS_MOUSE_SENSITIVITY           847
#define IDS_MOUSE_INPUTRATE             848
#define IDS_MOUSE_LEFTBUTTON            849
#define IDS_MOUSE_MIDDLEBUTTON          850
#define IDS_MOUSE_RIGHTBUTTON           851
#define IDS_JOYSTICK_USE                852
#define IDS_JOYSTICK_TURN               853
#define IDS_JOYSTICK_LOOK               854
#define IDS_JOYSTICK_MOVE               855
#define IDS_JOYSTICK_STRAFE             856
#define IDS_JOYSTICK_BUTTONNUM          857
#define IDS_JOYSTICK_AXIS               858
#define IDS_JOYSTICK_ACTION             859
#define IDS_HELP_SERVER_LAN             860
#define IDS_POV_MOVE                    861
#define IDS_JOYSTICK_INVERT             862
#define IDS_POV_LOOK                    863
#define IDS_JOYSTICK_AXISNONE           864
#define IDS_HELP_AXIS                   865
#define IDS_DISPLAY_BITDEPTH            866
#define IDS_ANTIALIAS                   867
#define IDS_ADVCONTROLS_RUNLOCK         868
#define IDS_NEW_EASY                    869
#define IDS_NEW_MEDIUM                  870
#define IDS_NEW_HARD                    871
#define IDS_NEW_INSANE                  872
#define IDS_ADVCONTROLS_CROSSHAIR       873
#define IDS_DISPLAY_RENDERER            874
#define IDS_DISPLAY_RESOLUTION          875
#define IDS_TEAM1_NAME                  876
#define IDS_CONTROLS                    877
#define IDS_HELP_PROFILE_LOAD           878
#define IDS_SERVER_NAME                 879
#define IDS_SERVER_PLAYERS              880
#define IDS_SERVER_PING                 881
#define IDS_SERVER_GAME                 882
#define IDS_SERVER_MAP                  883
#define IDS_JOIN_PLAYER_NAME            884
#define IDS_JOIN_PLAYER_SCORE           885
#define IDS_OPTION_NAME                 886
#define IDS_OPTION_VALUE                887
#define IDS_SERVER_REFRESH              888
#define IDS_SERVER_REPING               889
#define IDS_FILTER_ALLGAMES             890
#define IDS_FILTER_DM                   891
#define IDS_FILTER_COOP                 892
#define IDS_FILTER_ALLPOP               893
#define IDS_FILTER_NOTFULL              894
#define IDS_FILTER_NOTEMPTY             895
#define IDS_FILTER_NOT_BOTH             896
#define IDS_SERVER_LOCKED               897
#define IDS_SERVER_MISSION              898
#define IDS_HELP_SERVER_MISSION         899
#define IDS_HOST_NAME                   900
#define IDS_HOST_OPTIONS                901
#define IDS_HOST_MISSIONS               902
#define IDS_HOST_LAUNCH                 903
#define IDS_SERVER_FILTERS              904
#define IDS_POP_FILTER                  905
#define IDS_NIGHT_SCOPE                 906
#define IDS_SILENCER                    907
#define IDS_LASER                       908
#define IDS_TEAM2_NAME                  908
#define IDS_FILTER_PING                 909
#define IDS_SCOPE                       910
#define IDS_CAMERA_SCOPE                911
#define IDS_KILLEDMYSELF                912
#define IDS_HEKILLEDME                  913
#define IDS_IKILLEDHIM                  914
#define IDS_HEKILLEDHIMSELF             915
#define IDS_HEKILLEDHIM                 916
#define IDS_SKILL_STEALTH               917
#define IDS_SKILL_STEALTH_DESC          918
#define IDS_SKILL_STAMINA               919
#define IDS_SKILL_STAMINA_DESC          920
#define IDS_SKILL_MARKSMANSHIP          921
#define IDS_SKILL_MARKSMANSHIP_DESC     922
#define IDS_SKILL_CARRY                 923
#define IDS_SKILL_CARRY_DESC            924
#define IDS_SKILL_ARMOR                 925
#define IDS_SKILL_ARMOR_DESC            926
#define IDS_SKILL_WEAPON                927
#define IDS_SKILL_WEAPON_DESC           928
#define IDS_SKILL_GADGET                929
#define IDS_SKILL_GADGET_DESC           930
#define IDS_SKILL_NOVICE                931
#define IDS_SKILL_AMATEUR               932
#define IDS_SKILL_SKILLED               933
#define IDS_SKILL_EXPERT                934
#define IDS_SKILL_MASTER                935
#define IDS_SKILL_UPGRADE_COST          936
#define IDS_SKILL_UPGRADE               937
#define IDS_SKILL_AVAIL                 938
#define IDS_SKILL_MAX                   939
#define IDS_SKILL_ENERGY                940
#define IDS_SKILL_ENERGY_DESC           941
#define IDS_HOST_NAME_COOP_DEFAULT      942
#define IDS_PASSWORD_DEFAULT            943
#define IDS_TARGET_SEARCH               944
#define IDS_TARGET_MOVE                 945
#define IDS_TARGET_DROP                 946
#define IDS_TARGET_TALK                 947
#define IDS_TARGET_USE                  948
#define IDS_TARGET_TAKE                 949
#define IDS_TARGET_HACK                 950
#define IDS_TITLE_HOST_WEAPONS          950
#define IDS_TARGET_HACKKEYPAD           951
#define IDS_TARGET_WELD                 952
#define IDS_TARGET_DECODE               953
#define IDS_TARGET_PICK                 954
#define IDS_TARGET_PHOTO                955
#define IDS_TARGET_BOMB                 956
#define IDS_TARGET_INK                  957
#define IDS_TARGET_BUG                  958
#define IDS_TARGET_INNOCENT             959
#define IDS_TARGET_SEARCHING            960
#define IDS_SKILL_SEARCH                961
#define IDS_SKILL_SEARCH_DESC           962
#define IDS_SPEECH_FXVOL                963
#define IDS_HELP_SPEECHVOL              964
#define IDS_TARGET_REVIVE               965
#define IDS_CURRENT_CAMPAIGN            966
#define IDS_M_STAT_UNDAMAGED            967
#define IDS_M_STAT_TIMES_HIT            968
#define IDS_M_STAT_MARKSMANSHIP         969
#define IDS_M_STAT_ACCURACY             970
#define IDS_IWASKILLED                  971
#define IDS_ENTER_CAMPAIGN_NAME         972
#define IDS_HEWASKILLED                 973
#define IDS_TARGET_HACKING              974
#define IDS_HELP_ADD_WEAPON             974
#define IDS_TARGET_HACKINGKEYPAD        975
#define IDS_TARGET_WELDING              976
#define IDS_TARGET_DECODING             977
#define IDS_TARGET_PICKING              978
#define IDS_TARGET_PHOTOGRAPHING        979
#define IDS_TARGET_BOMBING              980
#define IDS_TARGET_INKING               981
#define IDS_TARGET_BUGGING              982
#define IDS_COOP_STAT_ACCURACY          983
#define IDS_COOP_STAT_KILLS             984
#define IDS_COOP_STAT_DEATHS            985
#define IDS_STAT_MISSION                986
#define IDS_FILTER_ALLPING              987
#define IDS_FILTER_LOWPING              988
#define IDS_FILTER_MEDPING              989
#define IDS_FILTER_HIGHPING             990
#define IDS_HELP_FILTER_PING            991
#define IDS_CDKEY_ENTER                 992
#define IDS_CDKEY_INVALID               993
#define IDS_CDKEY                       994
#define IDS_BANDWIDTH_INVALID           995
#define IDS_AMMO_NOPICKUP               996
#define IDS_DMODE_RENDERER              997
#define IDS_DMODE_RESOLUTION            998
#define IDS_TARGET_WAKEUP               999
#define IDS_JOIN_GAME                   1000
#define IDS_PLAYER_NAME                 1001
#define IDS_DMODE_PLEASEWAIT1           1002
#define IDS_DMODE_PLEASEWAIT2           1003
#define IDS_HELP_PLAYER_MODEL           1004
#define IDS_HELP_PLAYER_NAME            1005
#define IDS_SCORE_PING                  1006
#define IDS_HELP_SERVER_NAME            1007
#define IDS_HELP_SERVER_PLAYERS         1008
#define IDS_HELP_SERVER_PING            1009
#define IDS_HELP_SORT_PLYR_NAME         1010
#define IDS_HELP_SORT_PLYR_SCORE        1011
#define IDS_HELP_SORT_PLYR_PING         1012
#define IDS_HELP_REFRESH                1013
#define IDS_HELP_REPING                 1014
#define IDS_HELP_GAME_FILTER            1015
#define IDS_HELP_POP_FILTER             1016
#define IDS_HELP_REM_ALL_WPNS           1017
#define IDS_MOD_NOPICKUP                1018
#define IDS_GEAR_NOPICKUP               1019
#define IDS_HELP_REM_WEAPON             1020
#define IDS_CHANGING_AMMO               1021
#define IDS_HELP_JOIN_GAME              1022
#define IDS_HELP_SESSION_NAME           1023
#define IDS_HELP_GAME_TYPE              1024
#define IDS_HELP_HOST_OPTIONS           1025
#define IDS_HELP_HOST_MISSIONS          1026
#define IDS_HELP_LAUNCH                 1027
#define IDS_HELP_AVAIL_MISSIONS         1028
#define IDS_HELP_POV                    1029
#define IDS_HELP_SEL_MISSIONS           1030
#define IDS_HELP_ADD_MISSION            1031
#define IDS_HELP_ADD_ALL                1032
#define IDS_HELP_REM_MISSION            1033
#define IDS_HELP_REM_ALL                1034
#define IDS_VSYNC                       1035
#define IDS_HELP_VSYNC                  1036
#define IDS_CURRENT                     1037
#define IDS_UPGRADE                     1038
#define IDS_LOW_VIOLENCE                1039
#define IDS_TARGET_DEFUSE               1040
#define IDS_DISARMED                    1041
#define IDS_HELP_CDKEY                  1042
#define IDS_MUSIC_QUALITY               1043
#define IDS_HELP_MUSIC_QUALITY          1044
#define IDS_CONFIRM_MUSIC               1045
#define IDS_CONFIRM_SOUND               1046
#define IDS_PLAYER_MODEL                1047
#define IDS_HELP_PERFORMANCE_TEST       1048
#define IDS_HOST_AVAIL_MISSIONS         1049
#define IDS_TITLE_PERFORMANCE_TEST      1050
#define IDS_RES_DIFFERS                 1051
#define IDS_PRECACHE                    1052
#define IDS_LOAD_USERGAME               1053
#define IDS_SHELLCASINGS                1054
#define IDS_DISCONNECT                  1055
#define IDS_HELP_SHELLCASINGS           1056
#define IDS_SHUTDOWN                    1057
#define IDS_HELP_PRECACHE               1058
#define IDS_PERFORMANCE_FPS             1059
#define IDS_WPN_RESTRICT                1059
#define IDS_PERFORMANCE_FPS_AVE         1060
#define IDS_PERFORMANCE_RESULTS         1061
#define IDS_OVERALL_PERFORM             1062
#define IDS_HELP_OVERALL_PERFORM        1063
#define IDS_PERFORM_HIGH                1064
#define IDS_PERFORM_MEDIUM              1065
#define IDS_PERFORM_LOW                 1066
#define IDS_AUTOSWITCH_WEAPONS          1067
#define IDS_HELP_AUTOSWITCH_WEAPONS     1068
#define IDS_STARTNEXTLEVEL              1069
#define IDS_PERFORMANCE_FPS_MIN         1070
#define IDS_PERFORMANCE_FPS_MAX         1071
#define IDS_JOYSTICK_UNBOUND            1072
#define IDS_FX_DETAIL                   1073
#define IDS_HELP_FX_DETAIL              1074
#define IDS_PERFORMANCE_FPS_BELOW_MIN   1075
#define IDS_PERFORMANCE_FPS_MINTOMAX    1076
#define IDS_CONFIRM_RESTORE             1077
#define IDS_PERFORMANCE_FPS_ABOVE_MAX   1078
#define IDS_PERFORMANCE_TEST_ABORTED    1079
#define IDS_NEW_MOTD                    1080
#define IDS_VALIDATION_FAILED           1081
#define IDS_HARDWARE_CURSOR             1082
#define IDS_HELP_HARDWARE_CURSOR        1083
#define IDS_CONFIRM_CURSOR              1084
#define IDS_LAUNCH_UPDATE               1085
#define IDS_HELP_LAUNCH_UPDATE          1086
#define IDS_NEW_VERSION                 1087
#define IDS_INTERNET                    1088
#define IDS_NO_CDKEY                    1089
#define IDS_TARGET_HACKCARDREADER       1090
#define IDS_LARGE                       1091
#define IDS_SMALL                       1092
#define IDS_JOIN_LAN                    1093
#define IDS_GUNPICKUP                   1094
#define IDS_OUTOFAMMO                   1095
#define IDS_GEARPICKUP                  1096
#define IDS_AMMOPICKUP                  1097
#define IDS_MODPICKUP                   1098
#define IDS_INTELLIGENCE                1099
#define IDS_HELP_JOIN_LAN               1100
#define IDS_SERVER_ADDRESS              1101
#define IDS_NO_SERVERS                  1102
#define IDS_LOOKING_FOR_SERVERS         1103
#define IDS_CONNECTING_TO_SERVER        1104
#define IDS_UNKNOWN_PLAYER              1105
#define IDS_HELP_EASY                   1106
#define IDS_HELP_MEDIUM                 1107
#define IDS_HELP_HARD                   1108
#define IDS_HELP_INSANE                 1109
#define IDS_DIFF_REMINDER               1110
#define IDS_SERVERS_SHOWN               1111
#define IDS_GUNPICKUP2                  1112
#define IDS_HELP_WPN_RESTRICT           1112
#define IDS_KEY_PICKUP                  1113
#define IDS_STATUS_STRING               1114
#define IDS_WAITING                     1115
#define IDS_QUERYING                    1116
#define IDS_VALIDATING                  1117
#define IDS_TARGET_HACKINGCARDREADER    1118
#define IDS_LOAD_TIPS                   1119
#define IDS_HELP_LOAD_TIPS              1120
#define IDS_HELP_UPGRADE                1121
#define IDS_DSL_LOW                     1122
#define IDS_CONTOUR                     1123
#define IDS_HELP_CONTOUR                1124
#define IDS_PERFORMANCE_RECOMMEND_LOWER 1125
#define IDS_PAUSED                      1126
#define IDS_UNUSED                      1127
#define IDS_PERFORMANCE_RECOMMEND_HIGHER 1128
#define IDS_PERFORMANCE_RECOMMEND_CURRENT 1129
#define IDS_PRESSANYKEY                 1130
#define IDS_EMPTY                       1131
#define IDS_PRESSKEYTOCONTINUE          1132
#define IDS_SUREWANTQUIT                1133
#define IDS_SUREWANTABORT               1134
#define IDS_BUMPER_LOADING              1135
#define IDS_INTEL_ITEMS                 1136
#define IDS_UP                          1137
#define IDS_DOWN                        1138
#define IDS_DISCON_MISSINGFILE          1139
#define IDS_DISCON_CONNECTTERM          1140
#define IDS_DISCON_SERVERBOOT           1141
#define IDS_DISCON_TIMEOUT              1142
#define IDS_WEAPON                      1143
#define IDS_KEY                         1144
#define IDS_DEVICE_MOUSE                1145
#define IDS_DEVICE_JOYSTICK             1146
#define IDS_AUTOSWITCH_AMMO             1147
#define IDS_HELP_AUTOSWITCH_AMMO        1148
#define IDS_PORT                        1149
#define IDS_HELP_ENTER_PORT             1150
#define IDS_SERVER_PORT                 1151
#define IDS_FIND_SERVERS                1152
#define IDS_HELP_FIND_SERVERS           1153
#define IDS_HELP_PROFILE_DELETE         1154
#define IDS_HELP_PROFILE_RENAME         1155
#define IDS_CONFIRM_DELETE              1156
#define IDS_CURRENT_PROFILE             1157
#define IDS_ENTER_PROFILE_NAME          1158
#define IDS_CONFIRM_NEWPROFILE          1159
#define IDS_PERFORMANCE_TEST_BRIEF      1160
#define IDS_PARAMETERS                  1161
#define IDS_SELECT_AMMO_TEXT            1162
#define IDS_EXIT_WAITING                1163
#define IDS_EXIT_WAITING_1              1164
#define IDS_EXIT_WAITING_NAME           1165
#define IDS_EXIT_PLAYER_WAITING         1166
#define IDS_EXIT_PLAYER_WAITING_1       1167
#define IDS_EXIT_PLAYER_WAITING_NAME    1168
#define IDS_NET_GAME_END                1169
#define IDS_NET_GAME_END_HELP           1170
#define IDS_CONFIRM_SKILLS              1171
#define IDS_CHOOSE_TEAM                 1172
#define IDS_FRAG_LIMIT_HELP             1173
#define IDS_HELP_CHOOSE_TEAM_1          1174
#define IDS_TIME_LIMIT_HELP             1175
#define IDS_MAX_PLAYERS                 1176
#define IDS_MAX_PLAYERS_HELP            1177
#define IDS_ROUNDS_HELP                 1178
#define IDS_RUN_SPEED_HELP              1179
#define IDS_HELP_CHOOSE_TEAM_2          1180
#define IDS_FRIENDLY_FIRE_HELP          1181
#define IDS_AUTO_SELECT                 1182
#define IDS_HELP_HOST_PLAYERDIFF        1183
#define IDS_WEAPONS_STAY                1184
#define IDS_WEAPONS_STAY_HELP           1185
#define IDS_USE_SPAWN_LIMIT             1186
#define IDS_HELP_AUTO_SELECT            1186
#define IDS_USE_SPAWN_LIMIT_HELP        1187
#define IDS_HELP_TEAM_SELECT            1187
#define IDS_SPAWN_LIMIT                 1188
#define IDS_CANCELREVIVE                1188
#define IDS_SPAWN_LIMIT_HELP            1189
#define IDS_SERVER_MOD                  1189
#define IDS_HIT_LOCATION                1190
#define IDS_HIT_LOCATION_HELP           1191
#define IDS_SCORE_LIMIT                 1192
#define IDS_HELP_SCORE_LIMIT            1193
#define IDS_ALLOWED_WEAPONS             1194
#define IDS_DISABLED_WEAPONS            1195
#define IDS_END_SCORE                   1196
#define IDS_TEAM1_BOMB                  1197
#define IDS_TEAM2_BOMB                  1198
#define IDS_HOST_ADD_WEAPON             1199
#define IDS_YES_VK_CODE                 1200
#define IDS_NO_VK_CODE                  1201
#define IDS_ALLOW_GORE                  1202
#define IDS_END_TIME                    1203
#define IDS_END_FRAG                    1204
#define IDS_END_UNKNOWN                 1205
#define IDS_USE_PASSWORD                1206
#define IDS_HELP_PASSWORD               1207
#define IDS_PASSWORD                    1208
#define IDS_HELP_ENTER_PASSWORD         1209
#define IDS_NOCUSTOMWORLDS              1210
#define IDS_DEMONOCUSTOMWORLDS          1211
#define IDS_DEMODISCONNECT              1212
#define IDS_DEMOINFO                    1213
#define IDS_WAITINGFOROTHERPLAYERS      1214
#define IDS_NOJOYSTICKDETECTED          1215
#define IDS_NOQUICKSAVEGAME             1216
#define IDS_LOADGAMEFAILED              1217
#define IDS_SAVEGAMEFAILED              1218
#define IDS_NOLOADLEVEL                 1219
#define IDS_SOUNDNOTINITED              1220
#define IDS_UNSPECIFIEDERROR            1221
#define IDS_NOREMAPKEY                  1222
#define IDS_NOSOUNDCHANGE               1223
#define IDS_NOMUSICCHANGE               1224
#define IDS_ENDCURRENTGAME              1225
#define IDS_REINITIALIZING_RENDERER     1226
#define IDS_INVALID3DSOUNDPROVIDER      1227
#define IDS_CONFIRMSAVE                 1228
#define IDS_GAMESAVED                   1229
#define IDS_REBINDING_TEXTURES          1230
#define IDS_REBINDING_LIGHTMAPS         1231
#define IDS_SHUTDOWNSERVER              1232
#define IDS_NETERR_GENERIC              1233
#define IDS_NETERR_SELECTSERVICE        1234
#define IDS_NETERR_FILLSERVICE          1235
#define IDS_NETERR_JOINSESSION          1236
#define IDS_NETERR_HOSTSESSION          1237
#define IDS_NETERR_INIT                 1238
#define IDS_NETERR_CANTBINDTOPORT       1239
#define IDS_NETERR_NOTSAMEGUID          1240
#define IDS_PLAYER                      1241
#define IDS_SAY                         1242
#define IDS_NETERR_WRONGPASS            1243
#define IDS_YOUWEREKILLED               1244
#define IDS_QUICKSAVING                 1245
#define IDS_SERVERFULL                  1246
#define IDS_SERVER_WRONGVERSION         1247
#define IDS_JOINEDGAME                  1248
#define IDS_LEFTGAME                    1249
#define IDS_SAVINGGAME                  1250
#define IDS_CANTQUICKSAVE               1251
#define IDS_ACCESSGRANTED               1252
#define IDS_ACCESSDENIED                1253
#define IDS_LOCKED                      1254
#define ID_FILLSTUFF                    1255
#define IDS_HELP_ENTER_SCMDPASSWORD     1255
#define IDS_WON_MOTD_STATUS             1256
#define IDS_WON_MOTD_SUCCESS            1257
#define IDS_WON_MOTD_FAIL               1258
#define IDS_WON_VERSION_STATUS          1259
#define IDS_WON_VERSION_SUCCESS         1260
#define IDS_WON_VERSION_FAIL            1261
#define IDS_WON_CDKEY_STATUS            1262
#define IDS_WON_CDKEY_SUCCESS           1263
#define IDS_WON_CDKEY_FAIL              1264
#define IDS_WON_PUB_STATUS              1265
#define IDS_WON_PUB_SUCCESS             1266
#define IDS_WON_PUB_FAIL                1267
#define IDS_WON_REM_STATUS              1268
#define IDS_WON_REM_SUCCESS             1269
#define IDS_WON_REM_FAIL                1270
#define IDS_WON_LIST_STATUS             1271
#define IDS_WON_LIST_SUCCESS            1272
#define IDS_WON_LIST_FAIL               1273
#define IDS_WON_CLEAR_REQ_LIST          1274
#define IDS_WON_PROCESS_REQ             1275
#define IDS_WON_PING_SUCCESS            1276
#define IDS_WON_DETAIL_SUCCESS          1277
#define IDS_WON_DETAIL_FAIL             1278
#define IDS_WON_VAL_SUCCESS             1279
#define IDS_WON_VAL_FAIL                1280
#define IDS_WON_SERV_VAL                1281
#define IDS_DISCONNECTED_FROM_SERVER    1282
#define IDS_CANT_CONNECT_TO_SERVER      1283
#define IDS_CONTROL_FORWARD             1284
#define IDS_CONTROL_BACKWARD            1285
#define IDS_CONTROL_TURNLEFT            1286
#define IDS_CONTROL_TURNRIGHT           1287
#define IDS_CONTROL_STRAFE              1288
#define IDS_CONTROL_STRAFELEFT          1289
#define IDS_CONTROL_STRAFERIGHT         1290
#define IDS_CONTROL_TURNAROUND          1291
#define IDS_CONTROL_RUN                 1292
#define IDS_CONTROL_FIRE                1293
#define IDS_CONTROL_ACTIVATE            1294
#define IDS_CONTROL_JUMP                1295
#define IDS_CONTROL_RELOAD              1296
#define IDS_CONTROL_DUCK                1297
#define IDS_CONTROL_NEXTWEAPON          1298
#define IDS_CONTROL_PREVIOUSWEAPON      1299
#define IDS_CONTROL_LOOKUP              1300
#define IDS_CONTROL_LOOKDOWN            1301
#define IDS_CONTROL_CENTERVIEW          1302
#define IDS_CONTROL_INVENTORY           1303
#define IDS_CONTROL_MISSION             1304
#define IDS_CONTROL_HOLSTERWEAPON       1305
#define IDS_CONTROL_STATUS              1306
#define IDS_CONTROL_SAY                 1307
#define IDS_CONTROL_ALT_FIRING          1308
#define IDS_CONTROL_NEXT_AMMO           1309
#define IDS_CONTROL_KEYS                1310
#define IDS_CONTROL_INTEL               1311
#define IDS_CONTROL_RUNLOCKTOGGLE       1312
#define IDS_CONTROL_WEAPON1             1313
#define IDS_CONTROL_WEAPON2             1314
#define IDS_CONTROL_WEAPON3             1315
#define IDS_CONTROL_WEAPON4             1316
#define IDS_CONTROL_WEAPON5             1317
#define IDS_CONTROL_WEAPON6             1318
#define IDS_CONTROL_WEAPON7             1319
#define IDS_CONTROL_WEAPON8             1320
#define IDS_CONTROL_WEAPON9             1321
#define IDS_CONTROL_WEAPON10            1322
#define IDS_CONTROL_ZOOM_IN             1323
#define IDS_CONTROL_ZOOM_OUT            1324
#define IDS_CONTROL_UNASSIGNED          1325
#define IDS_CONTROL_NEXTVISMODE         1326
#define IDS_CONTROL_COMPASS             1327
#define IDS_CONTROL_LEANLEFT            1328
#define IDS_CONTROL_LEANRIGHT           1329
#define IDS_CONTROL_CROUCHTOGGLE        1330
#define IDS_CONTROL_MOVE_BODY           1331
#define IDS_CONTROL_FLASHLIGHT          1332
#define IDS_CONTROL_RADIO               1333
#define IDS_CONTROL_LASTWEAPON          1334
#define IDS_ACTIONSTRING_FORWARD        1335
#define IDS_ACTIONSTRING_BACKWARD       1336
#define IDS_ACTIONSTRING_TURNLEFT       1337
#define IDS_ACTIONSTRING_TURNRIGHT      1338
#define IDS_ACTIONSTRING_STRAFE         1339
#define IDS_ACTIONSTRING_STRAFELEFT     1340
#define IDS_ACTIONSTRING_STRAFERIGHT    1341
#define IDS_ACTIONSTRING_TURNAROUND     1342
#define IDS_ACTIONSTRING_RUN            1343
#define IDS_ACTIONSTRING_FIRE           1344
#define IDS_ACTIONSTRING_ACTIVATE       1345
#define IDS_ACTIONSTRING_JUMP           1346
#define IDS_ACTIONSTRING_RELOAD         1347
#define IDS_ACTIONSTRING_DUCK           1348
#define IDS_ACTIONSTRING_NEXTWEAPON     1349
#define IDS_ACTIONSTRING_PREVIOUSWEAPON 1350
#define IDS_ACTIONSTRING_LOOKUP         1351
#define IDS_ACTIONSTRING_LOOKDOWN       1352
#define IDS_ACTIONSTRING_CENTERVIEW     1353
#define IDS_ACTIONSTRING_INVENTORY      1354
#define IDS_ACTIONSTRING_MISSION        1355
#define IDS_ACTIONSTRING_HOLSTERWEAPON  1356
#define IDS_ACTIONSTRING_STATUS         1357
#define IDS_ACTIONSTRING_SAY            1358
#define IDS_ACTIONSTRING_ALT_FIRING     1359
#define IDS_ACTIONSTRING_KEYS           1360
#define IDS_ACTIONSTRING_INTEL          1361
#define IDS_ACTIONSTRING_RUNLOCKTOGGLE  1362
#define IDS_ACTIONSTRING_CROUCHTOGGLE   1363
#define IDS_ACTIONSTRING_UNASSIGNED     1364
#define IDS_ACTIONSTRING_NEXTAMMO       1365
#define IDS_ACTIONSTRING_ZOOMIN         1366
#define IDS_ACTIONSTRING_ZOOMOUT        1367
#define IDS_ACTIONSTRING_NEXTVISMODE    1368
#define IDS_ACTIONSTRING_COMPASS        1369
#define IDS_ACTIONSTRING_LEANLEFT       1370
#define IDS_ACTIONSTRING_LEANRIGHT      1371
#define IDS_ACTIONSTRING_MOVE_BODY      1372
#define IDS_ACTIONSTRING_FLASHLIGHT     1373
#define IDS_ACTIONSTRING_RADIO          1374
#define IDS_ACTIONSTRING_LASTWEAPON     1375
#define IDS_ABORT                       1376
#define IDS_DECODEMSG_CHARSET           1377
#define IDS_SCMDPASSWORD                1378
#define IDS_HELP_ALLOWSCMD              1379
#define IDS_HOST_NAME_DM_DEFAULT        1380
#define IDS_TAGGEDMYSELF                1381
#define IDS_HETAGGEDME                  1382
#define IDS_ITAGGEDHIM                  1383
#define IDS_HETAGGEDHIMSELF             1384
#define IDS_HETAGGEDHIM                 1385
#define IDS_IWASTAGGED                  1386
#define IDS_HEWASTAGGED                 1387
#define IDS_KICKBAN                     1388
#define IDS_SCORE_SCORE                 1389
#define IDS_SCORE_PLAYERS               1390
#define IDS_SCORE_KILLS                 1391
#define IDS_SCORE_TAGS                  1392
#define IDS_CONTROL_TEAM_SAY            1393
#define IDS_ACTIONSTRING_TEAM_SAY       1394
#define IDS_DOOMSDAY_CORE               1395
#define IDS_DOOMSDAY_TRANSMITTER        1396
#define IDS_DOOMSDAY_BATTERIES          1397
#define IDS_DOOMSDAY_PICKEDUP           1398
#define IDS_DOOMSDAY_DROPPED            1399
#define IDS_DOOMSDAY_PLACED             1400
#define IDS_DOOMSDAY_STOLE              1401
#define IDS_DOOMSDAY_DEVICE_COMPLETED   1402
#define IDS_DOOMSDAY_RESPAWNED          1403
#define IDS_HELP_SERVER_MOD             1404
#define IDS_FILTER_MOD                  1405
#define IDS_HELP_FILTER_MOD             1406
#define IDS_FILTER_ALLMODS              1407
#define IDS_RETAIL                      1408
#define IDS_FILTER_CURRENTMOD           1409
#define IDS_SERVER_WRONGMOD             1410
#define IDS_HECHANGED                   1411
#define IDS_ICHANGED                    1412
#define IDS_IWILLCHANGE                 1413
#define IDS_FRAG_SCORE                  1414
#define IDS_FRAG_SCORE_HELP             1415
#define IDS_TAG_SCORE                   1416
#define IDS_TAG_SCORE_HELP              1417
#define IDS_REVIVE_SCORE                1418
#define IDS_REVIVE_SCORE_HELP           1419
#define IDS_DD_COMP_SCORE               1420
#define IDS_DD_COMP_SCORE_HELP          1421
#define IDS_DD_HVY_SCORE                1422
#define IDS_DD_HVY_SCORE_HELP           1423
#define IDS_DD_LGT_SCORE                1424
#define IDS_DD_LGT_SCORE_HELP           1425
#define IDS_DD_REMOVED_SCORE            1426
#define IDS_DD_REMOVED_SCORE_HELP       1427
#define IDS_HOST_REMOVE_WEAPON          1428
#define IDS_HELP_ADD_WEAPONS            1429
#define IDS_HELP_REM_WEAPONS            1430
#define IDS_MISSING_WORLD               1431
#define IDS_SKILL_2110                  2110
#define IDS_SKILL_2111                  2111
#define IDS_SKILL_2112                  2112
#define IDS_SKILL_2113                  2113
#define IDS_SKILL_2114                  2114
#define IDS_SKILL_2115                  2115
#define IDS_SKILL_2116                  2116
#define IDS_SKILL_2117                  2117
#define IDS_SKILL_2118                  2118
#define IDS_SKILL_2119                  2119
#define IDS_SKILL_2120                  2120
#define IDS_SKILL_2121                  2121
#define IDS_SKILL_2122                  2122
#define IDS_SKILL_2123                  2123
#define IDS_SKILL_2124                  2124
#define IDS_SKILL_2125                  2125
#define IDS_SKILL_2126                  2126
#define IDS_SKILL_2127                  2127
#define IDS_SKILL_2128                  2128
#define IDS_SKILL_2129                  2129
#define IDS_SKILL_2130                  2130
#define IDS_SKILL_2131                  2131
#define IDS_SKILL_2132                  2132
#define IDS_SKILL_2133                  2133
#define IDS_SKILL_2134                  2134
#define IDS_SKILL_2135                  2135
#define IDS_SKILL_HELP_2150             2150
#define IDS_SKILL_HELP_2151             2151
#define IDS_SKILL_HELP_2152             2152
#define IDS_SKILL_HELP_2153             2153
#define IDS_SKILL_HELP_2154             2154
#define IDS_SKILL_HELP_2155             2155
#define IDS_SKILL_HELP_2156             2156
#define IDS_SKILL_HELP_2157             2157
#define IDS_SKILL_HELP_2158             2158
#define IDS_SKILL_HELP_2159             2159
#define IDS_SKILL_HELP_2160             2160
#define IDS_SKILL_HELP_2161             2161
#define IDS_SKILL_HELP_2162             2162
#define IDS_SKILL_HELP_2163             2163
#define IDS_SKILL_HELP_2164             2164
#define IDS_SKILL_HELP_2165             2165
#define IDS_SKILL_HELP_2166             2166
#define IDS_SKILL_HELP_2167             2167
#define IDS_SKILL_HELP_2168             2168
#define IDS_SKILL_HELP_2169             2169
#define IDS_SKILL_HELP_2170             2170
#define IDS_SKILL_HELP_2171             2171
#define IDS_SKILL_HELP_2172             2172
#define IDS_SKILL_HELP_2173             2173
#define IDS_SKILL_HELP_2174             2174
#define IDS_SKILL_HELP_2175             2175
#define IDS_ALLOW_SCMD_COMMANDS         2176
#define IDS_TARGET_OPEN_2177            2177
#define IDS_TARGET_CLOSE_2178           2178
#define IDS_TARGET_TIPOVER_2179         2179
#define IDS_APP_SHUTDOWN_1              2200
#define IDS_PROFILE_ALREADY_EXISTS      2201
#define IDS_CONFIRM_DELETE_PROFILE      2202
#define IDS_APP_UNABLE_TO_CREATE_HW_TNL_DEVICE 2203

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2203
#define _APS_NEXT_COMMAND_VALUE         2203
#define _APS_NEXT_CONTROL_VALUE         2203
#define _APS_NEXT_SYMED_VALUE           2203
#endif
#endif
