#ifndef __COMMANDS_H__
#define __COMMANDS_H__

// Commands...
#define COMMAND_FORWARD			0
#define COMMAND_BACKWARD		1
#define COMMAND_LEFT			2
#define COMMAND_RIGHT			3
#define COMMAND_TURNAROUND		4
#define COMMAND_DUCK			5
#define COMMAND_JUMP			6
#define COMMAND_RUN				7
#define COMMAND_RUNLOCK			8
#define COMMAND_FIRE			9
#define COMMAND_ALTFIRE			10
#define COMMAND_USE				11
#define COMMAND_STRAFE			12
#define COMMAND_STRAFELEFT		13
#define COMMAND_STRAFERIGHT		14
#define COMMAND_LOOKUP			15
#define COMMAND_LOOKDOWN		16
#define COMMAND_AIMUP			17
#define COMMAND_AIMDOWN			18
#define COMMAND_MOUSEAIMTOGGLE	19
#define COMMAND_CROSSHAIR		20

#define COMMAND_NEXTINVENTORY	21
#define COMMAND_PREVINVENTORY	22
#define COMMAND_USEINVENTORY	23
#define COMMAND_SCREENSHRINK	24
#define COMMAND_SCREENENLARGE	25
#define COMMAND_HOLSTERWEAPON	26
#define COMMAND_NEXTWEAPON		27
#define COMMAND_PREVWEAPON		28
#define COMMAND_DROPWEAPON		29

#define COMMAND_INVITEM_0		30
#define COMMAND_INVITEM_1		31
#define COMMAND_INVITEM_2		32
#define COMMAND_INVITEM_3		33

#define COMMAND_PROXIMITIES		40
#define COMMAND_REMOTES			41
#define COMMAND_TIME			42
#define COMMAND_DETONATE		43

#define COMMAND_RESPAWN			50
#define COMMAND_GRAB			51
#define COMMAND_MESSAGE			52
#define COMMAND_TAUNT			53

#define COMMAND_WEAPON_0		70
#define COMMAND_WEAPON_1		71
#define COMMAND_WEAPON_2		72
#define COMMAND_WEAPON_3		73
#define COMMAND_WEAPON_4		74
#define COMMAND_WEAPON_5 		75
#define COMMAND_WEAPON_6		76
#define COMMAND_WEAPON_7		77
#define COMMAND_WEAPON_8		78
#define COMMAND_WEAPON_9		79

#endif // __COMMANDS_H__