//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FxED.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      104
#define IDR_MAINFRAME                   128
#define IDR_SPELLETYPE                  129
#define IDD_DLGBAR                      130
#define IDI_CLOSED                      132
#define IDI_OPEN                        133
#define IDD_SPELLLIST                   133
#define IDI_SPELL                       134
#define IDD_STRINGDLG                   134
#define IDD_SPELLRESOLUTION             135
#define IDI_RESOURCE                    135
#define IDD_SPELLBASEPARAMETERS         136
#define IDB_SPELLWRAP                   141
#define IDD_EF_ALTERATTRIBUTE           142
#define IDR_TRACKWINDOW                 144
#define IDD_PHASEINFO                   145
#define IDD_PHASEINFODLG                145
#define IDD_TIMEBAR                     146
#define IDC_RIGHT                       148
#define IDC_LEFT                        149
#define IDD_FXPROP                      149
#define IDC_LEFTRIGHT                   150
#define IDD_FX                          150
#define IDD_REZ                         151
#define IDD_COLOURKEYS                  153
#define IDD_CHOOSECLRANIM               155
#define IDD_MOTIONKEYS                  157
#define IDD_KEYCONTROL                  158
#define IDD_SCALEKEYS                   159
#define IDD_CHOOSESCLANIM               160
#define IDD_INTEGERDLG                  161
#define IDD_FLOATDLG                    162
#define IDD_CHOOSESFAVKEY               164
#define IDD_COPYDATA                    165
#define IDD_CHOOSEMVANIM                166
#define IDD_IMPORTSPELLS                167
#define IDD_SHOWRESOURCES               168
#define IDD_EDITVECTOR                  169
#define IDC_GAMEINFO                    180
#define IDC_SPELLSLIST                  1000
#define IDC_EDIT1                       1001
#define IDC_LIST1                       1002
#define IDC_ALLEFFECTS                  1002
#define IDC_FXLIST                      1002
#define IDC_SPELLS                      1002
#define IDC_RESOURCELIST                1002
#define IDC_LIST2                       1003
#define IDC_EFFECTS                     1003
#define IDC_FAVOURITES                  1003
#define IDC_BUTTON1                     1004
#define IDC_ADD                         1004
#define IDC_FULLOPAC                    1004
#define IDC_DELCLRFAV                   1004
#define IDC_MINSCALE                    1004
#define IDC_PHASELENGTH                 1004
#define IDC_CREATEKEY                   1004
#define IDC_NONE                        1004
#define IDC_BROWSEAPP                   1004
#define IDC_BUTTON2                     1005
#define IDC_TOTEMS                      1005
#define IDC_REMOVE                      1005
#define IDC_FULLTRANS                   1005
#define IDC_MAXSCALE                    1005
#define IDC_DELETEALL                   1005
#define IDC_KEYREPEATS                  1005
#define IDC_BROWSEREZ                   1005
#define IDC_LEVEL                       1006
#define IDC_LEVELS                      1006
#define IDC_HALF                        1006
#define IDC_MIRRORX                     1006
#define IDC_BROWSEDLL                   1006
#define IDC_DESCRIPTION                 1007
#define IDC_RESET                       1007
#define IDC_MIRRORY                     1007
#define IDC_BUTTON3                     1008
#define IDC_ADDTOTEM                    1008
#define IDC_ADDTOFAVOURITES             1008
#define IDC_MIRRORZ                     1008
#define IDC_BUTTON4                     1009
#define IDC_REMOVETOTEM                 1009
#define IDC_CHOOSEFAVOURITE             1009
#define IDC_SELECTKEY                   1009
#define IDC_EDIT3                       1010
#define IDC_COST                        1010
#define IDC_DELETEKEY                   1010
#define IDC_SETALLSCALE                 1010
#define IDC_MOVEKEY                     1010
#define IDC_COMBO3                      1011
#define IDC_CASTHOWOFTEN                1011
#define IDC_DELETESINGLEKEY             1011
#define IDC_COMBO4                      1012
#define IDC_CASTPTTYPE                  1012
#define IDC_SELECTALL                   1012
#define IDC_COMBO1                      1013
#define IDC_ATTR                        1013
#define IDC_ANIMSPEED                   1013
#define IDC_UNSELECTALL                 1013
#define IDC_PRESETS                     1013
#define IDC_TYPE                        1014
#define IDC_ADDTOMOVEFAVOURITES         1014
#define IDC_RADIUS                      1015
#define IDC_CHOOSEMOVEFAVOURITE         1015
#define IDC_TARGET                      1016
#define IDC_SPLIT                       1016
#define IDC_EXPIRES                     1017
#define IDC_ROTATE                      1017
#define IDC_NAME                        1018
#define IDC_REQUIRESTOTEM               1019
#define IDC_AFFECTS                     1020
#define IDC_SPIN1                       1021
#define IDC_INITIALDELAY                1022
#define IDC_SPIN2                       1023
#define IDC_DECRIPTION                  1024
#define IDC_STATIC7                     1025
#define IDC_APPLY                       1026
#define IDC_REPEAT                      1027
#define IDC_RATE                        1027
#define IDC_ACTIVATIONPHASE             1028
#define IDC_STATIC8                     1029
#define IDC_STATIC1                     1030
#define IDC_STATIC2                     1031
#define IDC_STATIC3                     1032
#define IDC_STATIC4                     1033
#define IDC_STATIC5                     1034
#define IDC_STATIC6                     1035
#define IDC_PROPRECT                    1036
#define IDC_AMOUNT                      1037
#define IDC_TIMEPROP                    1045
#define IDC_TIMEBAR                     1046
#define IDC_TIMESCALE                   1047
#define IDC_TIMESCROLL                  1048
#define IDC_PROPERTIESRECT              1053
#define IDC_REZ                         1054
#define IDC_DLL                         1055
#define IDC_CHECK1                      1057
#define IDC_SHOWMARKERS                 1057
#define IDC_COLORKEYS                   1057
#define IDC_KEYCONTROL                  1058
#define IDC_MOTIONKEYS                  1059
#define IDC_COLOURTEST                  1060
#define IDC_SCALEKEYS                   1061
#define IDC_INTEGER                     1065
#define IDC_TOTALKEYS                   1069
#define IDC_TOTALTRACKS                 1070
#define IDC_STARTTIME                   1071
#define IDC_ENDTIME                     1072
#define IDC_TOTALTIME                   1073
#define IDC_KEYINFO                     1074
#define IDC_KEYINFO1                    1075
#define IDC_KEYINFO3                    1076
#define IDC_KEYINFO2                    1077
#define IDC_MOTION                      1078
#define IDC_SHOWNUMBERS                 1079
#define IDC_SHOWPATHS                   1080
#define IDC_USEPRESET                   1087
#define IDC_PRESET                      1088
#define IDC_REPS                        1089
#define IDC_COMBO5                      1090
#define IDC_ANIMSIZE                    1091
#define IDC_KEYINFO4                    1094
#define IDC_FOUNDRESOURCE               1095
#define IDC_SCALE                       1096
#define IDC_PROPSCROLL                  1097
#define IDC_PITCH                       1104
#define IDC_YAW                         1105
#define IDC_MAGNITUDE                   1106
#define IDC_APP                         1141
#define IDC_COMMANDLINE                 1142
#define ID_ADDGROUP                     32771
#define ID_DELETEGROUP                  32772
#define ID_ADDSPELL                     32773
#define ID_DELETESPELL                  32774
#define ID_DELETESPELLFROMGROUP         32775
#define ID_ADDSPELLSBYREF               32776
#define ID_RENAMESPELL                  32777
#define ID_RENAMEGROUP                  32778
#define ID_EDITSPELL                    32779
#define ID_GROUP_MAKECOPY               32787
#define ID_TRACK_ADDTRACK               32788
#define ID_TRACK_INSERTTRACK            32789
#define ID_TRACK_ADDKEY                 32790
#define ID_TRACK_EDITKEY                32791
#define ID_TRACK_DELETEKEY              32792
#define ID_TRACK_EXPANDKEY              32793
#define ID_FILE_SAVESPELLS              32796
#define ID_FILE_SAVESPELLS_AS           32797
#define ID_TRACK_EDITCOLOURKEYS         32798
#define ID_FILE_LAUNCH                  32800
#define ID_TRACK_EDITMOTIONKEYS         32801
#define ID_TRACK_EDITSCALEKEYS          32802
#define ID_TRACK_ADDKEYTOFAVOURITES     32803
#define ID_TRACK_ADDFAVOURITEKEY        32804
#define ID_FILE_IMPORTCOLOURFAVOURITES  32805
#define ID_FILE_IMPORTSCALEFAVOURITES   32806
#define ID_FILE_IMPORTKEYFAVOURITES     32807
#define ID_FILE_IMPORTMOVEFAVOURITES    32808
#define ID_TRACK_DELETETRACK            32809
#define ID_TRACK_COPYMULTIKEYS          32810
#define ID_IMPORTSPELL                  32811
#define ID_TRACK_MAKESAMELENGTH         32812
#define ID_FILE_RELOADRESOURCEFILE      32813
#define ID_TRACK_LINKKEY                32814
#define ID_TRACK_UNLINKKEY              32815
#define ID_TRACK_SETKEYLENGTH           32816
#define ID_FILE_EDITGAMEINFO            32817
#define ID_FILE_FINDFXCONTAININGRESOURCE 32818
#define ID_FORMAT_TEXT                  32819
#define ID_FORMAT_BINARY                32820
#define ID_FORMAT_TEXTTOBINARY          32821
#define ID_FORMAT_BINARYTOTEXT          32822
#define ID_TRACK_NAMEKEY                32823
#define ID_TRACK_CHANGEKEY              32824

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
