//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ModelEdit.rc
//
#define IDS_LOD_NUM_TEXT                1
#define IDS_INVALIDMODEL                2
#define IDS_GENERIC_NUM_STRING          3
#define IDDEFAULT                       3
#define IDC_APPLY                       3
#define IDAPPLY                         3
#define IDC_BUTTON_USE_X                3
#define IDS_TITLE_TEXT                  4
#define IDC_BUTTON_USE_Z                4
#define IDS_DUPLICATESOCKETNAME         5
#define IDS_INVALIDNODENAME             6
#define IDS_VERSION_NUM                 7
#define IDD_MODELEDIT_DIALOG            102
#define IDD_SOCKETEDIT                  103
#define IDR_MAINFRAME                   128
#define IDD_STRINGDLG                   139
#define IDD_DIALOG_RENAME               148
#define IDR_KEYFRAME_MENU               149
#define IDB_MARKER_TOP                  150
#define IDB_MARKER_BOTTOM               151
#define IDD_EDIT_KEYFRAME_TIME          153
#define IDD_CONTINUOUS_DIALOG           154
#define IDD_MODELINFO                   155
#define IDD_GENLOD                      156
#define IDD_COMMANDSTRINGEDIT           157
#define IDD_KEYFRAMESTRING              158
#define IDD_DIMENSIONS                  160
#define IDD_IMPORTANIM                  161
#define IDD_ANIMATIONFRAMERATE          162
#define IDB_BITMAP1                     163
#define IDB_BITMAP2                     164
#define IDD_TRANSLATIONDLG              165
#define IDD_UVIMPORT2                   166
#define IDD_ANIMNUMBER                  167
#define IDB_BITMAP3                     168
#define IDD_RENAMENODE                  169
#define IDR_MODELEDITMENU               170
#define IDD_ROTATIONDLG                 170
#define IDR_ACCELERATOR1                171
#define IDD_ABOUT                       172
#define IDD_ADDSOCKET                   174
#define IDD_ANIMMERGE                   176
#define IDD_WEIGHTEDIT                  177
#define IDB_BITMAP4                     178
#define IDD_LODEDIT                     179
#define IDD_PIECEINFO                   180
#define IDD_ADDCHILDMODELDLG            181
#define IDD_TIMEOFFSET                  182
#define IDR_MENU_ANIMLIST               183
#define IDD_WEIGHTSETSELECT             184
#define IDD_SETFOV                      197
#define IDD_EXPORT_D3D                  198
#define IDD_LOADLTA                     199
#define IDD_ADDCHILDMODEL               201
#define IDD_IMPSTRINGKEYS               202
#define IDD_PIECEMATERIAL               203
#define IDD_DIALOG1                     204
#define IDR_NODE_EDIT                   205
#define IDD_EDIT_OBB                    206
#define IDR_PIECE_EDIT                  206
#define IDD_PIECE_LOD_GEN               207
#define IDR_IMPORTLODS                  207
#define IDD_IMPORT_LODS                 208
#define IDR_SOCKET_EDIT                 208
#define IDD_INVALIDANIMDIMS             210
#define IDC_ENTEREDTEXT                 1009
#define IDC_MSGTEXT                     1010
#define IDC_PREVKEY                     1015
#define IDC_RPLAY                       1016
#define IDC_STOP                        1017
#define IDC_FPLAY                       1018
#define IDC_NEXTKEY                     1019
#define IDC_BUTTON6                     1020
#define IDC_BUTTON7                     1021
#define IDC_CREATE_SINGLE_FRAME         1021
#define IDC_RENAME                      1022
#define IDC_LOADMODEL                   1023
#define IDC_BUTTON9                     1024
#define IDC_SAVE                        1024
#define IDC_BUTTON10                    1025
#define IDC_IMPORT                      1025
#define IDC_BUTTON11                    1026
#define IDC_SAVEAS                      1026
#define IDC_CONTINUOUS                  1027
#define IDC_RENDER                      1028
#define IDC_ANIMLIST                    1029
#define IDC_MOVEUP                      1030
#define IDC_MOVEDOWN                    1031
#define IDC_EDIT1                       1031
#define IDC_DELETE                      1032
#define IDC_NEW_TIME                    1032
#define IDC_SPECULARSCALE               1032
#define IDC_EDIT_OBB_POS_Y              1032
#define IDC_KEYFRAME                    1033
#define IDC_KEYFRAME1                   1033
#define IDC_TEXTUREINDEX0               1033
#define IDC_EDIT_OBB_POS_Z              1033
#define IDC_WIREFRAME                   1034
#define IDC_KEYFRAME2                   1034
#define IDC_TEXTUREINDEX1               1034
#define IDC_EDIT_OBB_ROT_X              1034
#define IDC_CURRENT_TIME                1035
#define IDC_NODELIST                    1035
#define IDC_TEXTUREINDEX2               1035
#define IDC_EDIT_OBB_ROT_Y              1035
#define IDC_DELAY                       1036
#define IDC_CAMERA_FOLLOW               1036
#define IDC_KEYFRAME3                   1036
#define IDC_TEXTUREINDEX3               1036
#define IDC_EDIT_OBB_ROT_Z              1036
#define IDC_MODEL_BOX                   1037
#define IDC_KEYFRAME4                   1037
#define IDC_ANIM_BOX                    1038
#define IDC_LOD_SCROLL                  1039
#define IDC_LOD_TEXT                    1040
#define IDC_EDIT_OBB_SIZ_X              1040
#define IDC_MODELINFO                   1041
#define IDC_MODELINFOTEXT               1041
#define IDC_CHILDMODELS                 1041
#define IDC_EDIT_OBB_SIZ_Y              1041
#define IDC_COMMANDSTRING_BUTTON        1042
#define IDC_SOCKETLIST                  1042
#define IDC_EDIT_OBB_SIZ_Z              1042
#define IDC_EDGELENGTHCHECK             1043
#define IDC_DIMS                        1043
#define IDC_LOD_TEXT2                   1043
#define IDC_TRIAREAMETHOD               1044
#define IDC_DIMENSIONS_BUTTON           1044
#define IDC_MAXEDGELENGTH               1045
#define IDC_ANIMATION_FRAMERATE         1045
#define IDC_MINIMUM_NODE_POLIES         1047
#define IDC_THESTRING                   1047
#define IDC_TRANSLATION_BUTTON          1047
#define IDC_XDIM                        1048
#define IDC_NUMBER                      1048
#define IDC_TRI_PERCENT                 1048
#define IDC_YDIM                        1049
#define IDC_USEUVCOORDS                 1049
#define IDC_DUPLICATEANIM               1049
#define IDC_IMPORT_USEUVCOORDS          1049
#define IDC_TRI_MIN                     1049
#define IDC_ZDIM                        1050
#define IDC_ANIMATIONS                  1050
#define IDC_RENAMENODE                  1050
#define IDC_IMPORT_ANIMATIONS           1050
#define IDC_IMPORTUSERDIMS              1051
#define IDC_IMPORT_USERDIMS             1051
#define IDC_ALLANIMATIONS               1052
#define IDC_IMPORTTRANSLATIONS          1052
#define IDC_IMPORT_TRANSLATIONS         1052
#define IDC_FRAMERATESTRING             1053
#define IDC_IMPORT_WEIGHTSETS           1053
#define IDC_EDIT2                       1054
#define IDC_IMPORT_LODS                 1054
#define IDC_SOCKETEDIT_ATTACHMENT       1054
#define IDC_CURRENT_DIST                1054
#define IDC_FRAMETIME                   1055
#define IDC_FRAMESTRING                 1056
#define IDC_XTRANS                      1057
#define IDC_MIN_LODOFF                  1057
#define IDC_YTRANS                      1058
#define IDC_ZTRANS                      1059
#define IDC_JUSTCENTER                  1060
#define IDC_XDIMSSUB                    1061
#define IDC_APPLYOFFSET                 1061
#define IDC_XSUB                        1061
#define IDC_XDIMSADD                    1062
#define IDC_XADD                        1062
#define IDC_YDIMSSUB                    1063
#define IDC_YSUB                        1063
#define IDC_YDIMSADD                    1064
#define IDC_YADD                        1064
#define IDC_ZDIMSSUB                    1065
#define IDC_ZSUB                        1065
#define IDC_ZDIMSADD                    1066
#define IDC_ZADD                        1066
#define IDC_XTRANSSUB                   1067
#define IDC_XTRANSADD                   1068
#define IDC_YTRANSSUB                   1069
#define IDC_YTRANSADD                   1070
#define IDC_ZTRANSSUB                   1071
#define IDC_ZTRANSADD                   1072
#define IDC_ANIMATIONNAME               1074
#define IDC_MOVENUMBER                  1075
#define IDC_OLDNAME                     1076
#define IDC_NEWNAME                     1077
#define IDC_ROTX                        1078
#define IDC_ROTY                        1079
#define IDC_ROTZ                        1080
#define IDC_DRAWSKELETON                1081
#define IDC_SOCKETNAME                  1083
#define IDC_NODENAME                    1084
#define IDC_SOCKETROTRIGHT              1084
#define IDC_SOCKETROTUP                 1085
#define IDC_NEWANIMNAME                 1085
#define IDC_SOCKETROTFORWARD            1086
#define IDC_SOCKETPOSRIGHT              1087
#define IDC_SOCKETPOSUP                 1088
#define IDC_SOCKETPOSFORWARD            1089
#define IDC_ANIMACTIVE1                 1090
#define IDC_SOCKET_EDIT                 1091
#define IDC_SOCKET_EDIT2                1092
#define IDC_GLOBAL_SPACE                1093
#define IDC_DIMS_EDIT                   1094
#define IDC_TRANSLATION_EDIT            1095
#define IDC_SINGLEFRAMEDIFFERENCE       1096
#define IDC_ANIMACTIVE2                 1096
#define IDC_WEIGHTSETS                  1097
#define IDC_ANIMACTIVE3                 1097
#define IDC_WEIGHT                      1098
#define IDC_ANIMACTIVE4                 1098
#define IDC_ADDSET                      1099
#define IDC_SOCKETSCLRIGHT              1099
#define IDC_PIECES                      1100
#define IDC_REMOVESET                   1100
#define IDC_LODS                        1100
#define IDC_NODES                       1101
#define IDC_ADDLOD                      1101
#define IDC_SOCKETSCLUP                 1101
#define IDC_EDITLOD                     1102
#define IDC_DISTANCE                    1102
#define IDC_SOCKETSCLFORWARD            1102
#define IDC_REMOVELOD                   1103
#define IDC_REDUCTION                   1103
#define IDC_MAXLODS                     1104
#define IDC_COMMANDSTRING               1105
#define IDC_ANIMATIONLENGTH             1106
#define IDC_PIECELIST                   1106
#define IDC_PIECEWEIGHT                 1107
#define IDC_SPECULARPOWER               1108
#define IDC_SPECULARPOWER_LABEL         1109
#define IDC_SPECULARSCALE_LABEL         1110
#define IDC_TEXTUREINDEX_LABEL          1111
#define IDC_SCALESKELETON               1112
#define IDC_TIME_OFFSET                 1113
#define IDC_IMPORT_SOCKETS              1117
#define IDC_ANIMLIST2                   1119
#define IDC_SOCKETEDIT_ROTX             1120
#define IDC_SOCKETEDIT_ROTY             1121
#define IDC_SOCKETEDIT_ROTZ             1122
#define IDC_SOCKETEDIT_POSX             1123
#define IDC_SOCKETEDIT_POSY             1124
#define IDC_SOCKETEDIT_POSZ             1125
#define IDC_SOCKETEDIT_NAME             1126
#define IDC_SOCKETEDIT_ATTACHMENT_LOAD  1127
#define IDC_SOCKETEDIT_SCLX             1128
#define IDC_SOCKETEDIT_SCLY             1129
#define IDC_ANIMATION2                  1130
#define IDC_SOCKETEDIT_SCLZ             1130
#define IDC_SOCKETEDIT_NODENAME         1131
#define IDC_FOV_SLIDER                  1134
#define IDC_FOV_EDIT                    1135
#define IDC_EXPORT_D3D_FORCE_BONES_PER_VERT 1136
#define IDC_EXPORT_D3D_BONES_PER_VERT   1137
#define IDC_ANIMATION3                  1138
#define IDC_EXPORT_D3D_FORCE_BONES_PER_TRI 1138
#define IDC_MIN                         1138
#define IDC_ANIMATION4                  1139
#define IDC_EXPORT_D3D_BONES_PER_TRI    1139
#define IDC_MAX                         1139
#define IDC_ANIMATION1                  1140
#define IDC_EXPORT_D3D_ALLOW_RENDER_DIRECT 1140
#define IDC_MID                         1140
#define IDC_EXPORT_USED3DTNL            1140
#define IDC_EXPORT_D3D_FORCE_BONES_PER_TRI2 1141
#define IDC_SAVELOADLOG                 1141
#define IDC_EXPORT_D3D_FORCE_CUSTOM_TRANSFORMS 1142
#define IDC_LOADFILENAME                1143
#define IDC_EXPORT_USEMATRIXPALETTES    1143
#define IDC_LOADLOG                     1144
#define ID_APPLY                        1145
#define ID_DONE                         1146
#define IDC_PROGRESS                    1151
#define IDC_CHOOSEDIFFUSE               1153
#define IDC_CHOOSEAMBIENT               1154
#define IDC_DIFFUSE                     1155
#define IDC_CHOOSEEMISSIVE              1156
#define IDC_CHOOSESPECULAR              1157
#define IDC_AMBIENT                     1158
#define IDC_EMISSIVE                    1159
#define IDC_SPECULAR                    1160
#define IDC_SPIN2                       1163
#define IDC_SPINRENDERPRIORITY          1163
#define IDC_SPIN3                       1164
#define IDC_SPIN4                       1165
#define IDC_SPIN5                       1166
#define IDC_ALPHA                       1167
#define IDC_EXPORT_MINBONEWEIGHT        1168
#define IDC_SPIN6                       1168
#define IDC_SPIN7                       1169
#define IDC_SPIN8                       1170
#define IDC_NUMTEXTURES                 1171
#define IDC_SPIN1                       1172
#define IDC_RENDERSTYLEINDEX            1173
#define IDC_END_TIME                    1174
#define IDC_LODDISTANCE                 1174
#define IDC_CHECK1                      1175
#define IDC_SPIN9                       1175
#define IDC_DIABLEOBB                   1175
#define IDC_ENABLE_OBB                  1175
#define IDC_MOVEMENT_ENCODING           1175
#define IDC_EXPORT_PAUSE_AFTER_COMPILE  1175
#define IDC_RENDERPRIORITY              1175
#define IDC_EDIT_OBB_POS_X              1176
#define IDC_MAX_DIST                    1178
#define IDC_MIN_DIST                    1180
#define IDC_LOD_OFFSET                  1181
#define IDC_MIN_LOD                     1182
#define IDC_SCROLLBAR2                  1185
#define IDC_MAX_EDGE_LENGTH             1187
#define IDC_EDIT_OBB_POS_X_TRACK        1188
#define IDC_EDIT_OBB_POS_Y_TRACK        1189
#define IDC_EDIT_OBB_POS_Z_TRACK        1190
#define IDC_EDIT_OBB_ROT_X_TRACK        1191
#define IDC_COMBO_COMPRESSION_TYPE      1191
#define IDC_EDIT_OBB_ROT_Y_TRACK        1192
#define IDC_NO_GEOM                     1192
#define IDC_EDIT_OBB_ROT_Z_TRACK        1193
#define IDC_CHECK_NULL_LOD              1193
#define IDC_EDIT_OBB_SIZ_X_TRACK        1194
#define IDC_EDIT_OBB_SIZ_Y_TRACK        1195
#define IDC_EDIT_DIMS_X                 1195
#define IDC_EDIT_OBB_SIZ_Z_TRACK        1196
#define IDC_EDIT_DIMS_Y                 1196
#define IDC_EDIT_DIMS_Z                 1197
#define IDC_STATIC_ANIM_NAME            1198
#define IDC_STREAM0_OPTIONS_POSITION    1199
#define IDC_STREAM0_OPTIONS_NORMAL      1200
#define IDC_STREAM0_OPTIONS_COLOR       1201
#define IDC_STREAM0_OPTIONS_UV1         1202
#define IDC_STREAM0_OPTIONS_UV2         1203
#define IDC_STREAM0_OPTIONS_UV3         1204
#define IDC_CHECK8                      1205
#define IDC_STREAM0_OPTIONS_UV4         1205
#define IDC_STREAM0_OPTIONS_TANGENT     1206
#define ID_CLIP_AFTER                   32772
#define ID_CLIP_BEFORE                  32773
#define ID_DELETE_KEYFRAME              32774
#define ID_EDIT_KEYFRAME_TIME           32775
#define ID_TAG_KEYFRAME                 32776
#define ID_UNTAG_KEYFRAME               32777
#define ID_DELETE_TAGGED_KEYFRAMES      32778
#define ID_EDITKEYFRAMESTRING           32779
#define ID_SELECTALL                    32780
#define ID_TAGALL                       32781
#define ID_UNTAGALL                     32782
#define IDS_NODUPLICATECHILDMODELNAMES  32783
#define IDS_INVALIDANIMINDEX            32784
#define IDC_UNROTATE_TOP_NODE           32785
#define IDS_CANTEDITBASEMODEL           32785
#define ID_GENERATE_VERTEX_NORMALS      32788
#define ID_REVERSE_ANIMATION            32789
#define IDC_ROTATION_BUTTON             32790
#define ID_HELP_ABOUT                   32791
#define IDS_ADDCHILDMODEL               32791
#define ID_MODEL_REMOVENODE             32792
#define IDS_MODELEDIT_CAPTION           32792
#define ID_SELECT_NULL_NODES            32793
#define IDS_CANTADDCHILDMODEL           32793
#define IDS_ASKSAVERELOAD               32794
#define ID_ADDCHILDMODEL                32795
#define IDS_CANT_LOAD_CHILD_MODEL       32795
#define ID_REMOVECHILDMODEL             32796
#define IDS_NEED_TO_CALC_BOUNDING       32796
#define IDS_CANTLOADCHILDMODEL          32797
#define ID_REBUILDCHILDMODELTREE        32797
#define IDS_ADDEDCHILDSUCCESSFULLY      32798
#define IDS_NOTSKELETAL                 32799
#define IDS_TREESINVALID                32800
#define IDS_CANTCREATETREE              32801
#define ID_ADD_SOCKET                   32801
#define IDS_CANTCALCBOUNDRADIUS         32802
#define ID_REMOVE_SOCKET                32802
#define ID_SHOW_SOCKETS                 32803
#define IDS_ENTER_SOCKETNAME            32803
#define ID_SHOW_ATTACHMENTS             32804
#define IDS_SOCKET_EDIT                 32804
#define ID_RENAME_SOCKET                32805
#define IDS_RELATION_EDIT               32805
#define ID_ANIMATION_MERGE              32806
#define IDS_ENTER_UNIQUE_ANIM_NAME      32806
#define ID_SHOW_NORMALS                 32807
#define IDS_ENTER_GLOBAL_RADIUS         32807
#define ID_MODEL_MOOD                   32808
#define IDS_NEWWEIGHTSET                32808
#define ID_INTERNAL_RADIUS              32809
#define IDS_ENTERWEIGHTSETNAME          32809
#define ID_EDIT_WEIGHTS                 32810
#define ID_SHOW_NORMALREF               32811
#define ID_OPTIONS_PROFILE              32812
#define ID_PIECE_INFO                   32813
#define ID_INSERT_TIME_DELAY            32814
#define ID_SOLID_ATTACHMENTS            32815
#define IDS_DUPLICATE_ANIM_NAME         32816
#define IDC_DELETEANIM                  32817
#define IDC_SORTANIM_NAME               32818
#define IDC_SORTANIM_RELATION           32819
#define ID_OPTIONS_NEWBACKGROUND        32820
#define ID_OPTIONS_SHOWORIGINALMODEL    32821
#define IDC_ANIMATIONINTERPOLAION       32822
#define IDC_CHANGE_FOV                  32823
#define IDC_EXPORT_D3D                  32824
#define IDS_DEFLTALOGFILENAME           32824
#define IDC_EXPORT_ABC                  32825
#define IDC_DIFF_RED                    32826
#define EXPORT_PS2_LTB                  32826
#define IDC_DIFF_GRN                    32827
#define ID_IMPORTMODELSTRINGKEYS        32827
#define IDC_DIFF_BLU                    32828
#define IDC_DIFF_A                      32829
#define IDC_AMB_RED                     32830
#define IDC_AMB_GRN                     32831
#define IDC_AMB_BLU                     32832
#define IDC_EMIS_RED                    32833
#define IDC_EMIS_GRN                    32834
#define IDC_EMIS_BLU                    32835
#define IDC_SPEC_RED                    32836
#define IDC_SPEC_GRN                    32837
#define IDC_SPEC_BLU                    32838
#define IDC_SHININESS                   32839
#define IDC_DIFFUSE_COLOR               32840
#define IDC_AMBIENT_COLOR               32841
#define IDC_EMISSIVE_COLOR              32842
#define IDC_SPECULAR_COLOR              32843
#define IDS_DEFLTALOGEXTENSION          32844
#define IDS_LTALOGFILTER                32845
#define IDS_LOADMODELFILTER             32846
#define IDS_ADDCHILDMODELEXT            32847
#define IDS_ADDCHILDMODELFILTER         32848
#define IDS_IMPORTFILTER                32849
#define IDS_IMPORTDEFEXT                32850
#define ID_EXPORTMODELSTRINGKEYS        32851
#define IDS_SAVEASFILTER                32851
#define ID_OPTIONS_SHOWVERTEXWEIGHTING  32880
#define ID_CHANGE_AMBIENT_COLOR         32881
#define ID_NODEEDIT_EDITOBB             32881
#define ID_NODEEDIT_RENAME              32882
#define ID_NODEEDIT_DELETE              32883
#define ID_USEANIMDIMS                  32884
#define ID_CALC_INTERNAL_RADIUS         32884
#define IDC_SET_PROJ_DIR                32885
#define ID_SET_PROJ_DIR                 32886
#define ID_OPTIONS_LOADCONFIRM          32886
#define ID_PIECE_SET_TEXTURE            32887
#define ID_PIECE_SELECT_NONE            32888
#define ID_PIECE_BUILD_LODS             32889
#define ID_SHOW_TEXTURES                32890
#define ID_PIECEEDIT_EXPANDALL          32891
#define ID_PIECEEDIT_COLLAPSEALL        32892
#define ID_PIECE_REMOVE_LODS            32893
#define IDC_CALC_OBB                    32894
#define ID_MODEL_EXPORTWEIGHTSETS       32895
#define ID_MODEL_IMPORTWEIGHTSETS       32896
#define ID_IMPORTLODS_EXPANDALL         32897
#define ID_IMPORTLODS_COLLAPSEALL       32898
#define IDC_SAVE_AND_COMPILE            32899
#define IDC_COMPILE                     32900
#define ID_PIECE_MERGE                  32901
#define ID_NODEEDIT_LOOKAT              32902
#define ID_SOCKETEDIT_LOOKAT            32903
#define ID_CREATE_NULL_LOD              32904
#define IDS_ENTER_NULL_LOD_DISTANCE     32905
#define IDS_ENTER_NULL_LOD_DISTANCE_CAPTION 32906
#define ID_ANIMATION_CREATEANIMFROMBINDPOSE 32906

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32907
#define _APS_NEXT_CONTROL_VALUE         1207
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
