//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CoolServ.rc
//
#define IDS_NETERR_GENERIC              1
#define IDS_NETERR_SELECTSERVICE        2
#define IDS_NETERR_FILLSERVICE          3
#define IDC_COMMANDS_OPTIONS            3
#define IDS_NETERR_JOINSESSION          4
#define IDS_NETERR_HOSTSESSION          5
#define IDS_NETERR_INIT                 6
#define IDS_REZBASE                     7
#define IDS_INSERTCD                    8
#define IDS_APPNAME                     9
#define IDS_CONFIGFILE                  10
#define IDS_APPNAME_AO                  11
#define IDS_CONFIGFILE_AO               12
#define IDM_ABOUTBOX                    0x0010
#define IDS_NETWIZ_ITEMS_NONE           53
#define IDS_NETWIZ_ITEMS_HALF           54
#define IDS_NETWIZ_ITEMS_NORMAL         55
#define IDS_NETWIZ_ITEMS_DOUBLE         56
#define IDS_NETWIZ_ITEMS_INSANE         57
#define IDS_NETWIZ_HEAL_NOHEALING       58
#define IDS_NETWIZ_HEAL_REALLYSLOW      59
#define IDS_NETWIZ_HEAL_SLOW            60
#define IDS_NETWIZ_HEAL_NORMAL          61
#define IDS_NETWIZ_HEAL_FAST            62
#define IDS_NETWIZ_HEAL_REALLYFAST      63
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_COOLSERV_DIALOG             102
#define IDS_ERROR_REZFILE               102
#define IDS_ERROR_LOADREZ               103
#define IDS_ERROR_LOADSERVER            104
#define IDS_ERROR_ACCESSSERVER          105
#define IDS_ERROR_MEMORY                106
#define IDS_HELP_RUNSPEED               107
#define IDS_TITLE_RUNSPEED              108
#define IDS_HELP_MISSILESPEED           109
#define IDS_TITLE_MISSILESPEED          110
#define IDS_HELP_TIMESPEED              111
#define IDS_TITLE_TIMESPEED             112
#define IDS_HELP_NIGHTCOLOR             113
#define IDS_TITLE_NIGHTCOLOR            114
#define IDS_HELP_RESPAWNSCALE           115
#define IDS_TITLE_RESPAWNSCALE          116
#define IDS_HELP_HEALSCALE              117
#define IDS_TITLE_HEALSCALE             118
#define IDS_TITLE_DASHGO                119
#define IDS_HELP_DASHGO                 120
#define IDS_CHECKEXIT                   121
#define IDS_CONSOLE_INITSERVER          122
#define IDS_CONSOLE_SERVERINITED        123
#define IDS_CONSOLE_UNABLETOHOST        124
#define IDS_CONSOLE_SERVERRUNNING       125
#define IDS_CONSOLE_LASTPLAYERLEFT      126
#define IDS_CONSOLE_UNABLETOSTARTWORLD  127
#define IDR_MAINFRAME                   128
#define IDS_DEFAULTSERVERNAME           128
#define IDD_SHOGOSERVER                 129
#define IDS_SPYGAMENAME                 129
#define IDD_GAMESERVER                  129
#define IDS_REAL_APPNAME                130
#define IDS_GAMETYPE_DEATHMATCH         130
#define IDS_SPYGAMEVER                  131
#define IDS_SPYGAMEKEY                  132
#define IDS_WEBGAMENAME                 133
#define IDS_WEBGAMEVER                  134
#define IDS_GAMETYPE_UNKNOWN            135
#define IDS_GAMETYPE_CAPTUREFLAG        136
#define IDS_GAMETYPE_COOPERATIVE        137
#define IDS_GAMETYPE_TEAM               138
#define IDS_GAMETYPE_SOCCER             139
#define IDS_GAMETYPE_TOETAG             140
#define IDS_WEBREGURL                   141
#define IDS_NEXTLEVEL                   142
#define IDS_DEFAULTSERVERNAME_AO        143
#define IDS_SPYGAMEVER_AO               144
#define IDS_WEBGAMENAME_AO              145
#define IDS_WEBGAMEVER_AO               146
#define IDS_DIALOGTITLE_AO              147
#define IDC_SERVER_MESSAGES             1000
#define IDC_STARTSERVER                 1001
#define IDC_SHUTDOWNSERVER              1002
#define IDC_SERVICELIST                 1002
#define IDC_SERVER_NAME                 1003
#define IDC_BACK                        1003
#define IDC_PLAYER_LIST                 1004
#define IDC_NEXT                        1004
#define IDC_WORLD_NAME                  1006
#define IDC_RESOURCES                   1008
#define IDC_DEATHMATCH                  1008
#define IDC_COMMAND_BOX                 1009
#define IDC_COOPERATIVE                 1009
#define ID_MY_QUIT                      1010
#define IDC_CAPTURETHEFLAG              1010
#define IDC_SETTINGS                    1011
#define IDC_NAME                        1011
#define IDC_APPLY                       1012
#define IDC_DEFAULTS                    1013
#define IDC_LEVELS_LIST                 1014
#define IDC_PLAYERS_LIST                1015
#define IDC_PLAYERS_BOOT                1016
#define IDC_CONSOLE_COMMAND             1018
#define IDC_SERVER                      1019
#define IDC_QUIT                        1020
#define IDC_CONSOLE_WINDOW              1021
#define IDC_AFTERFRAGS                  1022
#define IDC_FRAGS                       1023
#define IDC_AFTERMINUTES                1024
#define IDC_MINUTES                     1025
#define IDC_GAMELIST                    1029
#define IDC_RETAILLIST                  1030
#define IDC_CUSTOMLIST                  1031
#define IDC_ADDRETAIL                   1032
#define IDC_ADDCUSTOM                   1033
#define IDC_REMOVE                      1034
#define ID_INIT                         1035
#define IDC_SERVER_VERSION              1036
#define IDC_SERVER_TIME                 1037
#define IDC_SERVER_SERVICE              1038
#define IDC_GAME_PLAYERS                1039
#define IDC_GAME_CURLEVEL               1040
#define IDC_GAME_NEXTLEVEL              1041
#define IDC_GAME_TIME                   1042
#define IDC_GAME_GOAL                   1043
#define IDC_CONSOLE_CLEAR               1044
#define IDC_MAXPLAYERS                  1044
#define IDC_CONSOLE_SEND                1045
#define IDC_PORT                        1045
#define IDC_PORTNUM                     1045
#define IDC_COMMANDS_NEXTLEVEL          1046
#define IDC_AMMO_RESPAWN                1046
#define IDC_PORTNUMTEXT                 1046
#define ID_UPDATE                       1047
#define IDC_ARMOR_RESPAWN               1047
#define IDC_SERVERREG                   1048
#define IDC_AMMO_LEVEL                  1048
#define IDC_UPDATEINFO                  1049
#define IDC_FALLDAMAGE                  1049
#define IDC_ARMOR_LEVEL                 1049
#define IDC_SOURCELIST                  1050
#define IDC_USEGAMESPY                  1050
#define IDC_HEALTH_RESPAWN              1050
#define IDC_DESTLIST                    1051
#define IDC_HEALTH_LEVEL                1051
#define IDC_ADD                         1052
#define IDC_POWERUPS_RESPAWN            1052
#define IDC_SAVE                        1053
#define IDC_HEALRATE                    1053
#define IDC_POWERUPS_LEVEL              1053
#define IDC_TRACTORBEAM                 1054
#define IDC_DOUBLEJUMP                  1055
#define IDC_RAMMINGDAMAGE               1056
#define IDC_RUNSPEED                    1057
#define IDC_MISSILESPEED                1058
#define IDC_RESPAWNSCALE                1059
#define IDC_HEALSCALE                   1060
#define IDC_HELP_RUNSPEED               1061
#define IDC_HELP_MISSILESPEED           1062
#define IDC_PORT_TEXT                   1062
#define IDC_TIMESPEED                   1063
#define IDC_NIGHTCOLOR                  1064
#define IDC_HELP_TIMESPEED              1065
#define IDC_HELP_NIGHTCOLOR             1066
#define IDC_HELP_RESPAWNSCALE           1067
#define IDC_HELP_HEALSCALE              1068
#define IDC_COLORPICKER                 1069
#define IDC_BB                          5000
#define IDC_CTF                         5001
#define IDC_FRIENDLYFIRE                5001
#define IDC_TEAMS                       5002
#define IDC_ONLYFLAGSCORES              5003
#define IDC_SOCCER                      5003
#define IDC_USETEAMSIZE                 5004
#define IDC_NEGFRAGS                    5005
#define IDC_FLAGVALUE                   5006
#define IDC_ONLYGOALSCORES              5007
#define IDC_GOALVALUE                   5008
#define IDC_SKIN_SOCCER                 5009
#define IDC_SKIN_ZOMBIE                 5010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
