//-------------------------------------------------------------------------
//
// MODULE  : Cheatdefs.h
//
// PURPOSE : Cheat code defines
//
// (c) 1997-2002 Monolith Productions, Inc.  All Rights Reserved
//
//-------------------------------------------------------------------------

#ifndef __CHEATDEFS_H
#define __CHEATDEFS_H

enum CheatCode
{
	CHEAT_NONE = -1,

// Retail cheats...
	CHEAT_GOD,
	CHEAT_AMMO,
	CHEAT_ARMOR,
	CHEAT_HEALTH,
	CHEAT_INVISIBLE,
	CHEAT_POS,
	CHEAT_KFA,
	CHEAT_FULL_WEAPONS,
	CHEAT_TEARS,
	CHEAT_SNOWMOBILE,
	CHEAT_MODSQUAD,
	CHEAT_FULL_GEAR,
	CHEAT_EXITLEVEL,
	CHEAT_NEXTMISSION,
	CHEAT_BOOT,
	CHEAT_VERSION,
	CHEAT_BUILDGUID,
	CHEAT_GIMMEGUN,
	CHEAT_GIMMEMOD,
	CHEAT_GIMMEGEAR,
	CHEAT_GIMMEAMMO,
	CHEAT_CONSOLE,
	CHEAT_SKILLZ,
	CHEAT_ENDGAME,
	CHEAT_BODYGOLFING,
	CHEAT_CHASETOGGLE,

// Development only cheats below this point...
	CHEAT_CLIP,
	CHEAT_TELEPORT,
	CHEAT_POSWEAPON,
  	CHEAT_POSWEAPON_MUZZLE,
	CHEAT_WEAPON_BREACHOFFSET,
	CHEAT_LIGHTSCALE,
	CHEAT_LIGHTADD,
	CHEAT_FOV,
	CHEAT_REMOVEAI,
	CHEAT_TRIGGERBOX,
	CHEAT_POS1STCAM,
	CHEAT_CAM_POSROT,
	CHEAT_MAX
};

#endif
